'use client';

import { useEffect, useMemo, useState } from 'react';
import { AlertTriangle, CheckCircle2, Download, RefreshCw } from 'lucide-react';
import { PageHeader } from '@/components/ui/page-header';
import { Card } from '@/components/ui/card';
import { Button, PrimaryButton } from '@/components/ui/buttons';
import { Input } from '@/components/forms/input';

type Issue = { code: string; severity: 'matched' | 'warning' | 'exception'; message: string };
type Row = { orderId: string; orderNumber: string; invoiceId: string; invoiceNumber: string; customerName: string; customerEmail: string; currency: string; orderTotalMinor: number; invoiceTotalMinor: number; creditedMinor: number; netCollectedMinor: number; paymentStatus: string; paymentProvider: string; paymentReference: string; issuedAt: string; paidAt: string; status: 'matched' | 'warning' | 'exception'; issues: Issue[] };
type Report = { currency: string; generatedAt: string; summary: { invoiceCount: number; matchedCount: number; warningCount: number; exceptionCount: number; invoicedMinor: number; creditedMinor: number; netSalesMinor: number; vatMinor: number; outstandingInvoiceMinor: number; paidOrdersWithoutInvoice: number }; rows: Row[]; missingInvoiceOrders: Array<{ id: string; orderNumber: string; customerName: string; customerEmail: string; totalMinor: number; currency: string; paidAt: string; paymentReference: string }> };
function money(value: number, currency = 'GBP') { return new Intl.NumberFormat('en-GB', { style: 'currency', currency }).format(Number(value || 0) / 100); }
function date(value: string) { try { return value ? new Intl.DateTimeFormat('en-GB', { dateStyle: 'medium' }).format(new Date(value)) : '—'; } catch { return '—'; } }

export function AccountingReconciliationPage() {
  const [report, setReport] = useState<Report | null>(null);
  const [loading, setLoading] = useState(true);
  const [error, setError] = useState('');
  const [filters, setFilters] = useState({ from: '', to: '', search: '' });
  const query = useMemo(() => { const params = new URLSearchParams(); if (filters.from) params.set('from', filters.from); if (filters.to) params.set('to', filters.to); if (filters.search.trim()) params.set('search', filters.search.trim()); return params.toString(); }, [filters]);
  async function load() { setLoading(true); setError(''); try { const response = await fetch(`/api/internal/accounting/reconciliation${query ? `?${query}` : ''}`, { cache: 'no-store' }); const payload = await response.json().catch(() => null); if (!response.ok || payload?.ok === false) throw new Error(payload?.error || 'Reconciliation could not be loaded.'); setReport(payload.data); } catch (next) { setError(next instanceof Error ? next.message : 'Reconciliation could not be loaded.'); } finally { setLoading(false); } }
  useEffect(() => { void load(); }, []);
  function exportHref(kind: string) { const params = new URLSearchParams(query); params.set('kind', kind); return `/api/internal/accounting/reconciliation/export?${params.toString()}`; }
  const summary = report?.summary;
  return <div>
    <PageHeader title="Accounting Reconciliation" subtitle="Match paid orders, formal invoices, credit notes and payment references before exporting bookkeeping records." actions={<><Button onClick={() => void load()} disabled={loading}><RefreshCw size={14} /> Refresh</Button><a href={exportHref('reconciliation')}><PrimaryButton type="button"><Download size={14} /> Export exceptions</PrimaryButton></a></>} />
    <Card className="mb-4"><div className="grid gap-3 md:grid-cols-[1fr_1fr_2fr_auto]"><Input type="date" value={filters.from} onChange={(event) => setFilters((current) => ({ ...current, from: event.target.value }))} /><Input type="date" value={filters.to} onChange={(event) => setFilters((current) => ({ ...current, to: event.target.value }))} /><Input value={filters.search} onChange={(event) => setFilters((current) => ({ ...current, search: event.target.value }))} placeholder="Invoice, order or customer" /><PrimaryButton onClick={() => void load()} disabled={loading}>Apply</PrimaryButton></div><div className="mt-4 flex flex-wrap gap-2"><a href={exportHref('sales')}><Button type="button"><Download size={14} /> Sales CSV</Button></a><a href={exportHref('vat')}><Button type="button"><Download size={14} /> VAT CSV</Button></a><a href={exportHref('credit-notes')}><Button type="button"><Download size={14} /> Credit notes CSV</Button></a></div></Card>
    {error ? <div className="mb-4 rounded-xl border border-red-500/30 bg-red-500/10 p-3 text-sm text-red-200">{error}</div> : null}
    {loading ? <Card>Building the reconciliation report…</Card> : null}
    {!loading && report ? <>
      <div className="mb-4 grid gap-3 sm:grid-cols-2 xl:grid-cols-6">{[
        ['Invoices', summary?.invoiceCount || 0], ['Matched', summary?.matchedCount || 0], ['Warnings', summary?.warningCount || 0], ['Exceptions', summary?.exceptionCount || 0], ['Net sales', money(summary?.netSalesMinor || 0, report.currency)], ['VAT', money(summary?.vatMinor || 0, report.currency)],
      ].map(([label, value]) => <Card key={String(label)}><div className="text-xs uppercase tracking-wide text-textMuted">{label}</div><div className="mt-2 text-2xl font-semibold text-white">{value}</div></Card>)}</div>
      {report.missingInvoiceOrders.length ? <Card className="mb-4 border-red-500/20"><div className="flex items-center gap-2 text-sm font-semibold text-red-200"><AlertTriangle size={16} /> Paid orders without invoices</div><div className="mt-4 space-y-2">{report.missingInvoiceOrders.map((order) => <div key={order.id} className="flex flex-wrap items-center justify-between gap-3 rounded-xl bg-panelMuted p-3 text-sm"><div><strong className="text-white">{order.orderNumber}</strong><div className="text-xs text-textMuted">{order.customerName} · {order.customerEmail || 'No email'}</div></div><div className="text-right"><strong className="text-white">{money(order.totalMinor, order.currency)}</strong><div className="text-xs text-red-200">Invoice required</div></div></div>)}</div></Card> : null}
      <Card><div className="mb-4 flex items-center justify-between"><h3 className="text-sm font-semibold text-white">Invoice reconciliation</h3><span className="text-xs text-textMuted">Generated {date(report.generatedAt)}</span></div><div className="overflow-x-auto"><table className="w-full min-w-[1050px] text-left text-xs"><thead className="text-textMuted"><tr>{['Status','Invoice','Order','Customer','Invoice total','Credits','Net collected','Payment','Reference','Issues'].map((label) => <th key={label} className="border-b border-white/8 px-3 py-3 font-medium">{label}</th>)}</tr></thead><tbody>{report.rows.map((row) => <tr key={row.invoiceId} className="border-b border-white/5 align-top"><td className="px-3 py-3">{row.status === 'matched' ? <span className="inline-flex items-center gap-1 text-emerald-300"><CheckCircle2 size={14} /> Matched</span> : <span className={row.status === 'exception' ? 'text-red-300' : 'text-amber-300'}>{row.status}</span>}</td><td className="px-3 py-3 font-medium text-white">{row.invoiceNumber}<div className="mt-1 text-textMuted">{date(row.issuedAt)}</div></td><td className="px-3 py-3 text-white">{row.orderNumber}</td><td className="px-3 py-3 text-white">{row.customerName}<div className="mt-1 text-textMuted">{row.customerEmail}</div></td><td className="px-3 py-3 text-white">{money(row.invoiceTotalMinor, row.currency)}</td><td className="px-3 py-3 text-white">{money(row.creditedMinor, row.currency)}</td><td className="px-3 py-3 text-white">{money(row.netCollectedMinor, row.currency)}</td><td className="px-3 py-3 text-white">{row.paymentStatus || 'Unknown'}<div className="mt-1 text-textMuted">{row.paymentProvider || '—'}</div></td><td className="max-w-[180px] break-all px-3 py-3 text-textMuted">{row.paymentReference || 'Missing'}</td><td className="max-w-[320px] px-3 py-3">{row.issues.length ? <div className="space-y-1">{row.issues.map((issue) => <div key={issue.code} title={issue.message} className={issue.severity === 'exception' ? 'text-red-300' : 'text-amber-300'}>{issue.code}</div>)}</div> : <span className="text-emerald-300">No issues</span>}</td></tr>)}</tbody></table></div></Card>
    </> : null}
  </div>;
}
