'use client';

import Link from 'next/link';
import { useCallback, useEffect, useMemo, useState } from 'react';
import { Input } from '@/components/forms/input';
import { Select } from '@/components/forms/select';
import { PageHeader } from '@/components/ui/page-header';
import { Button, PrimaryButton } from '@/components/ui/buttons';
import { Card } from '@/components/ui/card';

type Product = { id: string; name?: string; title?: string; slug: string; categorySlug?: string; categoryId?: string; priceFromMinor?: number; currency?: string; metadataJson?: Record<string, any> };
type QuoteLine = { id?: string; productId?: string; productSlug?: string; categorySlug?: string; productName: string; description?: string; quantity: number; unitNetMinor: number; netMinor?: number; vatRate: number; vatMinor?: number; grossMinor?: number; selectedOptions?: Array<{ key: string; label: string; value: string; slug?: string }>; metadataJson?: Record<string, unknown> };
type FormalQuote = { id: string; quoteNumber: string; customerId: string; customerName: string; customerEmail: string; customerPhone: string; customerCompany: string; storeSlug: string; title: string; status: string; currency: string; subtotalMinor: number; vatMinor: number; totalMinor: number; customerNotes: string; internalNotes: string; expiresAt: string; revision: number; updatedAt: string; convertedOrderId: string; lines: QuoteLine[]; revisions?: Array<{ id: string; revision: number; action: string; actorType: string; note: string; createdAt: string }> };
const statuses = ['requested', 'draft', 'sent', 'viewed', 'approved', 'declined', 'expired', 'converted', 'paid'];
function clean(value: unknown) { return String(value || '').trim(); }
function money(value: number, currency = 'GBP') { return new Intl.NumberFormat('en-GB', { style: 'currency', currency }).format(Number(value || 0) / 100); }
function dateInput(value: string) { try { return value ? new Date(value).toISOString().slice(0, 10) : ''; } catch { return ''; } }
function statusLabel(value: string) { return clean(value).replace(/[-_]/g, ' ').replace(/\b\w/g, (letter) => letter.toUpperCase()); }
function productName(product?: Product) { return clean(product?.name || product?.title || product?.slug || 'Print item'); }
function productLine(product?: Product): QuoteLine { const unit = Math.max(0, Number(product?.priceFromMinor || product?.metadataJson?.pricing?.priceFromMinor || 0)); const vatRate = Number(product?.metadataJson?.vatRate ?? product?.metadataJson?.pricing?.vatRate ?? 20); return { id: `line-${Date.now()}-${Math.random().toString(36).slice(2, 6)}`, productId: product?.id || product?.slug || '', productSlug: product?.slug || '', categorySlug: clean(product?.categorySlug || product?.categoryId), productName: productName(product), description: '', quantity: 1, unitNetMinor: unit, vatRate: Number.isFinite(vatRate) ? vatRate : 20, selectedOptions: [], metadataJson: { source: 'formal-quote-admin' } }; }
function lineTotals(line: QuoteLine) { const quantity = Math.max(1, Number(line.quantity || 1)); const netMinor = Math.max(0, Math.round(Number(line.unitNetMinor || 0) * quantity)); const vatMinor = Math.round(netMinor * Math.max(0, Number(line.vatRate || 0)) / 100); return { netMinor, vatMinor, grossMinor: netMinor + vatMinor }; }
function blankQuote(product?: Product): FormalQuote { const expires = new Date(Date.now() + 30 * 86400000).toISOString(); return { id: '', quoteNumber: 'New quote', customerId: '', customerName: '', customerEmail: '', customerPhone: '', customerCompany: '', storeSlug: 'main', title: product ? `${productName(product)} quotation` : 'Print quotation', status: 'draft', currency: product?.currency || 'GBP', subtotalMinor: 0, vatMinor: 0, totalMinor: 0, customerNotes: '', internalNotes: '', expiresAt: expires, revision: 0, updatedAt: '', convertedOrderId: '', lines: [productLine(product)], revisions: [] }; }

async function loadProducts(): Promise<Product[]> { try { const response = await fetch('/api/internal/catalog/products?limit=500', { cache: 'no-store' }); const payload = await response.json().catch(() => ({})); return Array.isArray(payload.data?.items) ? payload.data.items : []; } catch { return []; } }

export function QuotesPage() {
  const [quotes, setQuotes] = useState<FormalQuote[]>([]);
  const [products, setProducts] = useState<Product[]>([]);
  const [selected, setSelected] = useState<FormalQuote | null>(null);
  const [search, setSearch] = useState('');
  const [filter, setFilter] = useState('all');
  const [busy, setBusy] = useState('');
  const [notice, setNotice] = useState('');
  const [error, setError] = useState('');

  const load = useCallback(async () => {
    const [quoteResponse, nextProducts] = await Promise.all([fetch('/api/internal/formal-quotes?limit=500', { cache: 'no-store' }), loadProducts()]);
    const payload = await quoteResponse.json().catch(() => ({}));
    const nextQuotes = Array.isArray(payload.data?.items) ? payload.data.items : [];
    setQuotes(nextQuotes); setProducts(nextProducts);
    setSelected((current) => current?.id ? nextQuotes.find((item: FormalQuote) => item.id === current.id) || nextQuotes[0] || blankQuote(nextProducts[0]) : nextQuotes[0] || blankQuote(nextProducts[0]));
  }, []);
  useEffect(() => { load().catch((next) => setError(next instanceof Error ? next.message : 'Quotes could not be loaded.')); }, [load]);

  const shown = useMemo(() => quotes.filter((quote) => { const haystack = `${quote.quoteNumber} ${quote.customerName} ${quote.customerEmail} ${quote.title} ${quote.status}`.toLowerCase(); return (!search || haystack.includes(search.toLowerCase())) && (filter === 'all' || quote.status === filter); }), [quotes, search, filter]);
  const totals = useMemo(() => (selected?.lines || []).reduce((sum, line) => { const next = lineTotals(line); return { subtotalMinor: sum.subtotalMinor + next.netMinor, vatMinor: sum.vatMinor + next.vatMinor, totalMinor: sum.totalMinor + next.grossMinor }; }, { subtotalMinor: 0, vatMinor: 0, totalMinor: 0 }), [selected]);

  function patchQuote(patch: Partial<FormalQuote>) { setSelected((current) => current ? { ...current, ...patch } : current); }
  function patchLine(index: number, patch: Partial<QuoteLine>) { setSelected((current) => current ? { ...current, lines: current.lines.map((line, position) => position === index ? { ...line, ...patch } : line) } : current); }
  function removeLine(index: number) { setSelected((current) => current ? { ...current, lines: current.lines.filter((_, position) => position !== index) } : current); }
  function addLine(productId?: string) { const product = products.find((item) => item.id === productId || item.slug === productId) || products[0]; setSelected((current) => current ? { ...current, lines: [...current.lines, productLine(product)] } : blankQuote(product)); }
  function startNew() { setSelected(blankQuote(products[0])); setNotice(''); setError(''); }
  async function openQuote(id: string) { setBusy(`open:${id}`); try { const response = await fetch(`/api/internal/formal-quotes/${encodeURIComponent(id)}`, { cache: 'no-store' }); const payload = await response.json().catch(() => ({})); if (!response.ok || payload?.ok === false) throw new Error(payload?.error || 'Quote could not be loaded.'); setSelected(payload.data); } catch (next) { setError(next instanceof Error ? next.message : 'Quote could not be loaded.'); } finally { setBusy(''); } }
  async function save() {
    if (!selected) return;
    setBusy('save'); setError(''); setNotice('');
    try {
      const body = { ...selected, subtotalMinor: totals.subtotalMinor, vatMinor: totals.vatMinor, totalMinor: totals.totalMinor, lines: selected.lines.map((line) => ({ ...line, ...lineTotals(line) })) };
      const response = await fetch(selected.id ? `/api/internal/formal-quotes/${encodeURIComponent(selected.id)}` : '/api/internal/formal-quotes', { method: selected.id ? 'PATCH' : 'POST', headers: { 'Content-Type': 'application/json' }, body: JSON.stringify(selected.id ? { action: 'update', ...body } : body) });
      const payload = await response.json().catch(() => ({})); if (!response.ok || payload?.ok === false) throw new Error(payload?.error || 'Quote could not be saved.');
      setSelected(payload.data); setNotice(`${payload.data.quoteNumber} revision ${payload.data.revision} saved.`); await load();
    } catch (next) { setError(next instanceof Error ? next.message : 'Quote could not be saved.'); } finally { setBusy(''); }
  }
  async function action(actionName: 'send' | 'approve' | 'convert') {
    if (!selected?.id) { setError('Save the quote before using this action.'); return; }
    setBusy(actionName); setError(''); setNotice('');
    try {
      if (actionName === 'approve') { const response = await fetch(`/api/internal/formal-quotes/${encodeURIComponent(selected.id)}`, { method: 'PATCH', headers: { 'Content-Type': 'application/json' }, body: JSON.stringify({ action: 'approved', status: 'approved', note: 'Approved in quote admin' }) }); const payload = await response.json().catch(() => ({})); if (!response.ok || payload?.ok === false) throw new Error(payload?.error || 'Approval failed.'); setSelected(payload.data); setNotice(`${payload.data.quoteNumber} approved.`); }
      else { const response = await fetch(`/api/internal/formal-quotes/${encodeURIComponent(selected.id)}`, { method: 'PATCH', headers: { 'Content-Type': 'application/json' }, body: JSON.stringify({ action: actionName }) }); const payload = await response.json().catch(() => ({})); if (!response.ok || payload?.ok === false) throw new Error(payload?.error || `${actionName} failed.`); setSelected(payload.data); setNotice(actionName === 'send' ? `${payload.data.quoteNumber} queued for email. ${payload.accessUrl || ''}` : `${payload.data.quoteNumber} converted to order ${payload.order?.orderNumber || ''}. Payment link created.`); if (payload.paymentUrl) window.open(payload.paymentUrl, '_blank', 'noopener,noreferrer'); }
      await load();
    } catch (next) { setError(next instanceof Error ? next.message : 'Quote action failed.'); } finally { setBusy(''); }
  }

  return <div className="space-y-5">
    <PageHeader title="Formal quote workflow" subtitle="Create revisioned multi-line quotations, email secure approval links, convert accepted quotes to orders, and collect payment." actions={<div className="flex gap-2"><Button onClick={startNew}>New quote</Button><Link href="/orders" className="rounded-xl border border-white/10 px-4 py-2 text-sm text-white">Orders</Link></div>} />
    {notice ? <div className="rounded-xl border border-emerald-500/30 bg-emerald-500/10 p-4 text-sm text-emerald-100">{notice}</div> : null}{error ? <div className="rounded-xl border border-rose-500/30 bg-rose-500/10 p-4 text-sm text-rose-100">{error}</div> : null}
    <div className="grid gap-4 md:grid-cols-4"><Metric label="Open" value={String(quotes.filter((quote) => ['requested','draft','sent','viewed'].includes(quote.status)).length)} /><Metric label="Approved" value={String(quotes.filter((quote) => quote.status === 'approved').length)} /><Metric label="Converted" value={String(quotes.filter((quote) => ['converted','paid'].includes(quote.status)).length)} /><Metric label="Quoted value" value={money(quotes.reduce((sum, quote) => sum + quote.totalMinor, 0))} /></div>
    <div className="grid gap-5 xl:grid-cols-[1fr_1.65fr]">
      <Card className="space-y-4"><div className="grid gap-2 md:grid-cols-[1fr_160px]"><Input placeholder="Search quote, customer or email" value={search} onChange={(event) => setSearch(event.target.value)} /><Select options={['all', ...statuses]} value={filter} onChange={(event) => setFilter(event.target.value)} /></div><div className="max-h-[760px] space-y-2 overflow-y-auto">{shown.map((quote) => <button key={quote.id} onClick={() => openQuote(quote.id)} className="w-full rounded-2xl border border-white/10 p-4 text-left transition hover:bg-white/5" style={{ background: selected?.id === quote.id ? 'rgba(24,167,208,.10)' : undefined }}><div className="flex items-start justify-between gap-3"><div><div className="text-xs font-black uppercase tracking-[0.14em] text-cyan-200">{quote.quoteNumber}</div><div className="mt-2 font-semibold text-white">{quote.title}</div><div className="mt-1 text-xs text-textMuted">{quote.customerName} · revision {quote.revision}</div></div><div className="text-right"><div className="font-semibold text-white">{money(quote.totalMinor, quote.currency)}</div><div className="mt-1 text-xs uppercase text-textMuted">{statusLabel(quote.status)}</div></div></div></button>)}{!shown.length ? <p className="rounded-2xl border border-dashed border-white/10 p-6 text-center text-sm text-textMuted">No quotes match this view.</p> : null}</div></Card>
      <Card className="space-y-5">{selected ? <><div className="flex flex-wrap items-start justify-between gap-4"><div><div className="text-xs uppercase tracking-[0.2em] text-textMuted">{selected.quoteNumber}</div><h2 className="mt-2 text-2xl font-semibold text-white">{selected.title}</h2><p className="mt-1 text-sm text-textMuted">Revision {selected.revision || 'new'} · {statusLabel(selected.status)}</p></div><div className="flex flex-wrap gap-2"><Button onClick={save} disabled={busy === 'save'}>{busy === 'save' ? 'Saving…' : 'Save revision'}</Button><Button onClick={() => action('send')} disabled={!selected.id || busy === 'send'}>Send email</Button><Button onClick={() => action('approve')} disabled={!selected.id || busy === 'approve'}>Approve</Button><PrimaryButton onClick={() => action('convert')} disabled={!selected.id || !['approved','converted'].includes(selected.status) || busy === 'convert'}>Convert + payment</PrimaryButton></div></div>
        <div className="grid gap-3 md:grid-cols-3"><Input placeholder="Customer name" value={selected.customerName} onChange={(event) => patchQuote({ customerName: event.target.value })} /><Input placeholder="Customer email" value={selected.customerEmail} onChange={(event) => patchQuote({ customerEmail: event.target.value })} /><Input placeholder="Phone" value={selected.customerPhone} onChange={(event) => patchQuote({ customerPhone: event.target.value })} /><Input placeholder="Company" value={selected.customerCompany} onChange={(event) => patchQuote({ customerCompany: event.target.value })} /><Input placeholder="Quote title" value={selected.title} onChange={(event) => patchQuote({ title: event.target.value })} /><Input placeholder="Store slug" value={selected.storeSlug} onChange={(event) => patchQuote({ storeSlug: event.target.value })} /><Select options={statuses} value={selected.status} onChange={(event) => patchQuote({ status: event.target.value })} /><Input type="date" value={dateInput(selected.expiresAt)} onChange={(event) => patchQuote({ expiresAt: event.target.value ? new Date(`${event.target.value}T23:59:59Z`).toISOString() : '' })} /><Select options={['GBP', 'EUR', 'USD']} value={selected.currency} onChange={(event) => patchQuote({ currency: event.target.value })} /></div>
        <div className="grid gap-3 md:grid-cols-2"><textarea value={selected.customerNotes} onChange={(event) => patchQuote({ customerNotes: event.target.value })} rows={3} placeholder="Customer-visible notes" className="rounded-xl border border-white/10 bg-black/20 p-3 text-sm text-white" /><textarea value={selected.internalNotes} onChange={(event) => patchQuote({ internalNotes: event.target.value })} rows={3} placeholder="Internal notes" className="rounded-xl border border-white/10 bg-black/20 p-3 text-sm text-white" /></div>
        <div className="space-y-3"><div className="flex items-center justify-between"><h3 className="font-semibold text-white">Quote lines</h3><Button onClick={() => addLine()}>Add product line</Button></div>{selected.lines.map((line, index) => { const next = lineTotals(line); return <div key={line.id || index} className="rounded-2xl border border-white/10 p-4"><div className="grid gap-3 md:grid-cols-[1.5fr_100px_130px_100px_auto]"><div><Select options={products.map((product) => ({ value: product.id, label: productName(product) }))} value={line.productId || ''} onChange={(event) => { const product = products.find((item) => item.id === event.target.value); patchLine(index, { ...productLine(product), id: line.id }); }} /><Input className="mt-2" placeholder="Line description" value={line.description || ''} onChange={(event) => patchLine(index, { description: event.target.value })} /></div><Input type="number" min="1" value={String(line.quantity)} onChange={(event) => patchLine(index, { quantity: Math.max(1, Number(event.target.value) || 1) })} /><Input type="number" min="0" value={String(line.unitNetMinor)} onChange={(event) => patchLine(index, { unitNetMinor: Math.max(0, Number(event.target.value) || 0) })} /><Select options={['0', '20']} value={String(line.vatRate)} onChange={(event) => patchLine(index, { vatRate: Number(event.target.value) })} /><div className="flex items-center justify-end gap-3"><div className="text-right"><div className="font-semibold text-white">{money(next.grossMinor, selected.currency)}</div><div className="text-xs text-textMuted">VAT {money(next.vatMinor, selected.currency)}</div></div><Button onClick={() => removeLine(index)} disabled={selected.lines.length <= 1}>Remove</Button></div></div></div>; })}</div>
        <div className="ml-auto w-full max-w-sm space-y-2 rounded-2xl border border-white/10 p-4 text-sm"><div className="flex justify-between"><span className="text-textMuted">Subtotal</span><strong>{money(totals.subtotalMinor, selected.currency)}</strong></div><div className="flex justify-between"><span className="text-textMuted">VAT</span><strong>{money(totals.vatMinor, selected.currency)}</strong></div><div className="flex justify-between border-t border-white/10 pt-3 text-lg"><span>Total</span><strong>{money(totals.totalMinor, selected.currency)}</strong></div></div>
        {selected.revisions?.length ? <div><h3 className="mb-3 font-semibold text-white">Revision history</h3><div className="grid gap-2">{selected.revisions.slice(0, 10).map((revision) => <div key={revision.id} className="flex flex-wrap justify-between gap-3 rounded-xl border border-white/10 px-4 py-3 text-xs"><span>Revision {revision.revision} · {statusLabel(revision.action)} · {revision.actorType}</span><span className="text-textMuted">{revision.createdAt ? new Date(revision.createdAt).toLocaleString('en-GB') : ''} {revision.note ? `· ${revision.note}` : ''}</span></div>)}</div></div> : null}
      </> : <p className="text-sm text-textMuted">Select a quote or create a new one.</p>}</Card>
    </div>
  </div>;
}
function Metric({ label, value }: { label: string; value: string }) { return <Card><p className="text-xs text-textMuted">{label}</p><p className="mt-2 text-2xl font-semibold">{value}</p></Card>; }
