'use client';

import Link from 'next/link';
import { useCallback, useEffect, useMemo, useState } from 'react';
import { DataTable } from '@/components/data-table/data-table';
import { Input } from '@/components/forms/input';
import { Select } from '@/components/forms/select';
import { PageHeader } from '@/components/ui/page-header';
import { Button, PrimaryButton } from '@/components/ui/buttons';
import { Card } from '@/components/ui/card';
import { operationsService } from '@/services/operations.service';
import { ordersService } from '@/services/orders.service';
import type { QuoteRecord } from '@/data/operations';
import type { Order } from '@/modules/orders/types';

const statusOptions: QuoteRecord['status'][] = ['draft','sent','approved','expired'];
const channelOptions = ['US Main Store','B2B Wholesale API','Enterprise Portal','Trade Account','Walk-in Customer'];
type Product={id:string;name:string;slug:string;priceFromMinor?:number;currency?:string;metadataJson?:Record<string,any>};
type Line={id:string;productId:string;productName:string;quantity:number;unitMinor:number;costMinor:number;sellMinor:number;vatRate:string;margin:number};
const tone:Record<QuoteRecord['status'],string>={draft:'border-white/10 bg-white/5 text-text',sent:'border-sky-400/30 bg-sky-400/10 text-sky-200',approved:'border-emerald-400/30 bg-emerald-400/10 text-emerald-200',expired:'border-rose-400/30 bg-rose-400/10 text-rose-200'};
function ts(){return new Date().toISOString()} function stamp(){return ts().slice(0,16).replace('T',' ')} function gbp(p:number){return new Intl.NumberFormat('en-GB',{style:'currency',currency:'GBP'}).format((p||0)/100)} function n(v:any,f=0){const x=Number(v);return Number.isFinite(x)?x:f}
async function loadProducts():Promise<Product[]>{try{const r=await fetch('/api/internal/catalog/products?limit=500',{cache:'no-store'});const j=await r.json().catch(()=>({}));return Array.isArray(j.data?.items)?j.data.items:[]}catch{return[]}}
function cost(product:Product,qty:number){const m=product.metadataJson||{};const pf=Number(product.priceFromMinor||m.pricing?.priceFromMinor||2500);const c=m.manufacturingCost||{};const material=Math.round((Number(m.printMaths?.materialCostMinor||0)||pf*.28)*Math.max(1,qty/100));const machine=Math.round(((Number(c.machineSetupMinutes||10)+Number(c.machineRunMinutes||20))/60)*Number(c.machineHourlyRateMinor||3500));const labour=Math.round(((Number(c.labourSetupMinutes||8)+Number(c.labourRunMinutes||20))/60)*Number(c.labourHourlyRateMinor||1800));const prepress=Math.round((Number(c.prepressMinutes||10)/60)*Number(c.prepressHourlyRateMinor||2500));const finishing=Array.isArray(m.finishing)?m.finishing.reduce((s:any,f:any)=>s+Number(f.setupCostMinor||0)+Number(f.runCostMinor||0)*qty,0):0;const base=material+machine+labour+prepress+finishing+Number(c.packingCostMinor||150)+Number(c.outsourceCostMinor||0);return Math.max(Math.round(base*1.17),Math.round(pf*.45))}
function line(product:Product,qty:number,discount=0):Line{const c=cost(product,qty);const target=Number(product.metadataJson?.manufacturingCost?.targetMarginPercent||product.metadataJson?.pricing?.markupPercent||35);const sell=Math.round((c/Math.max(.01,1-target/100))*(1-discount/100));return{id:`line-${Date.now()}`,productId:product.id,productName:product.name,quantity:qty,unitMinor:Math.round(sell/Math.max(1,qty)),costMinor:c,sellMinor:sell,vatRate:product.metadataJson?.vatRate||product.metadataJson?.pricing?.vatRate||'standard',margin:sell?Math.round(((sell-c)/sell)*1000)/10:0}}
async function readTickets(){try{const r=await fetch('/api/internal/config/production-job-tickets/items',{cache:'no-store'});const j=await r.json().catch(()=>({}));return Array.isArray(j.data?.items)?j.data.items:[]}catch{return[]}}
async function writeTickets(items:any[]){await fetch('/api/internal/config/production-job-tickets/items',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({id:'production-job-tickets',title:'Production Job Tickets',description:'Manufacturing job tickets from quote conversion',items,values:{count:String(items.length),source:'v376-quote-conversion'}})})}
function due(days=3){const d=new Date();d.setDate(d.getDate()+days);return d.toISOString().slice(0,10)}

export function QuotesPage(){
const [quotes,setQuotes]=useState<QuoteRecord[]>([]),[products,setProducts]=useState<Product[]>([]),[search,setSearch]=useState(''),[status,setStatus]=useState<'all'|QuoteRecord['status']>('all'),[selectedId,setSelectedId]=useState<string|null>(null),[notice,setNotice]=useState('');
const [builder,setBuilder]=useState({customer:'',title:'',channel:'US Main Store',status:'draft' as QuoteRecord['status'],productId:'',quantity:'500',discount:'0'}); const [lines,setLines]=useState<Line[]>([]);
const load=useCallback(async()=>{const [q,p]=await Promise.all([operationsService.getQuotes(),loadProducts()]);setQuotes(q);setProducts(p);setSelectedId(x=>x??q[0]?.id??null);setBuilder(b=>({...b,productId:b.productId||p[0]?.id||''}))},[]); useEffect(()=>{load()},[load]);
const rows=useMemo(()=>quotes.filter(q=>{const h=`${q.id} ${q.customer} ${q.title} ${q.channel}`.toLowerCase();return(!search||h.includes(search.toLowerCase()))&&(status==='all'||q.status===status)}),[quotes,search,status]); const selected=rows.find(q=>q.id===selectedId)||rows[0]||null;
const totals=useMemo(()=>{const subtotal=lines.reduce((s,l)=>s+l.sellMinor,0),costs=lines.reduce((s,l)=>s+l.costMinor,0),vat=lines.reduce((s,l)=>s+(l.vatRate==='zero'?0:Math.round(l.sellMinor*.2)),0);const profit=subtotal-costs;return{subtotal,costs,vat,total:subtotal+vat,profit,margin:subtotal?Math.round(profit/subtotal*1000)/10:0,approval:subtotal?profit/subtotal<.25:false}},[lines]);
async function saveQuote(q:QuoteRecord){await operationsService.saveQuote({...q,updatedAt:stamp()});await load()} async function patchQuote(id:string,patch:Partial<QuoteRecord>){const q=quotes.find(x=>x.id===id);if(q)await saveQuote({...q,...patch})}
function addLine(){const p=products.find(x=>x.id===builder.productId)||products[0];if(p)setLines(prev=>[...prev,line(p,Math.max(1,n(builder.quantity,1)),n(builder.discount,0))])}
async function saveBuilder(){const q:QuoteRecord={id:`qt-${Date.now()}`,customer:builder.customer||'Customer',title:builder.title||`${lines[0]?.productName||'Print'} quotation`,channel:builder.channel,status:builder.status,total:Math.round(totals.total/100),updatedAt:stamp()};await saveQuote(q);setNotice(`Quote ${q.id} saved at ${gbp(totals.total)}.`);setLines([])}
async function convertQuote(q:QuoteRecord){const id=`ord-${q.id}`;const order:Order={id,orderNumber:`ORD-${q.id.replace(/\D/g,'').slice(-6)||Date.now().toString().slice(-6)}`,customerName:q.customer,organizationName:q.channel,customerEmail:'',createdAt:ts(),updatedAt:ts(),dueDate:due(3),status:'approved',paymentStatus:'authorized',productionStage:'prepress',total:q.total,currency:'GBP',itemCount:1,storeName:q.channel,shippingMethod:'Quote conversion',shippingAddress:'',billingAddress:'',trackingNumber:'',notes:[`Converted from quote ${q.id} by v376.`],items:[{id:`${id}-item-1`,productId:'quote-custom',productName:q.title,sku:q.id,quantity:1,unitPrice:q.total,totalPrice:q.total,thumbnail:''}],activity:[{id:`act-${Date.now()}`,label:'Quote converted',timestamp:ts(),tone:'success',description:`Quote ${q.id} converted to order and production ticket.`}]};await ordersService.saveOrder(order);const tickets=await readTickets();const ticketId=`job-${id}-item-1`;if(!tickets.some((t:any)=>t.id===ticketId)){await writeTickets([{id:ticketId,orderId:id,orderItemId:`${id}-item-1`,orderNumber:order.orderNumber,customerName:q.customer,productId:'quote-custom',productName:q.title,quantity:1,dueDate:order.dueDate,priority:'normal',status:'artwork-check',artworkStatus:'not-uploaded',machine:'Unassigned',material:'',route:['artwork-check','print','finishing','pack','dispatch'],finishing:[],supplier:'internal',notes:`Auto-created from approved quote ${q.id}.`,warnings:['Quote conversion needs product/material confirmation before production.'],automationSource:'v376-quote-order-production',createdAt:ts(),updatedAt:ts()},...tickets])}await patchQuote(q.id,{status:'approved'});setNotice(`Quote ${q.id} converted to order ${order.orderNumber} and production ticket.`)}
const k=useMemo(()=>({open:rows.filter(q=>q.status==='draft'||q.status==='sent').length,approved:rows.filter(q=>q.status==='approved').reduce((s,q)=>s+q.total,0),sent:rows.filter(q=>q.status==='sent').reduce((s,q)=>s+q.total,0),draft:rows.filter(q=>q.status==='draft').reduce((s,q)=>s+q.total,0)}),[rows]);
return <div className="space-y-5"><PageHeader title="Quote → Order Conversion" subtitle="Build estimates, approve quotes, convert to orders, and create production tickets using the existing order/production pipeline." actions={<div className="flex gap-2"><Link href="/orders" className="rounded-xl border border-white/10 px-4 py-2 text-sm text-white">Orders</Link><Link href="/production" className="rounded-xl border border-white/10 px-4 py-2 text-sm text-white">Production</Link></div>}/>{notice?<div className="rounded-xl border border-emerald-500/30 bg-emerald-500/10 p-4 text-sm text-emerald-100">{notice}</div>:null}
<div className="grid gap-4 md:grid-cols-4"><Metric label="Open quotes" value={String(k.open)}/><Metric label="Draft" value={gbp(k.draft*100)}/><Metric label="Sent" value={gbp(k.sent*100)}/><Metric label="Approved" value={gbp(k.approved*100)}/></div>
<Card className="space-y-4"><p className="text-xs uppercase tracking-[0.24em] text-textMuted">v376 live builder</p><div className="grid gap-3 md:grid-cols-5"><Input placeholder="Customer" value={builder.customer} onChange={e=>setBuilder({...builder,customer:e.target.value})}/><Input placeholder="Title" value={builder.title} onChange={e=>setBuilder({...builder,title:e.target.value})}/><Select options={channelOptions} value={builder.channel} onChange={e=>setBuilder({...builder,channel:e.target.value})}/><Select options={products.map(p=>({value:p.id,label:p.name}))} value={builder.productId} onChange={e=>setBuilder({...builder,productId:e.target.value})}/><Input type="number" placeholder="Qty" value={builder.quantity} onChange={e=>setBuilder({...builder,quantity:e.target.value})}/><Input type="number" placeholder="Discount %" value={builder.discount} onChange={e=>setBuilder({...builder,discount:e.target.value})}/><Select options={statusOptions} value={builder.status} onChange={e=>setBuilder({...builder,status:e.target.value as QuoteRecord['status']})}/><Button onClick={addLine}>Add line</Button><PrimaryButton onClick={saveBuilder} disabled={!lines.length}>Save quote</PrimaryButton></div><div className="overflow-x-auto"><table className="w-full min-w-[760px] text-left text-sm"><thead className="text-xs uppercase tracking-[0.16em] text-textMuted"><tr><th className="py-2 pr-4">Product</th><th>Qty</th><th>Cost</th><th>Sell</th><th>VAT</th><th>Margin</th><th></th></tr></thead><tbody className="divide-y divide-white/8">{lines.map(l=><tr key={l.id} className="text-textMuted"><td className="py-3 pr-4 text-white">{l.productName}</td><td>{l.quantity}</td><td>{gbp(l.costMinor)}</td><td>{gbp(l.sellMinor)}</td><td>{l.vatRate}</td><td className={l.margin<20?'text-rose-200':'text-emerald-200'}>{l.margin}%</td><td><Button onClick={()=>setLines(x=>x.filter(y=>y.id!==l.id))}>Remove</Button></td></tr>)}{!lines.length?<tr><td colSpan={7} className="py-5 text-textMuted">No quote lines yet.</td></tr>:null}</tbody></table></div><div className="grid gap-3 md:grid-cols-5"><Metric label="Subtotal" value={gbp(totals.subtotal)}/><Metric label="VAT" value={gbp(totals.vat)}/><Metric label="Total" value={gbp(totals.total)}/><Metric label="Profit" value={gbp(totals.profit)}/><Metric label="Margin" value={`${totals.margin}%`}/></div>{totals.approval?<div className="rounded-xl border border-amber-500/30 bg-amber-500/10 p-4 text-sm text-amber-100">Approval recommended before sending because margin is below target.</div>:null}</Card>
<div className="grid gap-4 xl:grid-cols-[1.7fr_1fr]"><Card className="space-y-4"><div className="grid gap-2 md:grid-cols-[2fr_1fr]"><Input placeholder="Search quotes..." value={search} onChange={e=>setSearch(e.target.value)}/><Select options={['all',...statusOptions]} value={status} onChange={e=>setStatus(e.target.value as any)}/></div><DataTable columns={[{key:'id',header:'Id',render:r=>r.id},{key:'customer',header:'Customer',render:r=>r.customer},{key:'title',header:'Quote',render:r=>r.title},{key:'status',header:'Status',render:r=><span className={`rounded-full border px-2 py-1 text-xs uppercase ${tone[r.status]}`}>{r.status}</span>},{key:'total',header:'Total',render:r=>gbp(r.total*100)},{key:'actions',header:'Actions',render:r=><div className="flex flex-wrap gap-2"><Button onClick={()=>setSelectedId(r.id)}>View</Button><Button onClick={()=>patchQuote(r.id,{status:'sent'})}>Send</Button><Button onClick={()=>patchQuote(r.id,{status:'approved'})}>Approve</Button><Button onClick={()=>convertQuote(r)} disabled={r.status!=='approved'}>Convert</Button><Button onClick={async()=>{await operationsService.deleteQuote(r.id);await load()}}>Delete</Button></div>}]} rows={rows} rowKey={r=>r.id}/></Card><Card className="space-y-4"><p className="text-xs uppercase tracking-[0.24em] text-textMuted">Conversion spotlight</p><h3 className="text-xl font-semibold text-text">{selected?.title||'No quote selected'}</h3>{selected?<><Box label="Customer" value={selected.customer}/><Box label="Value" value={gbp(selected.total*100)}/><Box label="Status" value={selected.status}/><div className="flex flex-wrap gap-2"><Button onClick={()=>patchQuote(selected.id,{status:'approved'})}>Approve</Button><PrimaryButton onClick={()=>convertQuote(selected)} disabled={selected.status!=='approved'}>Convert to order + production</PrimaryButton></div><p className="rounded-2xl border border-dashed border-white/10 p-4 text-sm text-textMuted">Approved quotes convert into an authorised order and a production ticket. The existing Orders page automation and Production Planner then continue the workflow.</p></>:<p className="text-sm text-textMuted">Pick a quote to convert.</p>}</Card></div></div>}
function Metric({label,value}:{label:string;value:string}){return <Card><p className="text-xs text-textMuted">{label}</p><p className="mt-2 text-2xl font-semibold">{value}</p></Card>}
function Box({label,value}:{label:string;value:string}){return <div className="rounded-2xl border border-white/6 bg-white/[0.03] p-3"><p className="text-xs text-textMuted">{label}</p><p className="mt-1 font-medium">{value}</p></div>}
