import crypto from 'crypto';
import { platformPrisma } from '@/core/db/platform-prisma';
import { requireSuperAdmin } from '@/core/auth/session-guard.service';

type KeyInput = { name: string; type?: string; environment?: string; status?: string; owner?: string; scopes?: string[] | string; expiresAt?: string; notes?: string; tenantId?: string };
type ApiKeyRow = { id: string; tenantId: string | null; name: string; prefix: string; type: string; environment: string; status: string; owner: string | null; scopes: unknown; expiresAt: Date | string | null; lastUsedAt: Date | string | null; createdAt: Date | string; notes: string | null; secretCiphertext: string | null };
const SCOPES = ['catalog:read','catalog:write','orders:read','orders:write','webhooks:manage','seo:read','seo:write'] as const;
function sha(value: string) { return crypto.createHash('sha256').update(value).digest('hex'); }
function keyMaterial() { return crypto.createHash('sha256').update(process.env.API_KEY_ENCRYPTION_SECRET || process.env.NEXTAUTH_SECRET || process.env.BOOTSTRAP_ADMIN_PASSWORD || process.env.DATABASE_URL || 'print-admin-dev-key').digest(); }
function encrypt(value: string) { const iv = crypto.randomBytes(12); const cipher = crypto.createCipheriv('aes-256-gcm', keyMaterial(), iv); const data = Buffer.concat([cipher.update(value, 'utf8'), cipher.final()]); const tag = cipher.getAuthTag(); return `${iv.toString('base64url')}.${tag.toString('base64url')}.${data.toString('base64url')}`; }
function decrypt(value: string | null) { if (!value) return ''; const [ivRaw, tagRaw, dataRaw] = value.split('.'); if (!ivRaw || !tagRaw || !dataRaw) return ''; const decipher = crypto.createDecipheriv('aes-256-gcm', keyMaterial(), Buffer.from(ivRaw, 'base64url')); decipher.setAuthTag(Buffer.from(tagRaw, 'base64url')); return Buffer.concat([decipher.update(Buffer.from(dataRaw, 'base64url')), decipher.final()]).toString('utf8'); }
function parseScopes(value: unknown) { if (Array.isArray(value)) return value.map(String); if (typeof value === 'string') { try { const parsed = JSON.parse(value); if (Array.isArray(parsed)) return parsed.map(String); } catch {} return value.split(',').map((x) => x.trim()).filter(Boolean); } return []; }
function normaliseScopes(value: KeyInput['scopes']) { return parseScopes(value).filter((scope) => SCOPES.includes(scope as any)); }
function publicRow(row: ApiKeyRow) { return { id: row.id, tenantId: row.tenantId || '', name: row.name, type: row.type, environment: row.environment, status: row.status, prefix: row.prefix, scopes: parseScopes(row.scopes), lastUsedAt: row.lastUsedAt ? new Date(row.lastUsedAt).toISOString() : 'Never', expiresAt: row.expiresAt ? new Date(row.expiresAt).toISOString().slice(0, 10) : '', createdAt: row.createdAt ? new Date(row.createdAt).toISOString().slice(0, 10) : '', owner: row.owner || '', notes: row.notes || '' }; }
async function ensureTable() { await platformPrisma.$executeRawUnsafe(`CREATE TABLE IF NOT EXISTS "ApiKey" ("id" TEXT PRIMARY KEY,"tenantId" TEXT,"name" TEXT NOT NULL,"prefix" TEXT NOT NULL UNIQUE,"secretHash" TEXT NOT NULL UNIQUE,"secretCiphertext" TEXT,"type" TEXT NOT NULL DEFAULT 'secret',"environment" TEXT NOT NULL DEFAULT 'production',"status" TEXT NOT NULL DEFAULT 'active',"owner" TEXT,"scopes" JSONB,"expiresAt" TIMESTAMP(3),"lastUsedAt" TIMESTAMP(3),"revokedAt" TIMESTAMP(3),"notes" TEXT,"createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,"updatedAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP);`); await platformPrisma.$executeRawUnsafe('CREATE INDEX IF NOT EXISTS "ApiKey_tenantId_idx" ON "ApiKey"("tenantId")'); await platformPrisma.$executeRawUnsafe('CREATE INDEX IF NOT EXISTS "ApiKey_prefix_idx" ON "ApiKey"("prefix")'); await platformPrisma.$executeRawUnsafe('CREATE INDEX IF NOT EXISTS "ApiKey_status_idx" ON "ApiKey"("status")'); }
async function defaultTenantId(input?: string) { if (input) return input; const rows = await platformPrisma.$queryRawUnsafe<Array<{ id: string }>>('SELECT id FROM "Tenant" ORDER BY "createdAt" ASC LIMIT 1').catch(() => []); return rows[0]?.id || null; }
export async function listPlatformApiKeys(search = '') { await requireSuperAdmin(); await ensureTable(); const rows = await platformPrisma.$queryRawUnsafe<ApiKeyRow[]>('SELECT id,"tenantId",name,prefix,type,environment,status,owner,scopes,"expiresAt","lastUsedAt","createdAt",notes,"secretCiphertext" FROM "ApiKey" WHERE ($1 = \'\' OR lower(name || \' \' || prefix || \' \' || coalesce(owner,\'\')) LIKE lower($2)) ORDER BY "createdAt" DESC LIMIT 200', search.trim(), `%${search.trim()}%`); return { items: rows.map(publicRow), scopes: SCOPES };
}
export async function createPlatformApiKey(input: KeyInput) { await requireSuperAdmin(); await ensureTable(); const environment = input.environment || 'production'; const type = input.type || 'secret'; const prefix = `${type === 'public' ? 'pk' : 'sk'}_${environment === 'production' ? 'live' : 'test'}_${crypto.randomBytes(4).toString('hex')}`; const secret = `${prefix}_${crypto.randomBytes(24).toString('base64url')}`; const tenantId = await defaultTenantId(input.tenantId); const id = `apikey-${crypto.randomUUID()}`; await platformPrisma.$executeRawUnsafe('INSERT INTO "ApiKey" (id,"tenantId",name,prefix,"secretHash","secretCiphertext",type,environment,status,owner,scopes,"expiresAt",notes,"updatedAt") VALUES ($1,$2,$3,$4,$5,$6,$7,$8,$9,$10,$11::jsonb,$12,$13,NOW())', id, tenantId, input.name || 'API Key', prefix, sha(secret), encrypt(secret), type, environment, input.status || 'active', input.owner || '', JSON.stringify(normaliseScopes(input.scopes)), input.expiresAt ? new Date(input.expiresAt) : null, input.notes || ''); const list = await listPlatformApiKeys(''); return { secret, prefix, ...list };
}
export async function updatePlatformApiKey(id: string, input: Partial<KeyInput>) { await requireSuperAdmin(); await ensureTable(); await platformPrisma.$executeRawUnsafe('UPDATE "ApiKey" SET name=COALESCE($2,name), status=COALESCE($3,status), owner=COALESCE($4,owner), scopes=COALESCE($5::jsonb,scopes), "expiresAt"=$6, notes=COALESCE($7,notes), "updatedAt"=NOW() WHERE id=$1', id, input.name || null, input.status || null, input.owner || null, input.scopes ? JSON.stringify(normaliseScopes(input.scopes)) : null, input.expiresAt ? new Date(input.expiresAt) : null, input.notes || null); return listPlatformApiKeys(''); }
export async function revokePlatformApiKey(id: string) { await requireSuperAdmin(); await ensureTable(); await platformPrisma.$executeRawUnsafe('UPDATE "ApiKey" SET status=\'revoked\',"revokedAt"=NOW(),"updatedAt"=NOW() WHERE id=$1', id); return listPlatformApiKeys(''); }
export async function verifyPublicApiKey(request: Request, requiredScope?: string) { await ensureTable(); const key = request.headers.get('x-print-api-key') || request.headers.get('authorization')?.replace(/^Bearer\s+/i, '') || ''; if (!key) throw new Error('API key required.'); const rows = await platformPrisma.$queryRawUnsafe<ApiKeyRow[]>('SELECT id,"tenantId",name,prefix,type,environment,status,owner,scopes,"expiresAt","lastUsedAt","createdAt",notes,"secretCiphertext" FROM "ApiKey" WHERE "secretHash"=$1 LIMIT 1', sha(key)); const row = rows[0]; if (!row || row.status !== 'active') throw new Error('API key is invalid or inactive.'); if (row.expiresAt && new Date(row.expiresAt).getTime() <= Date.now()) throw new Error('API key expired.'); const scopes = parseScopes(row.scopes); if (requiredScope && !scopes.includes(requiredScope)) throw new Error('API key scope denied.'); await platformPrisma.$executeRawUnsafe('UPDATE "ApiKey" SET "lastUsedAt"=NOW(),"updatedAt"=NOW() WHERE id=$1', row.id).catch(() => undefined); return { keyId: row.id, tenantId: row.tenantId || '', scopes, prefix: row.prefix }; }
export async function verifySignedPublicApiRequest(request: Request, requiredScope?: string) { const context = await verifyPublicApiKey(request, requiredScope); const signature = request.headers.get('x-print-signature') || ''; const timestamp = request.headers.get('x-print-timestamp') || ''; if (!signature || !timestamp) throw new Error('Signed request headers missing.'); const age = Math.abs(Date.now() - Number(timestamp)); if (!Number.isFinite(age) || age > 5 * 60 * 1000) throw new Error('Signed request timestamp expired.'); const rows = await platformPrisma.$queryRawUnsafe<ApiKeyRow[]>('SELECT id,"tenantId",name,prefix,type,environment,status,owner,scopes,"expiresAt","lastUsedAt","createdAt",notes,"secretCiphertext" FROM "ApiKey" WHERE id=$1 LIMIT 1', context.keyId); const secret = decrypt(rows[0]?.secretCiphertext || null); if (!secret) throw new Error('Signing secret unavailable.'); const url = new URL(request.url); const base = `${timestamp}.${request.method.toUpperCase()}.${url.pathname}${url.search}`; const expected = crypto.createHmac('sha256', secret).update(base).digest('hex'); if (!crypto.timingSafeEqual(Buffer.from(signature), Buffer.from(expected))) throw new Error('Invalid request signature.'); return context; }
