'use client';
import { useEffect, useState } from 'react';
import { PageHeader } from '@/components/ui/page-header';
import { Button, PrimaryButton } from '@/components/ui/buttons';
import { Input } from '@/components/forms/input';
import { Card } from '@/components/ui/card';
import { BaseModal } from '@/components/modals/base-modal';
import { collectionsService } from '@/services/collections.service';
import { productsService } from '@/services/products.service';
import { categoriesService } from '@/services/categories.service';
import type { CollectionFormValues, Collection } from '@/modules/collections/types';
import type { Product } from '@/modules/products/types';
import type { Category } from '@/modules/categories/types';
const emptyForm: CollectionFormValues = { title: '', productIds: [], categoryIds: [] };
export function CollectionsPage(){
 const [items,setItems]=useState<Collection[]>([]); const [products,setProducts]=useState<Product[]>([]); const [categories,setCategories]=useState<Category[]>([]); const [search,setSearch]=useState(''); const [open,setOpen]=useState(false); const [editing,setEditing]=useState<Collection|null>(null); const [form,setForm]=useState<CollectionFormValues>(emptyForm);
 const load = async()=>{ const [collectionsResponse, productsResponse, categoriesResponse] = await Promise.all([collectionsService.listCollections(search), productsService.listProducts({ perPage: 200 }), categoriesService.listCategories()]); setItems(collectionsResponse.data.items); setProducts(productsResponse.data.items); setCategories(categoriesResponse.data.items); };
 useEffect(()=>{ void load(); }, [search]);
 const startCreate=()=>{ setEditing(null); setForm(emptyForm); setOpen(true); };
 const startEdit=(item:Collection)=>{ setEditing(item); setForm({ title:item.title, productIds:item.productIds, categoryIds:item.categoryIds }); setOpen(true); };
 return <div><PageHeader title="Collections" subtitle="Curate groups of products and categories into storefront collections." actions={<PrimaryButton onClick={startCreate}>+ Add Collection</PrimaryButton>} /><div className="mb-4 flex gap-2"><Input placeholder="Search collections..." value={search} onChange={(e)=>setSearch(e.target.value)} /></div><div className="grid gap-4">{items.map((item)=><Card key={item.id}><div className="flex items-start justify-between gap-4"><div><h3 className="font-semibold">{item.title}</h3><p className="text-sm text-textMuted">Created {item.createdOn}</p><p className="mt-2 text-sm text-textMuted">{item.products.length} products · {item.categories.length} categories</p></div><div className="flex gap-2"><Button onClick={()=>startEdit(item)}>View/Edit</Button><Button className="text-red-300" onClick={async()=>{await collectionsService.deleteCollection(item.id); await load();}}>Delete</Button></div></div></Card>)}</div><BaseModal open={open} onClose={()=>setOpen(false)} title={editing?'Edit Collection':'Add Collection'}><div className="space-y-4"><Input placeholder="Collection name" value={form.title} onChange={(e)=>setForm((prev)=>({...prev,title:e.target.value}))} /><div className="grid gap-4 lg:grid-cols-2"><Card><div className="mb-3 flex items-center justify-between"><h3 className="font-semibold">Products</h3></div><div className="space-y-2 max-h-80 overflow-auto">{products.map((product)=><label key={product.id} className="flex items-center gap-2 text-sm"><input type="checkbox" checked={form.productIds.includes(product.id)} onChange={(e)=>setForm((prev)=>({...prev, productIds: e.target.checked ? [...prev.productIds, product.id] : prev.productIds.filter((id)=>id!==product.id)}))} /> {product.name}</label>)}</div></Card><Card><div className="mb-3 flex items-center justify-between"><h3 className="font-semibold">Categories</h3></div><div className="space-y-2 max-h-80 overflow-auto">{categories.map((category)=><label key={category.id} className="flex items-center gap-2 text-sm"><input type="checkbox" checked={form.categoryIds.includes(category.id)} onChange={(e)=>setForm((prev)=>({...prev, categoryIds: e.target.checked ? [...prev.categoryIds, category.id] : prev.categoryIds.filter((id)=>id!==category.id)}))} /> {category.name}</label>)}</div></Card></div><div className="flex justify-end gap-2"><Button onClick={()=>setOpen(false)}>Cancel</Button><PrimaryButton onClick={async()=>{ if(!form.title.trim()) return; if(editing) await collectionsService.updateCollection(editing.id, form); else await collectionsService.createCollection(form); setOpen(false); await load(); }}>{editing?'Save':'Create Collection'}</PrimaryButton></div></div></BaseModal></div>
}
