import { adminNavigationRegistry } from '@/config/admin-navigation';

export type ButtonAuditSeverity = 'pass' | 'warning' | 'error' | 'info';
export type ButtonAuditFinding = { id: string; file: string; severity: ButtonAuditSeverity; label: string; detail: string; action?: string };
type RouteCheck = { file: string; route: string; expectedActions: string[]; note?: string };
const DEEP_CHECKS: Record<string, Omit<RouteCheck, 'route'>> = {
  '/products': { file: 'src/modules/products/pages/products-list-page.tsx', expectedActions: ['Add Product', 'Import CSV Pricing', 'Export', 'Edit', 'Preview', 'Clone', 'Delete'], note: 'Tenant catalog list should use internal catalog API/database only.' },
  '/categories': { file: 'app/categories/page.tsx', expectedActions: ['Add Category', 'Edit', 'Delete'], note: 'Tenant category management must persist to database.' },
  '/orders': { file: 'app/orders/page.tsx', expectedActions: ['Open order', 'Update status'], note: 'Tenant orders should read from order database.' },
  '/quotes': { file: 'app/quotes/page.tsx', expectedActions: ['Create Quote', 'Save', 'Delete'], note: 'Quotes now use tenant operations service without mock fallback.' },
  '/production': { file: 'app/production/page.tsx', expectedActions: ['Create job', 'Edit', 'Delete'], note: 'Production records should use internal production-board/database path.' },
  '/artwork-proofing': { file: 'app/artwork-proofing/page.tsx', expectedActions: ['Open proof', 'Save', 'Delete'], note: 'Artwork proof records now use tenant operations service without mock fallback.' },
  '/reports': { file: 'src/modules/reports/pages/reports-page.tsx', expectedActions: ['Refresh', 'Export CSV', 'Schedule Report'], note: 'Tenant Reports use live orders/products/activity, not seed arrays.' },
  '/activity-log': { file: 'src/modules/activity-log/pages/activity-log-page.tsx', expectedActions: ['Refresh'], note: 'Activity Log uses live records and clean empty state.' },
  '/settings': { file: 'src/modules/operations/pages/settings-page.tsx', expectedActions: ['Edit', 'Save', 'Cancel'], note: 'General Settings save through tenant operations service.' },
  '/payment-accounts': { file: 'src/modules/settings/pages/payment-accounts-page.tsx', expectedActions: ['Refresh', 'Save account'], note: 'Build 78 separates tenant customer payments from platform subscription billing and shows missing env.' },
  '/support': { file: 'app/support/page.tsx', expectedActions: ['Create Support Task'], note: 'DB-backed through internal config API.' },
  '/knowledge-base': { file: 'app/knowledge-base/page.tsx', expectedActions: ['Add Article'], note: 'DB-backed through internal config API.' },
  '/error-log': { file: 'app/error-log/page.tsx', expectedActions: ['Create Incident'], note: 'No dummy incidents preloaded.' },
  '/organizations': { file: 'src/modules/settings/pages/organizations-page.tsx', expectedActions: ['Add Activation Group', 'Edit', 'Delete'], note: 'DB-backed through platform records API.' },
  '/merchant-accounts': { file: 'src/modules/settings/pages/merchant-accounts-page.tsx', expectedActions: ['Add Merchant Account', 'Edit', 'Delete'], note: 'DB-backed through platform records API.' },
  '/api-access': { file: 'src/modules/settings/pages/api-access-page.tsx', expectedActions: ['Add Access Profile', 'Edit', 'Delete'], note: 'DB-backed through platform records API.' },
  '/api-keys': { file: 'src/modules/platform/credentials-page.tsx', expectedActions: ['Create credential', 'Refresh'], note: 'DB-backed credential page.' },
  '/licensing-center': { file: 'src/modules/plugin/pages/licensing-center-live-page.tsx', expectedActions: ['Add licence', 'Edit', 'Delete'], note: 'Cleaned live licensing page.' },
  '/business-defaults': { file: 'src/modules/platform/default-store-bootstrap-page.tsx', expectedActions: ['Create / refresh default stores'], note: 'Build 76 default hosted store bootstrap for existing tenants.' },
  '/button-audit': { file: 'src/modules/launch/button-audit-page.tsx', expectedActions: ['Refresh'], note: 'Route/click audit registry.' },
  '/email-order-notification-qa': { file: 'src/modules/launch/email-order-notification-qa-page.tsx', expectedActions: ['Dry run', 'Queue test notifications'] },
  '/payment-checkout-qa': { file: 'src/modules/launch/payment-checkout-qa-page.tsx', expectedActions: ['Dry run', 'Create payment test order'] },
  '/storefront-order-test': { file: 'src/modules/launch/storefront-order-test-page.tsx', expectedActions: ['Dry run'] },
};
const TENANT_ROLE_NAMES = new Set(['admin', 'tenant_admin', 'owner']);
function row(id: string, file: string, severity: ButtonAuditSeverity, label: string, detail: string, action = ''): ButtonAuditFinding { return { id, file, severity, label, detail, action }; }
function routeToFile(route: string) { const clean = route.replace(/^\//, '') || 'page'; return `app/${clean}/page.tsx`; }
function isTenantRoute(item: { href?: string; roles?: string[]; hidden?: boolean }) { return Boolean(item.href && !item.hidden && item.roles?.some((role) => TENANT_ROLE_NAMES.has(role))); }
function buildRouteChecks(): RouteCheck[] { const checks: RouteCheck[] = []; const seen = new Set<string>(); for (const item of adminNavigationRegistry) { if (!isTenantRoute(item)) continue; const route = item.href; if (!route || seen.has(route)) continue; seen.add(route); const deep = DEEP_CHECKS[route]; checks.push({ route, file: deep?.file || routeToFile(route), expectedActions: deep?.expectedActions || ['Open page'], note: deep?.note || `Tenant sidebar route from ${item.groupLabel || item.parentLabel || 'main'}: ${item.label}.` }); } for (const [route, deep] of Object.entries(DEEP_CHECKS)) if (!seen.has(route)) checks.push({ route, ...deep }); return checks.sort((a, b) => a.route.localeCompare(b.route)); }
export async function buildButtonAudit() { const findings: ButtonAuditFinding[] = []; const routeChecks = buildRouteChecks(); for (const module of routeChecks) { findings.push(row(`known-${module.route}`, module.file, 'pass', 'Tenant sidebar route registered', `${module.route} is included in the tenant/admin action audit registry.`)); findings.push(row(`actions-${module.route}`, module.file, 'info', 'Expected visible actions', `Expected actions: ${module.expectedActions.join(', ')}.`, 'Open the route and confirm each action after deploy.')); if (module.note) findings.push(row(`note-${module.route}`, module.file, 'info', 'Production wiring note', module.note)); } findings.push(row('tenant-sidebar-full-coverage', 'src/config/admin-navigation.ts', 'pass', 'Full tenant sidebar imported', 'Button Audit now builds from adminNavigationRegistry instead of a short hand-written list.')); findings.push(row('deployment-safe-mode', 'src/core/launch/button-audit.service.ts', 'warning', 'Lightweight audit mode', 'This page uses registry coverage and manual action expectations to keep the Vercel function small.', 'Use the listed routes for manual click testing.')); const summary = findings.reduce((acc, item) => { acc.findings += 1; acc[item.severity] += 1; return acc; }, { findings: 0, pass: 0, warning: 0, error: 0, info: 0 } as Record<ButtonAuditSeverity | 'findings', number>); const score = Math.max(0, Math.min(100, 100 - summary.error * 8 - summary.warning * 3)); const ready = summary.error === 0; const nextActions = findings.filter((item) => item.severity === 'error' || item.severity === 'warning').slice(0, 30).map((item) => ({ label: item.label, detail: `${item.file}: ${item.detail}`, action: item.action, severity: item.severity })); return { ready, score, generatedAt: new Date().toISOString(), summary: { ...summary, filesScanned: routeChecks.length }, findings, nextActions }; }
