[phases.setup]
nixPkgs = ["nodejs_20", "npm-10_x"]

[phases.install]
cmds = ["npm install --include=dev --no-audit --no-fund"]
cacheDirectories = ["/root/.npm"]
paths = ["/app/node_modules/.bin"]

[phases.build]
cmds = ["NEXT_TELEMETRY_DISABLED=1 npm run build"]
cacheDirectories = [".next/cache", "node_modules/.cache"]

[start]
cmd = "NEXT_TELEMETRY_DISABLED=1 npm run start"
