import { platformPrisma } from '@/core/db/platform-prisma';
import { requireTenantSession } from '@/core/auth/session-guard.service';

const RESOURCE = 'payment-accounts';
function envReady(name: string) { return Boolean(process.env[name]); }
function envState() { return [
  { name: 'STRIPE_SECRET_KEY', ready: envReady('STRIPE_SECRET_KEY'), purpose: 'Your SaaS platform subscription billing.' },
  { name: 'STRIPE_WEBHOOK_SECRET', ready: envReady('STRIPE_WEBHOOK_SECRET'), purpose: 'Stripe webhook verification for subscriptions.' },
  { name: 'NEXT_PUBLIC_APP_URL', ready: envReady('NEXT_PUBLIC_APP_URL'), purpose: 'Return/cancel URLs for billing flows.' },
  { name: 'STRIPE_PLATFORM_PRICE_MONTHLY', ready: envReady('STRIPE_PLATFORM_PRICE_MONTHLY'), purpose: 'Monthly SaaS subscription price id.' },
  { name: 'STRIPE_PLATFORM_PRICE_YEARLY', ready: envReady('STRIPE_PLATFORM_PRICE_YEARLY'), purpose: 'Yearly SaaS subscription price id.' },
  { name: 'STRIPE_CONNECT_CLIENT_ID', ready: envReady('STRIPE_CONNECT_CLIENT_ID'), purpose: 'Tenant Connect onboarding for customer order payments.' },
]; }
async function ensureTable() { await platformPrisma.$executeRawUnsafe(`CREATE TABLE IF NOT EXISTS "CoreCatalogRecord" ("id" TEXT PRIMARY KEY,"tenantId" TEXT NOT NULL,"resource" TEXT NOT NULL,"slug" TEXT NOT NULL,"name" TEXT NOT NULL,"description" TEXT NOT NULL DEFAULT '',"metadataJson" JSONB,"createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,"updatedAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP);`); await platformPrisma.$executeRawUnsafe('CREATE UNIQUE INDEX IF NOT EXISTS "CoreCatalogRecord_tenant_resource_slug_uq" ON "CoreCatalogRecord"("tenantId","resource","slug")'); }
function mapAccount(row: any) { const meta = row?.metadataJson || {}; return { id: String(row?.id || 'tenant-payment-account'), name: String(row?.name || meta.name || 'Tenant customer payments'), slug: String(row?.slug || meta.slug || 'tenant-customer-payments'), mode: String(meta.mode || 'tenant_customer_payments'), provider: String(meta.provider || 'stripe_connect'), status: String(meta.status || 'not_connected'), connectedAccountId: String(meta.connectedAccountId || ''), chargesUse: String(meta.chargesUse || 'customer_orders'), updatedAt: row?.updatedAt instanceof Date ? row.updatedAt.toISOString() : String(row?.updatedAt || '') }; }
export async function getPaymentAccountsReadiness() { const session = await requireTenantSession(); await ensureTable(); const tenantId = String(session.tenantId || 'holo-print'); const rows = await platformPrisma.$queryRawUnsafe<any[]>('SELECT id,slug,name,description,"metadataJson","updatedAt" FROM "CoreCatalogRecord" WHERE "tenantId"=$1 AND resource=$2 ORDER BY "updatedAt" DESC', tenantId, RESOURCE); const accounts = rows.map(mapAccount); return { tenantId, env: envState(), platformBillingReady: envState().filter((item) => item.name !== 'STRIPE_CONNECT_CLIENT_ID').every((item) => item.ready), tenantConnectReady: envReady('STRIPE_CONNECT_CLIENT_ID') && envReady('STRIPE_SECRET_KEY'), accounts, split: { platformSubscriptionPayments: 'Use platform Stripe account only.', tenantCustomerOrderPayments: 'Use tenant connected Stripe account only.', currentProcessing: 'disabled_until_env_and_connect_complete' } }; }
export async function saveTenantPaymentAccount(input: Record<string, unknown>) { const session = await requireTenantSession(); await ensureTable(); const tenantId = String(session.tenantId || 'holo-print'); const id = String(input.id || 'tenant-payment-account'); const meta = { id, slug: 'tenant-customer-payments', name: String(input.name || 'Tenant customer payments'), mode: 'tenant_customer_payments', provider: 'stripe_connect', status: String(input.status || 'not_connected'), connectedAccountId: String(input.connectedAccountId || ''), chargesUse: 'customer_orders', updatedBy: session.email || session.id }; await platformPrisma.$executeRawUnsafe('INSERT INTO "CoreCatalogRecord" (id,"tenantId",resource,slug,name,description,"metadataJson","updatedAt") VALUES ($1,$2,$3,$4,$5,$6,$7::jsonb,NOW()) ON CONFLICT ("tenantId",resource,slug) DO UPDATE SET name=EXCLUDED.name,description=EXCLUDED.description,"metadataJson"=EXCLUDED."metadataJson","updatedAt"=NOW()', id, tenantId, RESOURCE, meta.slug, meta.name, 'Tenant customer order payment account configuration.', JSON.stringify(meta)); return mapAccount({ id, slug: meta.slug, name: meta.name, metadataJson: meta, updatedAt: new Date() }); }
