import crypto from 'crypto';
import { platformPrisma } from '@/core/db/platform-prisma';
import { requireTenantSession } from '@/core/auth/session-guard.service';
import { appBaseUrl, getStripeClient, missingStripeEnv, stripeConfiguredForConnect, stripeConfiguredForPlatform, stripeEnv } from './stripe-client.service';

const CONNECT_STATE_RESOURCE = 'stripe-connect-state';
const PAYMENT_RESOURCE = 'payment-accounts';
async function ensureRecordTable() { await platformPrisma.$executeRawUnsafe(`CREATE TABLE IF NOT EXISTS "CoreCatalogRecord" ("id" TEXT PRIMARY KEY,"tenantId" TEXT NOT NULL,"resource" TEXT NOT NULL,"slug" TEXT NOT NULL,"name" TEXT NOT NULL,"description" TEXT NOT NULL DEFAULT '',"metadataJson" JSONB,"createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,"updatedAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP);`); await platformPrisma.$executeRawUnsafe('CREATE UNIQUE INDEX IF NOT EXISTS "CoreCatalogRecord_tenant_resource_slug_uq" ON "CoreCatalogRecord"("tenantId","resource","slug")'); }
async function saveConnectState(tenantId: string, state: string, email?: string) { await ensureRecordTable(); const metadata = { state, tenantId, email: email || '', expiresAt: new Date(Date.now() + 20 * 60 * 1000).toISOString() }; await platformPrisma.$executeRawUnsafe('INSERT INTO "CoreCatalogRecord" (id,"tenantId",resource,slug,name,description,"metadataJson","updatedAt") VALUES ($1,$2,$3,$4,$5,$6,$7::jsonb,NOW()) ON CONFLICT ("tenantId",resource,slug) DO UPDATE SET "metadataJson"=EXCLUDED."metadataJson","updatedAt"=NOW()', `stripe-state-${state}`, tenantId, CONNECT_STATE_RESOURCE, state, 'Stripe Connect state', 'Temporary Stripe Connect OAuth state.', JSON.stringify(metadata)); return metadata; }
async function loadConnectState(state: string) { await ensureRecordTable(); const rows = await platformPrisma.$queryRawUnsafe<Array<{ tenantId: string; metadataJson: any }>>('SELECT "tenantId","metadataJson" FROM "CoreCatalogRecord" WHERE resource=$1 AND slug=$2 LIMIT 1', CONNECT_STATE_RESOURCE, state); const row = rows[0]; if (!row?.metadataJson) throw new Error('Stripe Connect state was not found. Start again from Payment Accounts.'); if (new Date(row.metadataJson.expiresAt).getTime() < Date.now()) throw new Error('Stripe Connect state expired. Start again from Payment Accounts.'); return { tenantId: row.tenantId, metadata: row.metadataJson }; }
async function saveConnectedAccountForTenant(tenantId: string, accountId: string) { await ensureRecordTable(); const metadata = { id: 'tenant-payment-account', slug: 'tenant-customer-payments', name: 'Tenant customer payments', mode: 'tenant_customer_payments', provider: 'stripe_connect', status: 'connected', connectedAccountId: accountId, chargesUse: 'customer_orders' }; await platformPrisma.$executeRawUnsafe('INSERT INTO "CoreCatalogRecord" (id,"tenantId",resource,slug,name,description,"metadataJson","updatedAt") VALUES ($1,$2,$3,$4,$5,$6,$7::jsonb,NOW()) ON CONFLICT ("tenantId",resource,slug) DO UPDATE SET name=EXCLUDED.name,description=EXCLUDED.description,"metadataJson"=EXCLUDED."metadataJson","updatedAt"=NOW()', `payment-${tenantId}`, tenantId, PAYMENT_RESOURCE, metadata.slug, metadata.name, 'Tenant customer order payment account configuration.', JSON.stringify(metadata)); return metadata; }
export async function createStripeConnectStartUrl() { const session = await requireTenantSession(); const miss = stripeConfiguredForConnect(); if (miss.length) return { ready: false, missing: miss, url: '', message: `Missing env: ${miss.join(', ')}` }; const state = crypto.randomBytes(24).toString('hex'); await saveConnectState(String(session.tenantId), state, session.email); const redirectUri = `${appBaseUrl()}/api/internal/payment-accounts/provider-return`; const url = new URL('https://connect.stripe.com/oauth/authorize'); url.searchParams.set('response_type', 'code'); url.searchParams.set('client_id', stripeEnv('STRIPE_CONNECT_CLIENT_ID')); url.searchParams.set('scope', 'read_write'); url.searchParams.set('redirect_uri', redirectUri); url.searchParams.set('state', state); return { ready: true, missing: [], url: url.toString(), message: 'Open this URL to connect the tenant Stripe account.' }; }
export async function completeStripeConnect(code: string, state: string) { if (!code || !state) throw new Error('Stripe Connect callback is missing code or state.'); const saved = await loadConnectState(state); const token = await getStripeClient().oauth.token({ grant_type: 'authorization_code', code }); const accountId = String(token.stripe_user_id || ''); if (!accountId) throw new Error('Stripe did not return a connected account id.'); const account = await saveConnectedAccountForTenant(saved.tenantId, accountId); return { tenantId: saved.tenantId, connectedAccountId: accountId, account }; }
export async function createPlatformSubscriptionCheckout(plan: 'monthly' | 'yearly') { const session = await requireTenantSession(); const priceEnv = plan === 'yearly' ? 'STRIPE_PLATFORM_PRICE_YEARLY' : 'STRIPE_PLATFORM_PRICE_MONTHLY'; const miss = stripeConfiguredForPlatform(plan); if (miss.length) return { ready: false, missing: miss, url: '', message: `Missing env: ${miss.join(', ')}` }; const stripe = getStripeClient(); const checkout = await stripe.checkout.sessions.create({ mode: 'subscription', success_url: `${appBaseUrl()}/payment-accounts?billing=success`, cancel_url: `${appBaseUrl()}/payment-accounts?billing=cancelled`, line_items: [{ price: stripeEnv(priceEnv), quantity: 1 }], client_reference_id: String(session.tenantId), customer_email: session.email, metadata: { tenantId: String(session.tenantId), plan } }); return { ready: true, missing: [], url: checkout.url || '', id: checkout.id, message: 'Open this URL to start platform subscription checkout.' }; }
export async function verifyStripeWebhookSignature(rawBody: string, signature: string | null) { const miss = missingStripeEnv(['STRIPE_SECRET_KEY', 'STRIPE_WEBHOOK_SECRET']); if (miss.length) throw new Error(`Missing env: ${miss.join(', ')}`); if (!signature) throw new Error('Stripe signature header missing.'); return getStripeClient().webhooks.constructEvent(rawBody, signature, stripeEnv('STRIPE_WEBHOOK_SECRET')); }
