import crypto from 'crypto';
import { platformPrisma } from '@/core/db/platform-prisma';
import { requireTenantSession } from '@/core/auth/session-guard.service';
import { saveTenantPaymentAccount } from './payment-accounts.service';

const CONNECT_STATE_RESOURCE = 'stripe-connect-state';
function appUrl() { return (process.env.NEXT_PUBLIC_APP_URL || process.env.ADMIN_URL || process.env.NEXT_PUBLIC_ADMIN_URL || 'http://localhost:3000').replace(/\/$/, ''); }
function missing(names: string[]) { return names.filter((name) => !process.env[name]); }
async function ensureRecordTable() { await platformPrisma.$executeRawUnsafe(`CREATE TABLE IF NOT EXISTS "CoreCatalogRecord" ("id" TEXT PRIMARY KEY,"tenantId" TEXT NOT NULL,"resource" TEXT NOT NULL,"slug" TEXT NOT NULL,"name" TEXT NOT NULL,"description" TEXT NOT NULL DEFAULT '',"metadataJson" JSONB,"createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,"updatedAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP);`); await platformPrisma.$executeRawUnsafe('CREATE UNIQUE INDEX IF NOT EXISTS "CoreCatalogRecord_tenant_resource_slug_uq" ON "CoreCatalogRecord"("tenantId","resource","slug")'); }
async function saveConnectState(tenantId: string, state: string, email?: string) { await ensureRecordTable(); const metadata = { state, tenantId, email: email || '', expiresAt: new Date(Date.now() + 20 * 60 * 1000).toISOString() }; await platformPrisma.$executeRawUnsafe('INSERT INTO "CoreCatalogRecord" (id,"tenantId",resource,slug,name,description,"metadataJson","updatedAt") VALUES ($1,$2,$3,$4,$5,$6,$7::jsonb,NOW()) ON CONFLICT ("tenantId",resource,slug) DO UPDATE SET "metadataJson"=EXCLUDED."metadataJson","updatedAt"=NOW()', `stripe-state-${state}`, tenantId, CONNECT_STATE_RESOURCE, state, 'Stripe Connect state', 'Temporary Stripe Connect OAuth state.', JSON.stringify(metadata)); return metadata; }
async function loadConnectState(state: string) { await ensureRecordTable(); const rows = await platformPrisma.$queryRawUnsafe<Array<{ tenantId: string; metadataJson: any }>>('SELECT "tenantId","metadataJson" FROM "CoreCatalogRecord" WHERE resource=$1 AND slug=$2 LIMIT 1', CONNECT_STATE_RESOURCE, state); const row = rows[0]; if (!row?.metadataJson) throw new Error('Stripe Connect state was not found. Start again from Payment Accounts.'); if (new Date(row.metadataJson.expiresAt).getTime() < Date.now()) throw new Error('Stripe Connect state expired. Start again from Payment Accounts.'); return { tenantId: row.tenantId, metadata: row.metadataJson };
}
async function stripeForm(path: string, body: Record<string, string>) { const secret = process.env.STRIPE_SECRET_KEY; if (!secret) throw new Error('STRIPE_SECRET_KEY is missing.'); const response = await fetch(`https://api.stripe.com${path}`, { method: 'POST', headers: { Authorization: `Bearer ${secret}`, 'Content-Type': 'application/x-www-form-urlencoded' }, body: new URLSearchParams(body).toString(), cache: 'no-store' }); const payload = await response.json().catch(() => ({})); if (!response.ok) throw new Error(payload?.error?.message || `Stripe request failed with ${response.status}`); return payload; }
export async function createStripeConnectStartUrl() { const session = await requireTenantSession(); const miss = missing(['STRIPE_CONNECT_CLIENT_ID', 'NEXT_PUBLIC_APP_URL']); if (miss.length) return { ready: false, missing: miss, url: '', message: `Missing env: ${miss.join(', ')}` }; const state = crypto.randomBytes(24).toString('hex'); await saveConnectState(String(session.tenantId), state, session.email); const redirectUri = `${appUrl()}/api/internal/auth/stripe-connect/callback`; const url = new URL('https://connect.stripe.com/oauth/authorize'); url.searchParams.set('response_type', 'code'); url.searchParams.set('client_id', String(process.env.STRIPE_CONNECT_CLIENT_ID)); url.searchParams.set('scope', 'read_write'); url.searchParams.set('redirect_uri', redirectUri); url.searchParams.set('state', state); return { ready: true, missing: [], url: url.toString(), message: 'Open this URL to connect the tenant Stripe account.' }; }
export async function completeStripeConnect(code: string, state: string) { if (!code || !state) throw new Error('Stripe Connect callback is missing code or state.'); const saved = await loadConnectState(state); const payload = await stripeForm('/v1/oauth/token', { grant_type: 'authorization_code', code }); const accountId = String(payload.stripe_user_id || ''); if (!accountId) throw new Error('Stripe did not return a connected account id.'); const original = await requireTenantSession().catch(() => null); const account = await saveTenantPaymentAccount({ connectedAccountId: accountId, status: 'connected', name: 'Tenant customer payments' }); return { tenantId: saved.tenantId, connectedAccountId: accountId, account, originalSessionTenantId: original?.tenantId || null }; }
export async function createPlatformSubscriptionCheckout(plan: 'monthly' | 'yearly') { const session = await requireTenantSession(); const priceEnv = plan === 'yearly' ? 'STRIPE_PLATFORM_PRICE_YEARLY' : 'STRIPE_PLATFORM_PRICE_MONTHLY'; const miss = missing(['STRIPE_SECRET_KEY', 'NEXT_PUBLIC_APP_URL', priceEnv]); if (miss.length) return { ready: false, missing: miss, url: '', message: `Missing env: ${miss.join(', ')}` }; const successUrl = `${appUrl()}/payment-accounts?billing=success`; const cancelUrl = `${appUrl()}/payment-accounts?billing=cancelled`; const payload = await stripeForm('/v1/checkout/sessions', { mode: 'subscription', success_url: successUrl, cancel_url: cancelUrl, 'line_items[0][price]': String(process.env[priceEnv]), 'line_items[0][quantity]': '1', client_reference_id: String(session.tenantId), customer_email: session.email }); return { ready: true, missing: [], url: String(payload.url || ''), id: String(payload.id || ''), message: 'Open this URL to start platform subscription checkout.' }; }
