import { ok } from '@/services/api/responses';
import type { ApiResponse } from '@/services/api/types';
import { http } from '@/services/api/http';
import type { Category, CategoryFormValues, CategoryTag } from '@/modules/categories/types';

type Envelope<T> = { success: boolean; data: T };
const mapCategory = (raw: Record<string, any>): Category => ({ id: String(raw.id), name: String(raw.name ?? ''), description: String(raw.description ?? ''), parentId: raw.parentId ? String(raw.parentId) : null, pricingId: String(raw.pricingId ?? ''), attributeSetId: String(raw.attributeSetId ?? ''), published: Boolean(raw.published), thumbnail: String(raw.thumbnail ?? 'https://placehold.co/96x96/111827/ffffff?text=CT'), friendlyUrl: String(raw.friendlyUrl ?? ''), productCount: Number(raw.productCount ?? 0), sortOrder: Number(raw.sortOrder ?? 0), accuZipConfig: String(raw.accuZipConfig ?? ''), useAlternateMaster: Boolean(raw.useAlternateMaster), tags: Array.isArray(raw.tags) ? raw.tags.map((tag: any) => ({ id: String(tag.id), label: String(tag.label) })) : [], canBrowse: Boolean(raw.canBrowse), canUpload: Boolean(raw.canUpload), canUploadLater: Boolean(raw.canUploadLater), canCreate: Boolean(raw.canCreate), canCustom: Boolean(raw.canCustom) });
export const categoriesService = {
  listCategories: async (): Promise<ApiResponse<{ items: Category[] }>> => { const response = await http.get<Envelope<{ items: Record<string, any>[] }>>('/categories'); return ok({ items: (response.data.items ?? []).map(mapCategory) }); },
  createCategory: async (values: CategoryFormValues): Promise<ApiResponse<Category>> => { const response = await http.post<Envelope<Record<string, any>>>('/categories', { ...values, parentId: values.parentId || null, tagIds: values.tagIds }); return ok(mapCategory(response.data)); },
  updateCategory: async (id: string, values: CategoryFormValues): Promise<ApiResponse<Category>> => { const response = await http.patch<Envelope<Record<string, any>>>(`/categories/${id}`, { ...values, parentId: values.parentId || null, tagIds: values.tagIds }); return ok(mapCategory(response.data)); },
  deleteCategory: async (id: string): Promise<ApiResponse<{ success: boolean }>> => { const response = await http.delete<Envelope<{ success: boolean }>>(`/categories/${id}`); return ok(response.data); },
  togglePublished: async (id: string, published: boolean): Promise<ApiResponse<Category>> => { const response = await http.patch<Envelope<Record<string, any>>>(`/categories/${id}`, { published }); return ok(mapCategory(response.data)); },
  moveCategory: async (id: string, direction: 'up' | 'down'): Promise<ApiResponse<{ items: Category[] }>> => { const response = await http.post<Envelope<{ items: Record<string, any>[] }>>(`/categories/${id}/move`, { direction }); return ok({ items: (response.data.items ?? []).map(mapCategory) }); },
  listCategoryTags: async (): Promise<ApiResponse<{ items: CategoryTag[] }>> => { const response = await http.get<Envelope<{ items: CategoryTag[] }>>('/categories/tags/list'); return ok({ items: response.data.items ?? [] }); },
  saveCategoryTags: async (labels: string[]): Promise<ApiResponse<{ items: CategoryTag[] }>> => { const response = await http.put<Envelope<{ items: CategoryTag[] }>>('/categories/tags/list', { labels }); return ok({ items: response.data.items ?? [] }); },
  listPricingOptions: async (): Promise<ApiResponse<{ items: Array<{ id: string; name: string }> }>> => ok({ items: [{ id: 'price-catalog', name: 'Catalog Pricing' }, { id: 'price-card', name: 'Card Pricing' }, { id: 'price-signage', name: 'Signage Pricing' }, { id: 'price-static', name: 'Custom Size / Static' }] }),
  listAttributeSets: async (): Promise<ApiResponse<{ items: Array<{ id: string; name: string }> }>> => ok({ items: [{ id: 'attr-print-core', name: 'Print Core' }, { id: 'attr-paper-finishes', name: 'Paper & Finish' }, { id: 'attr-large-format', name: 'Large Format' }] }),
  listAccuZipConfigs: async (): Promise<ApiResponse<{ items: Array<{ id: string; name: string }> }>> => ok({ items: [{ id: 'accu-std', name: 'Standard Postal Presort' }, { id: 'accu-bulk', name: 'Bulk Mail Processing' }] })
};
