import type { ArtworkProof, CustomerRecord, GeneralSetting, ProductionJob, QuoteRecord } from '@/data/operations';

const KEYS = { quotes: 'admin_quotes_store', customers: 'admin_customers_store', production: 'admin_production_store', artworkProofs: 'admin_artwork_proofs_store', settings: 'admin_general_settings_store', productionTickets: 'production-job-tickets' };
type ListResponse<T> = { ok?: boolean; data?: { items?: T[]; metadataJson?: { items?: T[] } } | T[]; payload?: { data?: T[] } | T[]; error?: string };
function endpointFor(key: string) { return `/api/internal/config/${encodeURIComponent(key)}/items`; }
function saveEndpointFor(key: string) { return `/api/internal/config/${encodeURIComponent(key)}`; }
function extractItems<T>(payload: ListResponse<T> | null): T[] { if (!payload) return []; const direct = Array.isArray(payload.data) ? payload.data : payload.data?.items || payload.data?.metadataJson?.items; if (Array.isArray(direct)) return direct as T[]; const nested = Array.isArray(payload.payload) ? payload.payload : payload.payload?.data; return Array.isArray(nested) ? nested as T[] : []; }
async function readDbList<T>(key: string): Promise<T[]> { const res = await fetch(endpointFor(key), { cache: 'no-store' }); const payload = (await res.json().catch(() => null)) as ListResponse<T> | null; if (!res.ok || payload?.ok === false) throw new Error(payload?.error || 'Internal config API read failed.'); return extractItems<T>(payload); }
async function readDbListSafe<T>(key: string): Promise<T[]> { try { return await readDbList<T>(key); } catch { return []; } }
async function writeDbList<T>(key: string, next: T[], title: string) { const res = await fetch(saveEndpointFor(key), { method: 'POST', headers: { 'Content-Type': 'application/json' }, body: JSON.stringify({ title, description: 'Operations workspace records', items: next, values: { count: String(next.length), savedAt: new Date().toISOString() } }) }); const payload = await res.json().catch(() => ({})); if (!res.ok || payload?.ok === false) throw new Error(payload?.error || 'Internal config API save failed.'); }
async function upsert<T extends { id: string }>(key: string, item: T, title: string): Promise<T> { const items = await readDbList<T>(key); const next = items.some((row) => row.id === item.id) ? items.map((row) => (row.id === item.id ? item : row)) : [item, ...items]; await writeDbList(key, next, title); return item; }
async function remove<T extends { id: string }>(key: string, id: string, title: string): Promise<void> { const items = await readDbList<T>(key); await writeDbList(key, items.filter((item) => item.id !== id), title); }
async function readProductionBoardInternal(): Promise<ProductionJob[]> { try { const res = await fetch('/api/internal/catalog/production-board', { cache: 'no-store' }); const payload = await res.json().catch(() => null); if (!res.ok || payload?.ok === false) throw new Error('Internal production board API failed.'); const items = payload?.data?.items; return Array.isArray(items) ? items as ProductionJob[] : []; } catch { return []; } }
async function writeProductionBoardInternal(job: ProductionJob, action: 'upsert' | 'delete' = 'upsert') { const res = await fetch('/api/internal/catalog/production-board', { method: 'POST', headers: { 'Content-Type': 'application/json' }, body: JSON.stringify(action === 'delete' ? { action: 'delete', id: job.id } : { action: 'upsert', job }) }); return res.ok; }

function normaliseStage(value: unknown): ProductionJob['stage'] { const stage = String(value || '').toLowerCase(); return ['queued', 'proofing', 'printing', 'finishing', 'shipped'].includes(stage) ? stage as ProductionJob['stage'] : 'proofing'; }
function normaliseRisk(value: unknown): ProductionJob['slaRisk'] { const risk = String(value || '').toLowerCase(); return risk === 'high' || risk === 'medium' ? risk : 'low'; }
function normalisePreflight(value: unknown): ProductionJob['preflightStatus'] { const status = String(value || '').toLowerCase(); if (['pass', 'passed', 'preflight-pass'].includes(status)) return 'pass'; if (['warning', 'preflight-warning'].includes(status)) return 'warning'; if (['fail', 'failed', 'blocked', 'preflight-fail'].includes(status)) return 'fail'; if (status === 'override') return 'override'; return 'pending'; }
function normaliseArtwork(value: unknown): ProductionJob['artworkStatus'] { const status = String(value || '').toLowerCase(); if (['approved', 'preflight-pass'].includes(status)) return status === 'approved' ? 'approved' : 'preflight-review'; if (['uploaded', 'preflight-warning', 'preflight-review'].includes(status)) return 'preflight-review'; if (['changes-requested', 'preflight-fail', 'design-required'].includes(status)) return 'changes-requested'; return 'missing'; }
function normaliseHandoff(value: unknown): ProductionJob['handoffState'] { const state = String(value || '').toLowerCase(); if (['ready-for-print', 'printing', 'finishing', 'ready-to-dispatch', 'dispatched', 'blocked', 'needs-artwork'].includes(state)) return state as ProductionJob['handoffState']; if (state === 'needs-approval') return 'needs-artwork'; return 'needs-artwork'; }
function ticketToProductionJob(ticket: Record<string, any>): ProductionJob { const preflightStatus = normalisePreflight(ticket.preflightStatus || ticket.artworkStatus); const artworkStatus = normaliseArtwork(ticket.artworkStatus); const customerProofStatus = String(ticket.customerProofStatus || ''); const handoffState = customerProofStatus === 'approved' || ticket.artworkStatus === 'approved' ? 'ready-for-print' : preflightStatus === 'fail' || ticket.status === 'blocked' ? 'blocked' : normaliseHandoff(ticket.handoffState); return { id: String(ticket.id || `pj-${ticket.orderNumber}`), orderNumber: String(ticket.orderNumber || ticket.orderId || ''), customer: String(ticket.customer || ticket.customerName || ''), product: String(ticket.product || ticket.productName || ticket.productSlug || ''), plant: String(ticket.plant || 'Default Production'), stage: normaliseStage(ticket.stage), slaRisk: normaliseRisk(ticket.slaRisk || ticket.risk), dueDate: String(ticket.dueDate || new Date().toISOString().slice(0, 10)), artworkStatus, preflightStatus, assignedOperator: String(ticket.assignedOperator || ticket.owner || 'Prepress Team'), machineName: String(ticket.machineName || 'Unassigned'), priority: ticket.priority === 'rush' || ticket.priority === 'priority' ? ticket.priority : 'standard', productionNotes: String(ticket.productionNotes || ''), dispatchMethod: ['collection', 'local-delivery', 'courier', 'royal-mail'].includes(String(ticket.dispatchMethod)) ? ticket.dispatchMethod : 'collection', handoffState, ...(ticket as any), source: ticket.source || 'production-job-tickets' } as ProductionJob; }
function mergeProductionJobs(...groups: ProductionJob[][]) { const byKey = new Map<string, ProductionJob>(); for (const group of groups) for (const job of group) { const key = String(job.orderNumber || job.id); if (!byKey.has(key)) byKey.set(key, job); else byKey.set(key, { ...byKey.get(key), ...job }); } return Array.from(byKey.values()).sort((a, b) => String(b.orderNumber || b.id).localeCompare(String(a.orderNumber || a.id))); }
async function readMergedProductionJobs() { const [internal, legacy, tickets] = await Promise.all([readProductionBoardInternal(), readDbListSafe<ProductionJob>(KEYS.production), readDbListSafe<Record<string, any>>(KEYS.productionTickets)]); return mergeProductionJobs(legacy, tickets.map(ticketToProductionJob), internal); }

export const operationsService = {
  getQuotes: async (): Promise<QuoteRecord[]> => readDbList(KEYS.quotes),
  saveQuote: async (quote: QuoteRecord) => upsert(KEYS.quotes, quote, 'Quotes'),
  deleteQuote: async (id: string) => remove<QuoteRecord>(KEYS.quotes, id, 'Quotes'),
  getCustomers: async (): Promise<CustomerRecord[]> => readDbList(KEYS.customers),
  saveCustomer: async (customer: CustomerRecord) => upsert(KEYS.customers, customer, 'Customers'),
  deleteCustomer: async (id: string) => remove<CustomerRecord>(KEYS.customers, id, 'Customers'),
  getProductionJobs: async (): Promise<ProductionJob[]> => readMergedProductionJobs(),
  saveProductionJob: async (job: ProductionJob) => { const ok = await writeProductionBoardInternal(job, 'upsert'); if (!ok) return upsert(KEYS.production, job, 'Production Jobs'); return job; },
  deleteProductionJob: async (id: string) => { const ok = await writeProductionBoardInternal({ id } as ProductionJob, 'delete'); if (!ok) return remove<ProductionJob>(KEYS.production, id, 'Production Jobs'); },
  getArtworkProofs: async (): Promise<ArtworkProof[]> => readDbList(KEYS.artworkProofs),
  saveArtworkProof: async (proof: ArtworkProof) => upsert(KEYS.artworkProofs, proof, 'Artwork Proofs'),
  deleteArtworkProof: async (id: string) => remove<ArtworkProof>(KEYS.artworkProofs, id, 'Artwork Proofs'),
  getGeneralSettings: async (): Promise<GeneralSetting[]> => readDbList(KEYS.settings),
  saveGeneralSetting: async (setting: GeneralSetting) => upsert(KEYS.settings, 'General Settings' as any)
};
