export const dynamic = 'force-dynamic';

import { NextRequest, NextResponse } from 'next/server';
import { getInternalCatalogRecord, upsertInternalCatalogRecord } from '@/core/catalog/internal-catalog.service';
import { tenantContextFromRequest } from '@/core/tenant/context';

const CONFIG_RESOURCE = 'admin-config' as any;
const CART_KEY = 'storefront-test-cart';

type CartItem = Record<string, unknown> & {
  id?: string;
  title?: string;
  productName?: string;
  quantity?: number;
  grossTotalMinor?: number;
  currency?: string;
};

function responseError(error: unknown, status = 500) {
  return NextResponse.json({ ok: false, error: error instanceof Error ? error.message : 'Storefront cart request failed.' }, { status });
}

function makeId(prefix = 'cart-item') {
  return `${prefix}-${new Date().toISOString().replace(/[-:.TZ]/g, '').slice(0, 14)}`;
}

function normaliseItem(body: CartItem): CartItem {
  const now = new Date().toISOString();
  const id = String(body.id || makeId());
  const productName = String(body.productName || body.productSlug || body.productId || 'Cart item');
  const quantity = Math.max(1, Number(body.quantity || 1));
  return {
    ...body,
    id,
    title: String(body.title || `${productName} x ${quantity}`),
    productName,
    quantity,
    status: String(body.status || 'cart-item'),
    currency: String(body.currency || 'GBP'),
    grossTotalMinor: Number(body.grossTotalMinor || 0),
    createdAt: body.createdAt || now,
    updatedAt: now,
    source: 'StorefrontTestCart',
  };
}

async function readItems(request: NextRequest): Promise<CartItem[]> {
  try {
    const record = await getInternalCatalogRecord(tenantContextFromRequest(request), CONFIG_RESOURCE, CART_KEY);
    const items = (record as any)?.metadataJson?.items;
    return Array.isArray(items) ? items : [];
  } catch (error) {
    const message = error instanceof Error ? error.message : '';
    if (message.includes('was not found')) return [];
    throw error;
  }
}

async function saveItems(request: NextRequest, items: CartItem[]) {
  return upsertInternalCatalogRecord(tenantContextFromRequest(request), CONFIG_RESOURCE, {
    id: CART_KEY,
    slug: CART_KEY,
    name: 'Storefront test cart',
    description: 'Temporary cart items generated by the storefront test flow.',
    metadataJson: {
      items,
      savedAt: new Date().toISOString(),
      storageKey: CART_KEY,
      source: 'StorefrontTestCart',
    },
  } as any);
}

export async function GET(request: NextRequest) {
  try {
    const items = await readItems(request);
    return NextResponse.json({ ok: true, source: 'internal-storefront-test-cart-db', data: { items } });
  } catch (error) {
    return responseError(error);
  }
}

export async function POST(request: NextRequest) {
  try {
    const body = await request.json().catch(() => ({}));
    const item = normaliseItem(body);
    const items = await readItems(request);
    const next = [item, ...items.filter((existing) => String(existing.id) !== String(item.id))];
    const record = await saveItems(request, next);
    return NextResponse.json({ ok: true, source: 'internal-storefront-test-cart-db', data: record, item });
  } catch (error) {
    return responseError(error);
  }
}

export async function DELETE(request: NextRequest) {
  try {
    const id = request.nextUrl.searchParams.get('id');
    if (!id) return responseError(new Error('Cart item id is required.'), 400);
    const items = await readItems(request);
    const next = items.filter((item) => String(item.id) !== String(id));
    const record = await saveItems(request, next);
    return NextResponse.json({ ok: true, source: 'internal-storefront-test-cart-db', data: record, deletedId: id });
  } catch (error) {
    return responseError(error);
  }
}
