/* This file is generated by scripts/sync-v0-theme-registry.mjs. Do not edit manually. */
import { createV0ThemeDefinition } from '@/theme-runtime/v0-package-adapter';
import {
  ThemeHomePage as CanvasThemeHomePage,
  themeManifest as canvasThemeManifest,
  themeRouteViews as canvasThemeRouteViews,
} from '@/v0-themes/canvas';

export const INSTALLED_V0_THEME_DEFINITIONS = [
  createV0ThemeDefinition({
    manifest: canvasThemeManifest,
    HomePage: CanvasThemeHomePage,
    routeViews: canvasThemeRouteViews,
    themeStyle: 'canvas',
  }),
];
