'use client';

import { useEffect, useMemo, useState } from 'react';
import { PageHeader } from '@/components/ui/page-header';
import { Card } from '@/components/ui/card';
import { Button, PrimaryButton } from '@/components/ui/buttons';
import { Input } from '@/components/forms/input';

type EnvRow = { name: string; ready: boolean; purpose: string };
type Account = { id: string; name: string; status: string; provider: string; connectedAccountId: string; chargesUse: string };
type Payload = { env: EnvRow[]; accounts: Account[]; platformBillingReady: boolean; tenantConnectReady: boolean; split: Record<string, string> };
export function PaymentAccountsPage() {
  const [data, setData] = useState<Payload | null>(null);
  const [message, setMessage] = useState('Loading payment readiness...');
  const [connectedAccountId, setConnectedAccountId] = useState('');
  const account = useMemo(() => data?.accounts?.[0], [data]);
  async function load() { try { const res = await fetch('/api/internal/payment-accounts', { cache: 'no-store' }); const payload = await res.json().catch(() => ({})); if (!res.ok || payload?.ok === false) throw new Error(payload?.error || 'Could not load payment accounts.'); setData(payload.data); setConnectedAccountId(payload.data?.accounts?.[0]?.connectedAccountId || ''); setMessage('Payment readiness loaded.'); } catch (error) { setMessage(error instanceof Error ? error.message : 'Could not load payment accounts.'); } }
  async function save() { try { const res = await fetch('/api/internal/payment-accounts', { method: 'POST', headers: { 'Content-Type': 'application/json' }, body: JSON.stringify({ connectedAccountId, status: connectedAccountId ? 'connected_manual_placeholder' : 'not_connected' }) }); const payload = await res.json().catch(() => ({})); if (!res.ok || payload?.ok === false) throw new Error(payload?.error || 'Could not save payment account.'); await load(); setMessage('Tenant customer payment account saved. Real Stripe Connect onboarding will be enabled after env is configured.'); } catch (error) { setMessage(error instanceof Error ? error.message : 'Could not save payment account.'); } }
  useEffect(() => { void load(); }, []);
  return <div className="space-y-4"><PageHeader title="Payment Accounts" subtitle="Separate tenant customer order payments from your platform subscription billing." actions={<Button onClick={() => void load()}>Refresh</Button>} />{message ? <div className="rounded-xl border border-white/10 bg-white/[0.04] p-3 text-sm text-textMuted">{message}</div> : null}<div className="grid gap-4 md:grid-cols-2"><Card><p className="text-xs uppercase tracking-wide text-textMuted">Tenant customer payments</p><p className="mt-3 text-lg font-semibold text-white">{data?.tenantConnectReady ? 'Connect ready' : 'Connect env missing'}</p><p className="mt-2 text-sm text-textMuted">This is for customer checkout/order payments. Money should go to the tenant/store Stripe account.</p></Card><Card><p className="text-xs uppercase tracking-wide text-textMuted">Platform subscription billing</p><p className="mt-3 text-lg font-semibold text-white">{data?.platformBillingReady ? 'Ready' : 'Env missing'}</p><p className="mt-2 text-sm text-textMuted">This is for monthly/yearly SaaS fees paid to your platform Stripe account.</p></Card></div><Card><h3 className="text-sm font-semibold text-white">Tenant payment account</h3><p className="mt-2 text-sm text-textMuted">Provider: Stripe Connect. Until real onboarding is enabled, you can store a connected account id placeholder for planning/testing.</p><div className="mt-4 grid gap-3 md:grid-cols-[1fr_auto]"><Input value={connectedAccountId} onChange={(event) => setConnectedAccountId(event.target.value)} placeholder="acct_... connected account id" /><PrimaryButton onClick={() => void save()}>Save account</PrimaryButton></div><p className="mt-3 text-sm text-textMuted">Current status: {account?.status || 'not_connected'}</p></Card><Card><h3 className="text-sm font-semibold text-white">Required env</h3><div className="mt-3 space-y-2">{(data?.env || []).map((item) => <div key={item.name} className="rounded-xl border border-white/8 bg-white/[0.03] p-3"><div className="flex flex-wrap justify-between gap-2"><p className="font-mono text-sm text-white">{item.name}</p><span className={item.ready ? 'text-emerald-300' : 'text-amber-300'}>{item.ready ? 'set' : 'missing'}</span></div><p className="mt-1 text-xs text-textMuted">{item.purpose}</p></div>)}</div></Card></div>;
}
