import { listInternalCatalog, getInternalCatalogRecord } from '@/core/catalog/internal-catalog.service';
import { resolveVatProfileForItem } from '@/core/tax/vat-rules';
import type { TenantContext } from '@/core/tenant/types';
import type { ProductAdminRuleAction, ProductAdminRuleConfig, ProductModeSettings, ProductOptionGroup, ProductOptionValue, ProductTemplateRuleConfig } from '@/modules/products/types';

type CatalogProduct = Record<string, any> & {
  id: string;
  slug?: string;
  name?: string;
  title?: string;
  description?: string;
  subtitle?: string;
  priceFromMinor?: number | null;
  currency?: string;
  isActive?: boolean;
  status?: string;
  categoryName?: string;
  categorySlug?: string;
  metadataJson?: Record<string, any>;
  optionGroups?: ProductOptionGroup[];
  templateRules?: ProductTemplateRuleConfig;
  productModeSettings?: ProductModeSettings;
};

type SelectedOptions = Record<string, string | number | boolean | string[] | undefined>;

type DeliveryMethod = Record<string, any> & { id: string; name?: string; slug?: string; description?: string; metadataJson?: Record<string, any> };

const defaultProductModeSettings: ProductModeSettings = {
  mode: 'formula',
  active: true,
  customerPriceVisibility: 'show-price',
  formula: { enabled: true, profileKey: 'internal-print-formula', formulaKey: 'sheet-or-area-cost-plus-margin', costingBasis: 'sheet', matrixKey: '', minimumChargeMinor: 0, marginPercent: 35, roundingMinor: 5, requireResolvedConfig: true, allowMatrixFallback: true },
  supplier: { enabled: false, vendorId: '', vendorName: '', supplierProductId: '', supplierSku: '', pricingEndpointKey: '', supplierLeadTimeDays: 3, markupPercent: 35, cloneSupplierOptions: false, useSupplierArtworkSpec: false, blockedOptionKeys: '', syncStatus: 'not-connected' },
  quote: { enabled: false, quoteReason: 'Custom specification or unsupported option combination needs manual pricing.', hideInstantPrice: false, showRequestQuoteButton: true, allowArtworkUploadBeforeQuote: true, requireManualApproval: true, minimumQuoteQuantity: 1, quoteSlaHours: 4, internalOwner: 'sales' },
  routing: { priority: 'formula-first', fallbackToQuote: true, fallbackMessage: 'This configuration needs a quick manual quote before checkout.', blockCheckoutWhenUnpriced: true, notes: 'Internal hosted storefront resolver.' },
};

function mergeProductModeSettings(input?: Partial<ProductModeSettings>): ProductModeSettings { return { ...defaultProductModeSettings, ...(input || {}), formula: { ...defaultProductModeSettings.formula, ...(input?.formula || {}) }, supplier: { ...defaultProductModeSettings.supplier, ...(input?.supplier || {}) }, quote: { ...defaultProductModeSettings.quote, ...(input?.quote || {}) }, routing: { ...defaultProductModeSettings.routing, ...(input?.routing || {}) } }; }
function moneyMinor(value: unknown) { const numberValue = Number(value || 0); return Number.isFinite(numberValue) ? Math.round(numberValue) : 0; }
function optionKey(group: ProductOptionGroup) { return group.pricingKey || group.key; }
function defaultSelectedValue(group: ProductOptionGroup) { const defaultValue = group.values.find((value) => value.id === group.defaultValueId || value.isDefault) || group.values.find((value) => !value.isHidden) || group.values[0]; return defaultValue?.id; }
function selectedValueId(group: ProductOptionGroup, selections: SelectedOptions) { const key = optionKey(group); const selected = selections[key] ?? selections[group.key] ?? selections[group.id] ?? defaultSelectedValue(group); return Array.isArray(selected) ? selected[0] : selected; }
function selectedValue(group: ProductOptionGroup, selections: SelectedOptions) { const id = selectedValueId(group, selections); return group.values.find((value) => String(value.id) === String(id)); }
function conditionMatches(condition: ProductAdminRuleConfig['conditions'][number], groups: ProductOptionGroup[], selections: SelectedOptions) { const group = groups.find((item) => item.key === condition.groupKey || item.pricingKey === condition.groupKey || item.id === condition.groupKey); const raw = group ? selectedValueId(group, selections) : selections[condition.groupKey]; const value = raw === undefined || raw === null ? '' : String(raw); const target = condition.value === undefined || condition.value === null ? '' : String(condition.value); const numericValue = Number(value); const numericTarget = Number(target); if (condition.operator === 'is-empty') return value === ''; if (condition.operator === 'is-selected') return value !== '' && (!target || value === target); if (condition.operator === 'equals') return value === target; if (condition.operator === 'not-equals') return value !== target; if (condition.operator === 'greater-than') return Number.isFinite(numericValue) && Number.isFinite(numericTarget) && numericValue > numericTarget; if (condition.operator === 'less-than') return Number.isFinite(numericValue) && Number.isFinite(numericTarget) && numericValue < numericTarget; if (condition.operator === 'between') { const second = Number(condition.secondaryValue); return Number.isFinite(numericValue) && Number.isFinite(numericTarget) && Number.isFinite(second) && numericValue >= numericTarget && numericValue <= second; } return false; }
function ruleMatches(rule: ProductAdminRuleConfig, groups: ProductOptionGroup[], selections: SelectedOptions) { if (!rule.enabled) return false; if (!rule.conditions?.length) return true; return rule.conditions.every((condition) => conditionMatches(condition, groups, selections)); }
function applyRules(groups: ProductOptionGroup[], rules: ProductAdminRuleConfig[], selections: SelectedOptions) { const hiddenGroups = new Set<string>(); const requiredGroups = new Set<string>(); const hiddenValues = new Set<string>(); const visibleValues = new Set<string>(); const messages: string[] = []; const appliedActions: ProductAdminRuleAction[] = []; let priceAdjustmentMinor = 0; let priceMultiplier = 1; let leadTimeDaysAdjustment = 0; let blockedCheckout = false; let quoteRequiredByRule = false; const ordered = [...rules].sort((a, b) => (a.priority || 999) - (b.priority || 999)); for (const rule of ordered) { if (!ruleMatches(rule, groups, selections)) continue; for (const action of rule.actions || []) { appliedActions.push(action); if (action.type === 'hide-group' && action.targetGroupKey) hiddenGroups.add(action.targetGroupKey); if (action.type === 'require-group' && action.targetGroupKey) requiredGroups.add(action.targetGroupKey); if (action.type === 'hide-value' && action.targetValueId) hiddenValues.add(action.targetValueId); if (action.type === 'show-value' && action.targetValueId) visibleValues.add(action.targetValueId); if (action.type === 'add-price') priceAdjustmentMinor += moneyMinor(action.amountMinor); if (action.type === 'multiply-price' && Number(action.multiplier)) priceMultiplier *= Number(action.multiplier); if (action.type === 'set-lead-time') leadTimeDaysAdjustment = Math.max(leadTimeDaysAdjustment, Number(action.leadTimeDays || 0)); if (action.type === 'block-checkout') blockedCheckout = true; if (action.type === 'set-artwork-mode') quoteRequiredByRule = true; if (action.message) messages.push(action.message); } if (rule.stopProcessing) break; } const resolvedGroups = groups.filter((group) => !hiddenGroups.has(group.key) && !hiddenGroups.has(group.pricingKey || '') && !hiddenGroups.has(group.id)).map((group) => ({ ...group, required: group.required || requiredGroups.has(group.key) || requiredGroups.has(group.pricingKey || '') || requiredGroups.has(group.id), values: group.values.filter((value) => !hiddenValues.has(value.id) || visibleValues.has(value.id)), selectedValueId: selectedValueId(group, selections) })); return { resolvedGroups, messages: Array.from(new Set(messages)), appliedActions, priceAdjustmentMinor, priceMultiplier, leadTimeDaysAdjustment, blockedCheckout, quoteRequiredByRule }; }
function selectedQuantity(groups: ProductOptionGroup[], selections: SelectedOptions) { const quantityGroup = groups.find((group) => group.source === 'quantity' || group.pricingKey === 'quantity' || group.key === 'quantity'); const selected = quantityGroup ? selectedValue(quantityGroup, selections) : undefined; const selectedFromRequest = selections.quantity || selections.qty; return Number(selectedFromRequest || selected?.quantity || selected?.label || 1) || 1; }
function selectedCosts(groups: ProductOptionGroup[], selections: SelectedOptions) { let setupCostMinor = 0; let runCostMinor = 0; let multiplier = 1; let extraCostMinor = 0; for (const group of groups) { const value = selectedValue(group, selections); if (!value) continue; setupCostMinor += moneyMinor(value.setupCostMinor); runCostMinor += moneyMinor(value.runCostMinor || value.extraCostMinor); extraCostMinor += moneyMinor(value.extraCostMinor); if (Number(value.pricingMultiplier)) multiplier *= Number(value.pricingMultiplier); } return { setupCostMinor, runCostMinor, multiplier, extraCostMinor }; }
function roundMinor(value: number, roundingMinor: number) { const step = Math.max(1, Number(roundingMinor || 1)); return Math.ceil(value / step) * step; }
function resolveFormulaPrice(product: CatalogProduct, groups: ProductOptionGroup[], selections: SelectedOptions, mode: ProductModeSettings, ruleEffects: ReturnType<typeof applyRules>) { if (!mode.formula.enabled) return null; const quantity = selectedQuantity(groups, selections); const costs = selectedCosts(groups, selections); const baseMinor = moneyMinor(product.priceFromMinor) || costs.setupCostMinor || mode.formula.minimumChargeMinor || 0; const variableMinor = costs.runCostMinor * quantity + costs.extraCostMinor; const subtotal = Math.max(mode.formula.minimumChargeMinor || 0, (baseMinor + variableMinor + ruleEffects.priceAdjustmentMinor) * costs.multiplier * ruleEffects.priceMultiplier); const withMargin = subtotal * (1 + (Number(mode.formula.marginPercent || 0) / 100)); return { source: 'formula', ok: true, currency: product.currency || 'GBP', subtotalMinor: roundMinor(subtotal, mode.formula.roundingMinor), totalMinor: roundMinor(withMargin, mode.formula.roundingMinor), quantity, message: `Formula price resolved using ${mode.formula.profileKey || mode.formula.costingBasis}.`, breakdown: { baseMinor, setupCostMinor: costs.setupCostMinor, runCostMinor: costs.runCostMinor, extraCostMinor: costs.extraCostMinor, ruleAdjustmentMinor: ruleEffects.priceAdjustmentMinor, optionMultiplier: costs.multiplier, ruleMultiplier: ruleEffects.priceMultiplier, marginPercent: mode.formula.marginPercent, roundingMinor: mode.formula.roundingMinor } }; }
function resolveSupplierPrice(product: CatalogProduct, mode: ProductModeSettings) { if (!mode.supplier.enabled) return null; if (!mode.supplier.vendorId && !mode.supplier.vendorName) return { source: 'supplier', ok: false, currency: product.currency || 'GBP', totalMinor: null, message: 'Supplier mode enabled but supplier is not mapped.' }; if (!mode.supplier.supplierProductId && !mode.supplier.supplierSku) return { source: 'supplier', ok: false, currency: product.currency || 'GBP', totalMinor: null, message: 'Supplier product ID/SKU is missing.' }; const baseMinor = moneyMinor(product.priceFromMinor); if (!baseMinor) return { source: 'supplier', ok: false, currency: product.currency || 'GBP', totalMinor: null, message: 'Supplier API is mapped but no live supplier price is connected yet.' }; const totalMinor = Math.round(baseMinor * (1 + Number(mode.supplier.markupPercent || 0) / 100)); return { source: 'supplier', ok: true, currency: product.currency || 'GBP', subtotalMinor: baseMinor, totalMinor, message: `Supplier placeholder price resolved for ${mode.supplier.vendorName || mode.supplier.vendorId}. Live API pricing can replace this later.`, supplier: { vendorId: mode.supplier.vendorId, vendorName: mode.supplier.vendorName, supplierProductId: mode.supplier.supplierProductId, supplierSku: mode.supplier.supplierSku, syncStatus: mode.supplier.syncStatus, markupPercent: mode.supplier.markupPercent } }; }
function choosePrice(product: CatalogProduct, groups: ProductOptionGroup[], selections: SelectedOptions, mode: ProductModeSettings, ruleEffects: ReturnType<typeof applyRules>) { const formula = resolveFormulaPrice(product, groups, selections, mode, ruleEffects); const supplier = resolveSupplierPrice(product, mode); const routes = mode.routing.priority === 'supplier-first' ? [supplier, formula] : mode.routing.priority === 'quote-first' ? [] : [formula, supplier]; const resolved = routes.find((route) => route?.ok) || null; const quoteRequired = mode.quote.enabled && (mode.mode === 'quote' || mode.customerPriceVisibility === 'request-quote' || !resolved || ruleEffects.quoteRequiredByRule); return { selected: resolved, formula, supplier, quoteRequired, priceVisible: Boolean(resolved && !mode.quote.hideInstantPrice && mode.customerPriceVisibility !== 'request-quote'), unpriced: !resolved }; }
function mapDeliveryMethod(row: DeliveryMethod) { const meta = row.metadataJson || {}; const enabled = meta.enabled !== false; const showAtCheckout = meta.showAtCheckout !== false; return { id: row.id, name: row.name || row.title || row.slug, publicLabel: meta.publicLabel || row.name || row.title, checkoutDescription: meta.checkoutDescription || row.description || '', fulfilmentMode: meta.fulfilmentMode || 'delivery', zoneType: meta.zoneType || 'manual', zoneName: meta.zoneName || 'Manual zone', postcodeRules: meta.postcodeRules || '', pricingBasis: meta.pricingBasis || 'flat', basePriceMinor: moneyMinor(meta.basePriceMinor), freeAboveMinor: meta.freeAboveMinor === undefined ? undefined : moneyMinor(meta.freeAboveMinor), cutoffTime: meta.cutoffTime || '16:00', transitDays: meta.transitDays || '', productionBufferDays: Number(meta.productionBufferDays || 0), sameDayEligible: Boolean(meta.sameDayEligible), nextDayEligible: Boolean(meta.nextDayEligible), requiresManualApproval: Boolean(meta.requiresManualApproval), taxClass: meta.taxClass || 'standard', vatRate: meta.vatRate ?? meta.taxRate ?? 20, enabled, showAtCheckout, sortOrder: Number(meta.sortOrder || 999) }; }
function postcodeMatches(method: ReturnType<typeof mapDeliveryMethod>, postcode?: string) { if (!postcode) return true; if (!method.postcodeRules || method.zoneType === 'pickup') return true; const normalised = postcode.trim().toUpperCase().replace(/\s+/g, ''); return String(method.postcodeRules).split(',').map((part) => part.trim().toUpperCase().replace(/\s+/g, '')).filter(Boolean).some((rule) => { if (rule === 'UKMAINLAND' || rule.includes('UKMAINLAND')) return true; if (rule.endsWith('*')) return normalised.startsWith(rule.slice(0, -1)); return normalised.startsWith(rule); }); }
export async function resolveDeliveryOptions(ctx: TenantContext, input: { postcode?: string; subtotalMinor?: number } = {}) { const list = await listInternalCatalog(ctx, 'shipping-methods', { limit: 200 }); const subtotal = moneyMinor(input.subtotalMinor); const options = (list.items || []).map((item) => mapDeliveryMethod(item as DeliveryMethod)).filter((method) => method.enabled && method.showAtCheckout && postcodeMatches(method, input.postcode)).map((method) => { const free = method.freeAboveMinor !== undefined && subtotal >= method.freeAboveMinor; return { ...method, priceMinor: free ? 0 : method.basePriceMinor, freeApplied: free }; }).sort((a, b) => a.sortOrder - b.sortOrder || String(a.publicLabel).localeCompare(String(b.publicLabel))); return { options, count: options.length }; }

async function loadProduct(ctx: TenantContext, idOrSlug: string): Promise<CatalogProduct> { const product = await getInternalCatalogRecord(ctx, 'products', idOrSlug) as CatalogProduct; const metadata = product.metadataJson || {}; return { ...product, optionGroups: product.optionGroups || metadata.optionGroups || [], templateRules: product.templateRules || metadata.templateRules, productModeSettings: product.productModeSettings || metadata.productModeSettings }; }
function publicProduct(product: CatalogProduct) { const vat = resolveVatProfileForItem({ ...product, productName: product.name || product.title, categoryName: product.categoryName, categorySlug: product.categorySlug, metadataJson: product.metadataJson || {} }); return { id: product.id, slug: product.slug, name: product.name || product.title, title: product.title || product.name, description: product.description || product.subtitle || '', categoryName: product.categoryName, categorySlug: product.categorySlug, status: product.status, isActive: product.isActive, priceFromMinor: product.priceFromMinor, currency: product.currency || 'GBP', vatRate: vat.vatRate, vatClass: vat.vatClass, vatReason: vat.vatReason }; }
function withVatPricing(product: CatalogProduct, pricing: ReturnType<typeof choosePrice>) { const vat = resolveVatProfileForItem({ ...product, productName: product.name || product.title, categoryName: product.categoryName, categorySlug: product.categorySlug, metadataJson: product.metadataJson || {} }); const grossMinor = moneyMinor(pricing.selected?.totalMinor); const netMinor = vat.vatRate > 0 ? Math.round(grossMinor / (1 + vat.vatRate / 100)) : grossMinor; const vatMinor = Math.max(0, grossMinor - netMinor); return { ...pricing, vatRate: vat.vatRate, vatClass: vat.vatClass, vatReason: vat.vatReason, netMinor, vatMinor, grossMinor, selected: pricing.selected ? { ...pricing.selected, vatRate: vat.vatRate, vatClass: vat.vatClass, vatReason: vat.vatReason, netMinor, vatMinor, grossMinor, totalMinor: grossMinor } : pricing.selected }; }
export async function resolveStorefrontProduct(ctx: TenantContext, idOrSlug: string, selections: SelectedOptions = {}) { const product = await loadProduct(ctx, idOrSlug); const optionGroups = product.optionGroups || []; const templateRules = product.templateRules; const productModeSettings = mergeProductModeSettings(product.productModeSettings); const adminRules = templateRules?.adminRules || []; const ruleEffects = applyRules(optionGroups, adminRules, selections); const pricingRaw = choosePrice(product, ruleEffects.resolvedGroups as ProductOptionGroup[], selections, productModeSettings, ruleEffects); const pricing = withVatPricing(product, pricingRaw); const delivery = await resolveDeliveryOptions(ctx, { subtotalMinor: pricing.selected?.totalMinor || product.priceFromMinor || 0 }); const checkoutBlocked = Boolean(ruleEffects.blockedCheckout || (pricing.unpriced && productModeSettings.routing.blockCheckoutWhenUnpriced && !productModeSettings.routing.fallbackToQuote)); return { ok: true, source: 'internal-storefront-resolver', product: publicProduct(product), selectedOptions: selections, resolvedOptions: ruleEffects.resolvedGroups, optionGroups: ruleEffects.resolvedGroups, templateRules: templateRules ? { templateKey: templateRules.templateKey, templateName: templateRules.templateName, mergeMode: templateRules.mergeMode, artworkRules: templateRules.artworkRules, pricingProfileKey: templateRules.pricingProfileKey, productionMethod: templateRules.productionMethod } : null, productMode: { mode: productModeSettings.mode, active: productModeSettings.active, customerPriceVisibility: productModeSettings.customerPriceVisibility, routing: productModeSettings.routing, formula: productModeSettings.formula, supplier: productModeSettings.supplier, quote: productModeSettings.quote }, pricing, deliveryOptions: delivery.options, appliedRules: { actions: ruleEffects.appliedActions, messages: ruleEffects.messages, priceAdjustmentMinor: ruleEffects.priceAdjustmentMinor, priceMultiplier: ruleEffects.priceMultiplier, leadTimeDaysAdjustment: ruleEffects.leadTimeDaysAdjustment }, checkout: { blocked: checkoutBlocked, quoteRequired: pricing.quoteRequired, blockReason: checkoutBlocked ? productModeSettings.routing.fallbackMessage || 'This product cannot be checked out until it is priced.' : null, messages: ruleEffects.messages } }; }
export async function resolveStorefrontCartPrice(ctx: TenantContext, input: { productId: string; selections?: SelectedOptions; quantity?: number }) { const selections = { ...(input.selections || {}), ...(input.quantity ? { quantity: input.quantity } : {}) }; const resolved = await resolveStorefrontProduct(ctx, input.productId, selections); return { ok: true, source: 'internal-storefront-resolver', product: resolved.product, selectedOptions: resolved.selectedOptions, pricing: resolved.pricing, checkout: resolved.checkout, appliedRules: resolved.appliedRules }; }
export async function createQuoteRequest(ctx: TenantContext, input: Record<string, any>) { const productId = String(input.productId || input.slug || ''); const resolved = productId ? await resolveStorefrontProduct(ctx, productId, input.selections || {}) : null; return { ok: true, source: 'internal-storefront-resolver', mode: 'quote-request-captured', quoteRequest: { id: `quote_${Date.now()}`, tenantId: ctx.tenantId, siteId: ctx.siteId, productId, customer: input.customer || {}, selections: input.selections || {}, artwork: input.artwork || null, notes: input.notes || '', status: 'draft-review-required', createdAt: new Date().toISOString() }, resolved }; }
