import { getInternalCatalogRecord, upsertInternalCatalogRecord } from '@/core/catalog/internal-catalog.service';
import { tenantContextFromRequest } from '@/core/tenant/context';
import { DRAFT_ORDER_KEY, readDraftOrders, saveDraftOrders } from '@/core/storefront/cart-checkout-bridge';

const CONFIG_RESOURCE = 'admin-config' as any;
export const FINAL_ORDER_KEY = 'storefront-final-orders';
export const ORDER_LOCK_KEY = 'storefront-order-locks';
export const FINANCE_LEDGER_KEY = 'storefront-finance-ledger';
export const PAYMENT_INTENT_KEY = 'storefront-payment-intents';

type Store = Record<string, any>;

function makeId(prefix: string) {
  return `${prefix}-${new Date().toISOString().replace(/[-:.TZ]/g, '').slice(0, 14)}-${Math.random().toString(16).slice(2, 8)}`;
}

function money(value: unknown) {
  const next = Number(value);
  return Number.isFinite(next) && next >= 0 ? Math.round(next) : 0;
}

async function readConfig(request: Request, key: string) {
  try {
    return await getInternalCatalogRecord(tenantContextFromRequest(request), CONFIG_RESOURCE, key);
  } catch (error) {
    const message = error instanceof Error ? error.message : '';
    if (message.includes('was not found')) return null;
    throw error;
  }
}

async function writeConfig(request: Request, key: string, name: string, metadataJson: Store) {
  return upsertInternalCatalogRecord(tenantContextFromRequest(request), CONFIG_RESOURCE, {
    id: key,
    slug: key,
    name,
    description: `${name} generated by internal storefront services.`,
    metadataJson: { ...metadataJson, savedAt: new Date().toISOString(), storageKey: key, source: 'StorefrontOrderPaymentSafety' },
  } as any);
}

export async function readFinalOrders(request: Request) {
  const record = await readConfig(request, FINAL_ORDER_KEY);
  const items = (record as any)?.metadataJson?.items;
  return Array.isArray(items) ? items : [];
}

export async function saveFinalOrders(request: Request, items: Store[]) {
  return writeConfig(request, FINAL_ORDER_KEY, 'Storefront final orders', { items });
}

export async function readOrderLocks(request: Request) {
  const record = await readConfig(request, ORDER_LOCK_KEY);
  const items = (record as any)?.metadataJson?.items;
  return Array.isArray(items) ? items : [];
}

export async function saveOrderLocks(request: Request, items: Store[]) {
  return writeConfig(request, ORDER_LOCK_KEY, 'Storefront order locks', { items });
}

export async function readFinanceLedger(request: Request) {
  const record = await readConfig(request, FINANCE_LEDGER_KEY);
  const ledger = (record as any)?.metadataJson?.ledger || {};
  return {
    invoices: Array.isArray(ledger.invoices) ? ledger.invoices : [],
    payments: Array.isArray(ledger.payments) ? ledger.payments : [],
    vatSnapshots: Array.isArray(ledger.vatSnapshots) ? ledger.vatSnapshots : [],
  };
}

export async function saveFinanceLedger(request: Request, ledger: Store) {
  return writeConfig(request, FINANCE_LEDGER_KEY, 'Storefront finance ledger', { ledger });
}

export async function readPaymentStore(request: Request) {
  const record = await readConfig(request, PAYMENT_INTENT_KEY);
  const store = (record as any)?.metadataJson?.store || {};
  return {
    intents: Array.isArray(store.intents) ? store.intents : [],
    events: Array.isArray(store.events) ? store.events : [],
  };
}

export async function savePaymentStore(request: Request, store: Store) {
  return writeConfig(request, PAYMENT_INTENT_KEY, 'Storefront payment intents', { store });
}

function findDraft(drafts: Store[], id: string) {
  return drafts.find((entry) => String(entry.id) === id || String(entry.quoteReference) === id);
}

function totalsFromDraft(draft: Store) {
  const totals = draft.totals || draft.payload?.totals || {};
  return {
    currency: String(draft.currency || totals.currency || 'GBP'),
    netTotalMinor: money(draft.netTotalMinor ?? totals.netTotalMinor),
    vatTotalMinor: money(draft.vatTotalMinor ?? totals.vatTotalMinor),
    grossTotalMinor: money(draft.grossTotalMinor ?? totals.grossTotalMinor),
    vatBreakdown: Array.isArray(draft.vatBreakdown) ? draft.vatBreakdown : Array.isArray(totals.vatBreakdown) ? totals.vatBreakdown : [],
  };
}

function validateTotals(totals: Store) {
  if (totals.grossTotalMinor !== totals.netTotalMinor + totals.vatTotalMinor) {
    throw new Error('Order totals do not reconcile.');
  }
}

export async function finaliseDraftOrder(request: Request, input: Store) {
  const draftId = String(input.draftOrderId || input.orderId || input.id || input.quoteReference || '').trim();
  if (!draftId) throw new Error('Draft order id or quoteReference is required.');

  const [drafts, finalOrders, locks, ledger, paymentStore] = await Promise.all([
    readDraftOrders(request),
    readFinalOrders(request),
    readOrderLocks(request),
    readFinanceLedger(request),
    readPaymentStore(request),
  ]);

  const existingFinal = finalOrders.find((order) => String(order.sourceDraftId) === draftId || String(order.quoteReference) === draftId);
  if (existingFinal) return { order: existingFinal, invoice: ledger.invoices.find((invoice: Store) => invoice.orderId === existingFinal.id), paymentIntent: paymentStore.intents.find((intent: Store) => intent.orderId === existingFinal.id), duplicate: true };

  const draft = findDraft(drafts, draftId);
  if (!draft) throw new Error('Draft order was not found for finalisation.');
  const now = new Date().toISOString();
  const totals = totalsFromDraft(draft);
  validateTotals(totals);

  const order = {
    ...draft,
    id: makeId('order'),
    sourceDraftId: draft.id,
    orderNumber: `ORD-${Date.now()}`,
    quoteReference: draft.quoteReference || draft.payload?.quoteReference || '',
    status: 'awaiting-payment',
    paymentStatus: 'payment-required',
    productionStatus: 'payment-lock',
    locked: true,
    lockReason: 'Payment must be authorised or captured before production release.',
    totals,
    ...totals,
    finalisedAt: now,
    updatedAt: now,
    source: 'StorefrontOrderFinalisation',
    history: [{ at: now, action: 'finalised-from-draft', source: 'order-payment-safety' }, ...(Array.isArray(draft.history) ? draft.history : [])],
  };

  const invoice = {
    id: makeId('invoice'),
    invoiceNumber: `INV-${Date.now()}`,
    orderId: order.id,
    orderNumber: order.orderNumber,
    customerName: order.customerName || order.customer?.name || order.payload?.customer?.name || '',
    customerEmail: order.customerEmail || order.customer?.email || order.payload?.customer?.email || '',
    status: 'issued',
    ...totals,
    issuedAt: now,
    updatedAt: now,
    source: 'StorefrontOrderFinalisation',
    history: [{ at: now, action: 'issued-from-order', source: 'order-payment-safety' }],
  };

  const paymentIntent = {
    id: makeId('pay-intent'),
    provider: 'stripe-ready',
    providerMode: 'not-connected',
    providerIntentId: `stripe_ready_${Date.now()}`,
    paymentUrl: `/checkout/pay/${invoice.invoiceNumber}`,
    invoiceId: invoice.id,
    invoiceNumber: invoice.invoiceNumber,
    orderId: order.id,
    orderNumber: order.orderNumber,
    customerName: invoice.customerName,
    customerEmail: invoice.customerEmail,
    amountMinor: totals.grossTotalMinor,
    currency: totals.currency,
    status: 'payment_link_created',
    createdAt: now,
    updatedAt: now,
    history: [{ at: now, action: 'created-with-final-order', source: 'order-payment-safety' }],
  };

  const lock = { id: makeId('lock'), orderId: order.id, orderNumber: order.orderNumber, status: 'active', reason: order.lockReason, createdAt: now, source: 'StorefrontOrderFinalisation' };

  await Promise.all([
    saveFinalOrders(request, [order, ...finalOrders]),
    saveOrderLocks(request, [lock, ...locks]),
    saveFinanceLedger(request, { ...ledger, invoices: [invoice, ...ledger.invoices], vatSnapshots: [{ id: makeId('vat-snapshot'), orderId: order.id, invoiceId: invoice.id, vatBreakdown: totals.vatBreakdown, vatTotalMinor: totals.vatTotalMinor, createdAt: now }, ...ledger.vatSnapshots] }),
    savePaymentStore(request, { intents: [paymentIntent, ...paymentStore.intents], events: [{ id: makeId('payment-event'), intentId: paymentIntent.id, invoiceId: invoice.id, orderId: order.id, action: 'create-with-final-order', status: paymentIntent.status, amountMinor: paymentIntent.amountMinor, currency: paymentIntent.currency, createdAt: now }, ...paymentStore.events] }),
    saveDraftOrders(request, drafts.map((entry) => String(entry.id) === String(draft.id) ? { ...entry, status: 'finalised', finalOrderId: order.id, updatedAt: now } : entry)),
  ]);

  return { order, invoice, paymentIntent, lock, duplicate: false };
}

export async function applyPaymentEventToOrder(request: Request, input: Store) {
  const intentId = String(input.intentId || input.paymentIntentId || '').trim();
  const action = String(input.action || '').trim();
  if (!intentId) throw new Error('Payment intent id is required.');
  if (!['mark-authorized', 'mark-captured', 'mark-failed', 'cancel-intent'].includes(action)) throw new Error('Unsupported payment action.');

  const [finalOrders, locks, ledger, paymentStore] = await Promise.all([readFinalOrders(request), readOrderLocks(request), readFinanceLedger(request), readPaymentStore(request)]);
  const now = new Date().toISOString();
  let updatedIntent: Store | null = null;
  const nextStatus = action === 'mark-authorized' ? 'authorized' : action === 'mark-captured' ? 'captured' : action === 'mark-failed' ? 'failed' : 'cancelled';

  const intents = paymentStore.intents.map((intent: Store) => {
    if (String(intent.id) !== intentId) return intent;
    updatedIntent = { ...intent, status: nextStatus, updatedAt: now, capturedAt: nextStatus === 'captured' ? now : intent.capturedAt || null, history: [{ at: now, action, source: 'order-payment-safety' }, ...(Array.isArray(intent.history) ? intent.history : [])] };
    return updatedIntent;
  });
  if (!updatedIntent) throw new Error('Payment intent not found.');

  const orders = finalOrders.map((order) => {
    if (String(order.id) !== String(updatedIntent?.orderId)) return order;
    const paid = nextStatus === 'authorized' || nextStatus === 'captured';
    return { ...order, status: paid ? 'confirmed' : nextStatus === 'failed' ? 'payment-failed' : order.status, paymentStatus: nextStatus, productionStatus: paid ? 'ready-for-production-gate' : 'payment-lock', locked: !paid, lockReason: paid ? null : order.lockReason, updatedAt: now, history: [{ at: now, action: `payment-${nextStatus}`, source: 'order-payment-safety' }, ...(Array.isArray(order.history) ? order.history : [])] };
  });

  const activeLocks = locks.map((lock) => String(lock.orderId) === String(updatedIntent?.orderId) && (nextStatus === 'authorized' || nextStatus === 'captured') ? { ...lock, status: 'released', releasedAt: now } : lock);
  const invoices = ledger.invoices.map((invoice: Store) => String(invoice.id) === String(updatedIntent?.invoiceId) ? { ...invoice, status: nextStatus === 'captured' ? 'paid' : nextStatus === 'authorized' ? 'authorized' : nextStatus === 'failed' ? 'payment-failed' : invoice.status, paidAt: nextStatus === 'captured' ? now : invoice.paidAt || null, updatedAt: now } : invoice);
  const payments = nextStatus === 'captured' && !ledger.payments.some((payment: Store) => String(payment.intentId) === intentId)
    ? [{ id: makeId('payment'), intentId, invoiceId: updatedIntent.invoiceId, orderId: updatedIntent.orderId, amountMinor: updatedIntent.amountMinor, currency: updatedIntent.currency, status: 'captured-tracked', trackedAt: now, source: 'order-payment-safety' }, ...ledger.payments]
    : ledger.payments;

  await Promise.all([
    saveFinalOrders(request, orders),
    saveOrderLocks(request, activeLocks),
    saveFinanceLedger(request, { ...ledger, invoices, payments }),
    savePaymentStore(request, { intents, events: [{ id: makeId('payment-event'), intentId, invoiceId: updatedIntent.invoiceId, orderId: updatedIntent.orderId, action, status: nextStatus, amountMinor: updatedIntent.amountMinor, currency: updatedIntent.currency, createdAt: now }, ...paymentStore.events] }),
  ]);

  return { intent: updatedIntent, orders, locks: activeLocks, ledger: { ...ledger, invoices, payments } };
}
