import { getInternalCatalogRecord, upsertInternalCatalogRecord } from '@/core/catalog/internal-catalog.service';
import { tenantContextFromRequest } from '@/core/tenant/context';
import { syncWorkflowFromFinalOrders, transitionWorkflowItem } from '@/core/storefront/production-workflow';

const CONFIG_RESOURCE = 'admin-config' as any;
export const PLANNER_KEY = 'storefront-production-planner';
const PRODUCTION_TICKETS_KEY = 'production-job-tickets';

type Store = Record<string, any>;
type PlannerStage = 'queued' | 'prepress' | 'print' | 'finish' | 'dispatch' | 'completed' | 'blocked';

const DEFAULT_SHIFTS = [
  { id: 'shift-morning', name: 'Morning', startHour: 8, endHour: 13, enabled: true },
  { id: 'shift-evening', name: 'Evening', startHour: 13, endHour: 18, enabled: true },
  { id: 'shift-night', name: 'Night', startHour: 18, endHour: 22, enabled: false },
];
const MACHINE_LANES = [
  { id: 'lane-digital-sra3', name: 'Digital SRA3', type: 'digital', maxWidthMm: 320, supports: ['business-cards', 'leaflets', 'flyers'], stage: 'print', minutesPerDay: 420, makeReadyMinutes: 8, speedSheetsPerHour: 900, workStartHour: 8, liveStatus: 'idle' },
  { id: 'lane-digital-sra2', name: 'Digital SRA2', type: 'digital', maxWidthMm: 450, supports: ['leaflets', 'booklets', 'posters'], stage: 'print', minutesPerDay: 420, makeReadyMinutes: 10, speedSheetsPerHour: 650, workStartHour: 8, liveStatus: 'idle' },
  { id: 'lane-large-format', name: 'Large Format Roll', type: 'large-format', maxWidthMm: 1600, supports: ['banner', 'pvc-banner', 'poster'], stage: 'print', minutesPerDay: 390, makeReadyMinutes: 12, speedSheetsPerHour: 60, workStartHour: 8, liveStatus: 'idle' },
  { id: 'lane-finishing', name: 'Finishing', type: 'finishing', maxWidthMm: 0, supports: ['lamination', 'cutting', 'creasing', 'booklets'], stage: 'finish', minutesPerDay: 390, makeReadyMinutes: 10, speedSheetsPerHour: 500, workStartHour: 8, liveStatus: 'idle' },
  { id: 'lane-dispatch', name: 'Dispatch', type: 'dispatch', maxWidthMm: 0, supports: ['all'], stage: 'dispatch', minutesPerDay: 360, makeReadyMinutes: 5, speedSheetsPerHour: 120, workStartHour: 8, liveStatus: 'idle' },
];

function nowIso() { return new Date().toISOString(); }
function makeId(prefix: string) { return `${prefix}-${new Date().toISOString().replace(/[-:.TZ]/g, '').slice(0, 14)}-${Math.random().toString(36).slice(2, 8)}`; }
function asNumber(value: unknown, fallback = 0) { const n = Number(value); return Number.isFinite(n) && n >= 0 ? n : fallback; }
function addDays(date: Date, days: number) { const next = new Date(date); next.setDate(next.getDate() + days); return next; }
function text(value: unknown) { return String(value || '').trim(); }

async function readRecord(request: Request) { try { return await getInternalCatalogRecord(tenantContextFromRequest(request), CONFIG_RESOURCE, PLANNER_KEY); } catch (error) { const message = error instanceof Error ? error.message : ''; if (message.includes('was not found')) return null; throw error; } }
async function readConfigItems(request: Request, key: string) { try { const record = await getInternalCatalogRecord(tenantContextFromRequest(request), CONFIG_RESOURCE, key); const json = (record as any)?.metadataJson || {}; if (Array.isArray(json.items)) return json.items as Store[]; if (Array.isArray(json.store?.items)) return json.store.items as Store[]; return []; } catch (error) { const message = error instanceof Error ? error.message : ''; if (message.includes('was not found')) return []; throw error; } }
export async function readPlannerStore(request: Request) { const record = await readRecord(request); const store = (record as any)?.metadataJson?.store || {}; return { jobs: Array.isArray(store.jobs) ? store.jobs : [], actions: Array.isArray(store.actions) ? store.actions : [], lanes: Array.isArray(store.lanes) ? store.lanes : MACHINE_LANES, batches: Array.isArray(store.batches) ? store.batches : [], shifts: Array.isArray(store.shifts) ? store.shifts : DEFAULT_SHIFTS, downtime: Array.isArray(store.downtime) ? store.downtime : [], liveEvents: Array.isArray(store.liveEvents) ? store.liveEvents : [], scheduleSettings: store.scheduleSettings || { mode: 'capacity-priority', includeWeekends: false } }; }
export async function savePlannerStore(request: Request, store: Store) { return upsertInternalCatalogRecord(tenantContextFromRequest(request), CONFIG_RESOURCE, { id: PLANNER_KEY, slug: PLANNER_KEY, name: 'Storefront production planner', description: 'Persistent machine planner jobs generated from paid storefront workflow items and approved proofing tickets.', metadataJson: { store, savedAt: nowIso(), storageKey: PLANNER_KEY, source: 'StorefrontProductionPlanner' } } as any); }

function productText(item: Store) { return `${item.productSlug || ''} ${item.productName || ''} ${item.product || ''} ${item.orderNumber || ''}`.toLowerCase(); }
function laneForWorkflowItem(item: Store) { const value = productText(item); if (value.includes('banner') || value.includes('pvc')) return MACHINE_LANES[2]; if (value.includes('booklet') || value.includes('flyer') || value.includes('leaflet')) return MACHINE_LANES[1]; return MACHINE_LANES[0]; }
function normalisePreflight(value: unknown) { const status = text(value).toLowerCase(); if (['pass', 'passed', 'preflight-pass'].includes(status)) return 'pass'; if (['warning', 'preflight-warning'].includes(status)) return 'warning'; if (['fail', 'failed', 'blocked', 'preflight-fail'].includes(status)) return 'fail'; if (status === 'override') return 'override'; return 'pending'; }
function paymentReleased(item: Store) { const status = text(item.paymentStatus || item.paymentGate).toLowerCase(); return ['paid', 'captured', 'authorized', 'manual-paid'].includes(status) || text(item.paymentGate).toLowerCase() === 'paid'; }
function artworkReleased(ticket: Store) { return text(ticket.customerProofStatus).toLowerCase() === 'approved' || text(ticket.artworkStatus).toLowerCase() === 'approved' || normalisePreflight(ticket.preflightStatus || ticket.artworkStatus) === 'override'; }
function ticketReleased(ticket: Store) { return artworkReleased(ticket) && paymentReleased(ticket); }
function ticketBlockReason(ticket: Store) { const artwork = text(ticket.artworkStatus).toLowerCase(); const preflight = normalisePreflight(ticket.preflightStatus || ticket.artworkStatus); if (!artworkReleased(ticket)) { if (!ticket.artworkUploadId && artwork !== 'design-required') return 'Missing artwork upload.'; if (artwork === 'design-required') return 'Customer requested design help.'; if (preflight === 'fail' || artwork === 'preflight-fail') return 'Preflight failed or replacement artwork required.'; if (preflight === 'pass') return 'Preflight passed, waiting for customer approval.'; if (preflight === 'warning') return 'Preflight warning needs approval or override.'; return 'Artwork proof approval required before scheduling.'; } if (!paymentReleased(ticket)) return 'Payment has not been captured or authorised.'; return ''; }
function canCreatePlannerJob(item: Store) { const paid = ['captured', 'authorized', 'paid'].includes(String(item.paymentStatus || '').toLowerCase()); const ok = ['pass', 'override'].includes(String(item.preflightStatus || '').toLowerCase()); return paid && ok && !item.productionBlocked; }
function quantityFromItem(item: Store) { return asNumber(item.quantity || item.payload?.quantity || item.items?.[0]?.quantity || 250, 250); }
function sra3Yield(item: Store) { const value = productText(item); if (value.includes('business')) return 21; if (value.includes('a5')) return 4; if (value.includes('a4')) return 2; return 1; }
function sheetsForJob(item: Store) { return Math.max(1, Math.ceil(quantityFromItem(item) / sra3Yield(item))); }
function dueDateFor(item: Store) { const base = new Date(); const priority = String(item.priority || item.turnaround || item.selectedDelivery || item.payload?.deliveryEstimate?.service || '').toLowerCase(); const days = priority.includes('rush') || priority.includes('express') || priority.includes('same') ? 1 : priority.includes('standard') ? 3 : 5; return addDays(base, days).toISOString(); }
function priorityScore(job: Store) { if (job.stage === 'blocked' || job.productionBlocked) return -1000; const due = new Date(job.dueAt || dueDateFor(job)).getTime(); const dueSoon = Math.max(0, 100000000 - Math.max(0, due - Date.now())) / 1000000; const rush = String(job.priority || '').toLowerCase() === 'rush' ? 250 : 0; const express = String(job.priority || '').toLowerCase() === 'express' ? 150 : 0; return Math.round(rush + express + dueSoon + asNumber(job.grossTotalMinor) / 100000); }
function laneById(lanes: Store[], id: string) { return lanes.find((lane) => lane.id === id) || MACHINE_LANES[0]; }
function enabledShiftMinutes(shifts: Store[]) { return shifts.filter((s) => s.enabled !== false).reduce((sum, s) => sum + Math.max(0, (asNumber(s.endHour, 17) - asNumber(s.startHour, 8)) * 60), 0) || 420; }
function shiftStartHour(shifts: Store[]) { const enabled = shifts.filter((s) => s.enabled !== false).sort((a, b) => asNumber(a.startHour) - asNumber(b.startHour)); return asNumber(enabled[0]?.startHour, 8); }
function downtimeMinutesForLane(downtime: Store[], laneId: string) { return downtime.filter((d) => String(d.laneId) === laneId && d.active !== false).reduce((sum, d) => sum + asNumber(d.minutes, 0), 0); }
function schedulable(job: Store) { return job.stage !== 'blocked' && !job.productionBlocked && job.handoffState !== 'blocked'; }
function liveStatusForLane(jobs: Store[], lane: Store) { const active = jobs.find((j) => j.laneId === lane.id && ['prepress', 'print', 'finish', 'dispatch'].includes(String(j.stage)) && schedulable(j)); if (active) return { status: 'running', jobId: active.id, orderNumber: active.orderNumber }; const blocked = jobs.find((j) => j.laneId === lane.id && !schedulable(j)); if (blocked) return { status: 'blocked', jobId: blocked.id, orderNumber: blocked.orderNumber }; return { status: 'idle', jobId: null, orderNumber: null }; }

function jobFromWorkflow(item: Store) { const lane = laneForWorkflowItem(item); const sheets = sheetsForJob(item); const createdAt = nowIso(); return { id: makeId('planner-job'), workflowId: item.id, orderId: item.orderId, orderNumber: item.orderNumber, customerName: item.customerName || 'Storefront Customer', laneId: lane.id, laneName: lane.name, stage: 'queued' as PlannerStage, status: 'queued-for-production', priority: item.priority || 'standard', productionBlocked: false, paymentStatus: item.paymentStatus || 'captured', preflightStatus: item.preflightStatus || 'pass', grossTotalMinor: Number(item.grossTotalMinor || 0), currency: item.currency || 'GBP', quantity: quantityFromItem(item), sra3Yield: sra3Yield(item), sra3Sheets: sheets, estimatedMinutes: Math.ceil(lane.makeReadyMinutes + (sheets / Math.max(1, lane.speedSheetsPerHour)) * 60), dueAt: dueDateFor(item), scheduleScore: 0, lateRisk: false, progressPercent: 0, liveStatus: 'waiting', createdAt, updatedAt: createdAt, history: [{ at: createdAt, action: 'created-from-workflow', to: 'queued' }], source: 'StorefrontProductionPlanner' }; }
function jobFromTicket(ticket: Store) { const lane = laneForWorkflowItem(ticket); const sheets = sheetsForJob(ticket); const createdAt = nowIso(); const released = ticketReleased(ticket); const reason = ticketBlockReason(ticket); return { id: `planner-ticket-${ticket.id || ticket.orderNumber}`, workflowId: `ticket-${ticket.id || ticket.orderNumber}`, productionTicketId: ticket.id, orderId: ticket.orderId, orderNumber: ticket.orderNumber, customerName: ticket.customerName || ticket.customer || 'Storefront Customer', laneId: lane.id, laneName: lane.name, stage: released ? 'queued' as PlannerStage : 'blocked' as PlannerStage, status: released ? 'queued-for-production' : 'blocked-proof-or-payment', priority: ticket.priority || 'standard', productionBlocked: !released, blockReason: reason, paymentStatus: ticket.paymentStatus || 'unknown', paymentGate: paymentReleased(ticket) ? 'paid' : 'awaiting-payment', preflightStatus: normalisePreflight(ticket.preflightStatus || ticket.artworkStatus), artworkStatus: ticket.artworkStatus || 'missing', customerProofStatus: ticket.customerProofStatus || 'pending', handoffState: released ? 'ready-for-print' : 'blocked', artworkUploadId: ticket.artworkUploadId || null, artworkFileUrl: ticket.artworkFileUrl || null, artworkDownloadUrl: ticket.artworkDownloadUrl || null, grossTotalMinor: Number(ticket.priceMinor || ticket.grossTotalMinor || 0), currency: ticket.currency || 'GBP', quantity: quantityFromItem(ticket), sra3Yield: sra3Yield(ticket), sra3Sheets: sheets, estimatedMinutes: Math.ceil(lane.makeReadyMinutes + (sheets / Math.max(1, lane.speedSheetsPerHour)) * 60), dueAt: ticket.dueDate ? new Date(ticket.dueDate).toISOString() : dueDateFor(ticket), scheduleScore: released ? 0 : -1000, lateRisk: false, progressPercent: 0, liveStatus: released ? 'waiting' : 'blocked', createdAt, updatedAt: createdAt, history: [{ at: createdAt, action: released ? 'created-from-paid-approved-proof-ticket' : 'created-blocked-from-proof-ticket', to: released ? 'queued' : 'blocked', note: reason || null }], source: 'production-job-tickets' }; }

export function summarizePlanner(jobs: Store[]) { return { total: jobs.length, queued: jobs.filter((j) => j.stage === 'queued').length, prepress: jobs.filter((j) => j.stage === 'prepress').length, print: jobs.filter((j) => j.stage === 'print').length, finish: jobs.filter((j) => j.stage === 'finish').length, dispatch: jobs.filter((j) => j.stage === 'dispatch').length, completed: jobs.filter((j) => j.stage === 'completed').length, blocked: jobs.filter((j) => !schedulable(j)).length, schedulable: jobs.filter(schedulable).length, lateRisk: jobs.filter((j) => j.lateRisk).length, rush: jobs.filter((j) => String(j.priority).toLowerCase() === 'rush').length, running: jobs.filter((j) => j.liveStatus === 'running').length }; }
function sortForSchedule(jobs: Store[]) { return [...jobs].sort((a, b) => priorityScore(b) - priorityScore(a) || new Date(a.dueAt || 0).getTime() - new Date(b.dueAt || 0).getTime()); }
function workStart(lane: Store, shifts: Store[], dayOffset = 0) { const d = addDays(new Date(), dayOffset); d.setHours(shiftStartHour(shifts), 0, 0, 0); return d; }
function autoScheduleJobs(jobs: Store[], lanes: Store[], shifts: Store[], downtime: Store[]) { const laneCursors = new Map<string, { dayOffset: number; used: number; cursor: Date }>(); return sortForSchedule(jobs).map((job, index) => { if (job.stage === 'completed') return { ...job, scheduleScore: priorityScore(job), sequence: index + 1, liveStatus: 'done', progressPercent: 100 }; if (!schedulable(job)) return { ...job, scheduledStartAt: null, scheduledEndAt: null, scheduleScore: -1000, sequence: index + 1, liveStatus: 'blocked', progressPercent: 0, lateRisk: false }; const lane = laneById(lanes, job.laneId); const cap = Math.max(30, Math.min(asNumber(lane.minutesPerDay, 420), enabledShiftMinutes(shifts)) - downtimeMinutesForLane(downtime, lane.id)); const mins = asNumber(job.estimatedMinutes, 20); let state = laneCursors.get(lane.id) || { dayOffset: 0, used: 0, cursor: workStart(lane, shifts, 0) }; if (state.used + mins > cap) state = { dayOffset: state.dayOffset + 1, used: 0, cursor: workStart(lane, shifts, state.dayOffset + 1) }; const start = new Date(state.cursor); const end = new Date(start.getTime() + mins * 60000); const dueAt = job.dueAt || dueDateFor(job); const lateRisk = end.getTime() > new Date(dueAt).getTime(); laneCursors.set(lane.id, { dayOffset: state.dayOffset, used: state.used + mins, cursor: end }); const running = ['prepress', 'print', 'finish', 'dispatch'].includes(String(job.stage)); return { ...job, scheduledStartAt: start.toISOString(), scheduledEndAt: end.toISOString(), dueAt, lateRisk, scheduleScore: priorityScore(job), sequence: index + 1, liveStatus: running ? 'running' : 'waiting', progressPercent: running ? Math.max(10, Math.min(95, asNumber(job.progressPercent, 35))) : asNumber(job.progressPercent, 0), status: lateRisk ? 'late-risk' : job.status }; }); }
function buildCapacity(jobs: Store[], lanes: Store[], shifts: Store[], downtime: Store[]) { return lanes.map((lane) => { const laneJobs = jobs.filter((j) => j.laneId === lane.id && j.stage !== 'completed' && schedulable(j)); const used = laneJobs.reduce((sum, j) => sum + asNumber(j.estimatedMinutes), 0); const shiftCap = Math.min(asNumber(lane.minutesPerDay, 420), enabledShiftMinutes(shifts)); const down = downtimeMinutesForLane(downtime, lane.id); const cap = Math.max(30, shiftCap - down); const live = liveStatusForLane(jobs, lane); return { laneId: lane.id, laneName: lane.name, usedMinutes: used, capacityMinutes: cap, downtimeMinutes: down, remainingMinutes: Math.max(0, cap - used), overloadMinutes: Math.max(0, used - cap), utilisationPercent: Math.min(180, Math.round((used / Math.max(1, cap)) * 100)), jobCount: laneJobs.length, liveStatus: live.status, activeJobId: live.jobId, activeOrderNumber: live.orderNumber }; }); }
function buildTimeline(jobs: Store[]) { return sortForSchedule(jobs).filter((j) => j.stage !== 'completed' && schedulable(j)).map((job) => ({ jobId: job.id, orderNumber: job.orderNumber, laneId: job.laneId, laneName: job.laneName, stage: job.stage, startAt: job.scheduledStartAt, endAt: job.scheduledEndAt, dueAt: job.dueAt, lateRisk: job.lateRisk, minutes: asNumber(job.estimatedMinutes, 20), sequence: job.sequence, progressPercent: asNumber(job.progressPercent), liveStatus: job.liveStatus })); }
function buildBatches(jobs: Store[]) { const groups = new Map<string, Store[]>(); jobs.filter((j) => j.stage !== 'completed' && schedulable(j)).forEach((job) => { const key = `${job.laneId}|${job.sra3Yield || 1}|${job.preflightStatus || 'pass'}|${String(job.priority || 'standard')}`; groups.set(key, [...(groups.get(key) || []), job]); }); return Array.from(groups.entries()).map(([key, group]) => { const [laneId] = key.split('|'); const totalSheets = group.reduce((sum, j) => sum + asNumber(j.sra3Sheets, 1), 0); const avgSheets = Math.round(totalSheets / Math.max(1, group.length)); const saving = group.length > 1 ? Math.max(5, (group.length - 1) * 8) : 0; return { id: `batch-${laneId}-${group.length}-${totalSheets}`, laneId, jobIds: group.map((j) => j.id), orderNumbers: group.map((j) => j.orderNumber), jobCount: group.length, totalSra3Sheets: totalSheets, averageSheets: avgSheets, estimatedSavingMinutes: saving, suggested: group.length > 1, status: group.length > 1 ? 'recommended' : 'single', label: group.length > 1 ? `Optimise ${group.length} jobs / ${totalSheets} SRA3 sheets` : `${group[0]?.orderNumber || 'Job'} single run` }; }); }
function buildWarnings(jobs: Store[], capacity: Store[]) { return [...jobs.filter((j) => j.lateRisk).map((j) => ({ type: 'late-risk', jobId: j.id, orderNumber: j.orderNumber, message: `${j.orderNumber} is scheduled after due date.` })), ...jobs.filter((j) => !schedulable(j)).map((j) => ({ type: String(j.blockReason || '').toLowerCase().includes('payment') ? 'payment-blocked' : 'artwork-blocked', jobId: j.id, orderNumber: j.orderNumber, message: `${j.orderNumber} is not scheduled: ${j.blockReason || 'proof approval and payment are required.'}` })), ...capacity.filter((c) => c.overloadMinutes > 0).map((c) => ({ type: 'capacity-overload', laneId: c.laneId, message: `${c.laneName} is overloaded by ${c.overloadMinutes} minutes.` })), ...capacity.filter((c) => c.downtimeMinutes > 0).map((c) => ({ type: 'downtime', laneId: c.laneId, message: `${c.laneName} has ${c.downtimeMinutes} minutes downtime today.` }))]; }
function enrich(jobsInput: Store[], lanes: Store[], actions: Store[], shifts: Store[], downtime: Store[], liveEvents: Store[]) { const jobs = autoScheduleJobs(jobsInput, lanes, shifts, downtime); const capacity = buildCapacity(jobs, lanes, shifts, downtime); const timeline = buildTimeline(jobs); const batches = buildBatches(jobs); const warnings = buildWarnings(jobs, capacity); return { jobs, actions, lanes, batches, capacity, timeline, warnings, shifts, downtime, liveEvents, summary: summarizePlanner(jobs), scheduleSettings: { mode: 'capacity-priority-shift-aware-proof-payment-gated', generatedAt: nowIso() } }; }
function mergeJobsBySource(jobs: Store[]) { const byKey = new Map<string, Store>(); for (const job of jobs) { const key = String(job.productionTicketId || job.workflowId || job.orderNumber || job.id); if (!byKey.has(key)) byKey.set(key, job); else byKey.set(key, { ...byKey.get(key), ...job }); } return Array.from(byKey.values()); }
export async function syncPlannerFromWorkflow(request: Request) { const [planner, workflow, tickets] = await Promise.all([readPlannerStore(request), syncWorkflowFromFinalOrders(request), readConfigItems(request, PRODUCTION_TICKETS_KEY)]); const existing = new Set(planner.jobs.map((j: Store) => String(j.workflowId || j.productionTicketId || j.orderNumber))); const createdWorkflow = workflow.items.filter((i: Store) => canCreatePlannerJob(i) && !existing.has(String(i.id))).map(jobFromWorkflow); const createdTickets = tickets.filter((ticket: Store) => ticket.artworkStatus && !existing.has(`ticket-${ticket.id || ticket.orderNumber}`) && !existing.has(String(ticket.id || ticket.orderNumber))).map(jobFromTicket); const created = [...createdWorkflow, ...createdTickets]; const actions = created.map((job: Store) => ({ id: makeId('planner-action'), action: job.source === 'production-job-tickets' ? 'sync-proofing-ticket' : 'sync-workflow', jobId: job.id, workflowId: job.workflowId, orderId: job.orderId, at: nowIso() })).concat(planner.actions).slice(0, 400); const result = { ...enrich(mergeJobsBySource([...created, ...planner.jobs]), planner.lanes, actions, planner.shifts, planner.downtime, planner.liveEvents), created: created.length, workflowSummary: workflow.summary, ticketSummary: { total: tickets.length, blocked: createdTickets.filter((job) => job.productionBlocked).length, released: createdTickets.filter((job) => !job.productionBlocked).length } }; if (created.length) await savePlannerStore(request, result); return result; }
function nextStage(stage: PlannerStage): PlannerStage { if (stage === 'queued') return 'prepress'; if (stage === 'prepress') return 'print'; if (stage === 'print') return 'finish'; if (stage === 'finish') return 'dispatch'; if (stage === 'dispatch') return 'completed'; return stage; }
export async function updatePlannerJob(request: Request, input: Store) { const planner = await readPlannerStore(request); const id = String(input.jobId || input.id || input.orderId || '').trim(); const action = String(input.action || '').trim(); if (!id && !['auto-schedule', 'set-shifts', 'add-downtime', 'clear-downtime', 'optimise-batches'].includes(action)) throw new Error('Planner job id or order id is required.'); if (!action) throw new Error('Planner action is required.');
  if (action === 'set-shifts') { const shifts = Array.isArray(input.shifts) ? input.shifts : planner.shifts; const result = enrich(planner.jobs, planner.lanes, [{ id: makeId('planner-action'), action, at: nowIso() }, ...planner.actions].slice(0, 400), shifts, planner.downtime, planner.liveEvents); await savePlannerStore(request, result); return { job: null, ...result }; }
  if (action === 'add-downtime') { const downtime = [{ id: makeId('downtime'), laneId: input.laneId, minutes: asNumber(input.minutes, 30), reason: input.reason || 'Manual downtime', active: true, createdAt: nowIso() }, ...planner.downtime]; const result = enrich(planner.jobs, planner.lanes, [{ id: makeId('planner-action'), action, laneId: input.laneId, at: nowIso() }, ...planner.actions].slice(0, 400), planner.shifts, downtime, planner.liveEvents); await savePlannerStore(request, result); return { job: null, ...result }; }
  if (action === 'clear-downtime') { const downtime = input.laneId ? planner.downtime.filter((d: Store) => String(d.laneId) !== String(input.laneId)) : []; const result = enrich(planner.jobs, planner.lanes, [{ id: makeId('planner-action'), action, laneId: input.laneId || 'all', at: nowIso() }, ...planner.actions].slice(0, 400), planner.shifts, downtime, planner.liveEvents); await savePlannerStore(request, result); return { job: null, ...result }; }
  if (action === 'auto-schedule' || action === 'optimise-batches') { const result = enrich(planner.jobs, planner.lanes, [{ id: makeId('planner-action'), action, at: nowIso() }, ...planner.actions].slice(0, 400), planner.shifts, planner.downtime, planner.liveEvents); await savePlannerStore(request, result); return { job: null, ...result }; }
  const index = planner.jobs.findIndex((job: Store) => String(job.id) === id || String(job.orderId) === id || String(job.orderNumber) === id); if (index < 0) throw new Error('Planner job not found.');
  const job = planner.jobs[index]; if (!schedulable(job) && ['start', 'advance', 'move-stage', 'assign-lane', 'complete', 'resume'].includes(action)) throw new Error(job.blockReason || 'Proof approval and captured payment are required before this job can be scheduled.'); const from = job.stage as PlannerStage; let stage = from; let status = job.status || 'queued-for-production'; let productionBlocked = Boolean(job.productionBlocked); let laneId = job.laneId; let laneName = job.laneName; let priority = input.priority || job.priority; let dueAt = input.dueAt || job.dueAt; let estimatedMinutes = asNumber(input.estimatedMinutes, asNumber(job.estimatedMinutes, 20)); let progressPercent = asNumber(input.progressPercent, asNumber(job.progressPercent, 0)); let liveStatus = job.liveStatus || 'waiting';
  if (action === 'start' || action === 'advance') { stage = nextStage(from); status = stage === 'completed' ? 'completed' : `in-${stage}`; liveStatus = stage === 'completed' ? 'done' : 'running'; progressPercent = stage === 'completed' ? 100 : Math.max(progressPercent, 10); }
  if (action === 'move-stage') { stage = String(input.stage || from) as PlannerStage; status = `moved-to-${stage}`; productionBlocked = stage === 'blocked'; liveStatus = productionBlocked ? 'blocked' : ['prepress', 'print', 'finish', 'dispatch'].includes(stage) ? 'running' : 'waiting'; }
  if (action === 'resize-duration') { estimatedMinutes = Math.max(5, asNumber(input.estimatedMinutes, estimatedMinutes)); status = 'duration-updated'; }
  if (action === 'hold') { stage = 'blocked'; status = 'on-hold'; productionBlocked = true; liveStatus = 'blocked'; }
  if (action === 'resume') { stage = 'queued'; status = 'queued-for-production'; productionBlocked = false; liveStatus = 'waiting'; }
  if (action === 'complete') { stage = 'completed'; status = 'completed'; productionBlocked = false; liveStatus = 'done'; progressPercent = 100; }
  if (action === 'set-priority') { priority = String(input.priority || 'standard'); status = `priority-${priority}`; }
  if (action === 'set-due-date') { dueAt = String(input.dueAt || dueAt || dueDateFor(job)); status = 'due-date-updated'; }
  if (action === 'live-status') { liveStatus = String(input.liveStatus || liveStatus); progressPercent = asNumber(input.progressPercent, progressPercent); status = `live-${liveStatus}`; }
  if (action === 'assign-lane' || input.laneId) { const lane = planner.lanes.find((e: Store) => String(e.id) === String(input.laneId)); if (lane) { laneId = lane.id; laneName = lane.name; status = action === 'assign-lane' ? 'lane-assigned' : status; } }
  const updatedAt = nowIso(); const updated = { ...job, stage, status, laneId, laneName, priority, dueAt, estimatedMinutes, progressPercent, liveStatus, productionBlocked, updatedAt, history: [{ at: updatedAt, action, from, to: stage, note: input.note || null }, ...(Array.isArray(job.history) ? job.history : [])].slice(0, 100) };
  const jobs = [...planner.jobs]; jobs[index] = updated; const liveEvents = action === 'live-status' || ['start', 'hold', 'resume', 'complete'].includes(action) ? [{ id: makeId('live-event'), jobId: updated.id, orderNumber: updated.orderNumber, liveStatus, progressPercent, at: updatedAt }, ...planner.liveEvents].slice(0, 300) : planner.liveEvents; const actions = [{ id: makeId('planner-action'), action, jobId: updated.id, orderId: updated.orderId, from, to: stage, at: updatedAt, note: input.note || null }, ...planner.actions].slice(0, 400); const result = enrich(jobs, planner.lanes, actions, planner.shifts, planner.downtime, liveEvents); await savePlannerStore(request, result);
  if (action === 'start' && from === 'queued') await transitionWorkflowItem(request, { workflowId: updated.workflowId, action: 'release-to-production', note: 'Planner job started.' }).catch(() => null);
  return { job: updated, ...result };
}
