import { platformPrisma } from '@/core/db/platform-prisma';
import { requireTenantSession } from '@/core/auth/session-guard.service';

const DOMAIN_RESOURCE = 'store-domain-bindings';
const STORE_RESOURCE = 'store-channels';
function cleanDomain(value: unknown) { return String(value || '').trim().toLowerCase().replace(/^https?:\/\//, '').replace(/\/.*$/, '').replace(/:\d+$/, ''); }
function slug(value: unknown, fallback = 'default-store') { return String(value || fallback).toLowerCase().replace(/[^a-z0-9]+/g, '-').replace(/(^-|-$)/g, '') || fallback; }
function now() { return new Date().toISOString(); }
async function ensureTable() { await platformPrisma.$executeRawUnsafe(`CREATE TABLE IF NOT EXISTS "CoreCatalogRecord" ("id" TEXT PRIMARY KEY,"tenantId" TEXT NOT NULL,"resource" TEXT NOT NULL,"slug" TEXT NOT NULL,"name" TEXT NOT NULL,"description" TEXT NOT NULL DEFAULT '',"metadataJson" JSONB,"createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,"updatedAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP);`); await platformPrisma.$executeRawUnsafe('CREATE UNIQUE INDEX IF NOT EXISTS "CoreCatalogRecord_tenant_resource_slug_uq" ON "CoreCatalogRecord"("tenantId","resource","slug")'); }
function mapDomain(row: any) { const meta = row?.metadataJson || {}; return { id: row?.id || `domain-${meta.domain}`, domain: meta.domain || row?.slug || '', tenantId: row?.tenantId || meta.tenantId || '', storeSlug: meta.storeSlug || meta.channelSlug || 'default-store', channelSlug: meta.channelSlug || meta.storeSlug || 'default-store', status: meta.status || 'pending-dns', isPrimary: Boolean(meta.isPrimary), dnsTarget: meta.dnsTarget || process.env.STOREFRONT_CNAME_TARGET || process.env.NEXT_PUBLIC_APP_HOST || '', verificationToken: meta.verificationToken || '', verifiedAt: meta.verifiedAt || '', createdAt: meta.createdAt || row?.createdAt || '', updatedAt: meta.updatedAt || row?.updatedAt || '' }; }
async function storeExists(tenantId: string, storeSlug: string) { const rows = await platformPrisma.$queryRawUnsafe<any[]>('SELECT slug FROM "CoreCatalogRecord" WHERE "tenantId"=$1 AND resource=$2 AND slug=$3 LIMIT 1', tenantId, STORE_RESOURCE, storeSlug); return Boolean(rows[0]); }
export async function listStoreDomainBindings() { const session = await requireTenantSession(); await ensureTable(); const tenantId = String(session.tenantId || ''); const rows = await platformPrisma.$queryRawUnsafe<any[]>('SELECT id,"tenantId",slug,name,description,"metadataJson","createdAt","updatedAt" FROM "CoreCatalogRecord" WHERE "tenantId"=$1 AND resource=$2 ORDER BY "updatedAt" DESC', tenantId, DOMAIN_RESOURCE); return { items: rows.map(mapDomain) }; }
export async function saveStoreDomainBinding(input: Record<string, any>) { const session = await requireTenantSession(); await ensureTable(); const tenantId = String(session.tenantId || ''); const domain = cleanDomain(input.domain); if (!domain) throw new Error('Domain is required.'); const storeSlug = slug(input.storeSlug || input.channelSlug || 'default-store'); const exists = await storeExists(tenantId, storeSlug); if (!exists) throw new Error(`Store/channel ${storeSlug} does not exist for this tenant yet.`); const verificationToken = String(input.verificationToken || `print-domain-${tenantId}-${storeSlug}`).replace(/[^a-zA-Z0-9-]/g, '-').slice(0, 120); const meta = { domain, tenantId, storeSlug, channelSlug: storeSlug, status: input.status === 'verified' ? 'verified' : 'pending-dns', isPrimary: Boolean(input.isPrimary), dnsTarget: String(input.dnsTarget || process.env.STOREFRONT_CNAME_TARGET || process.env.NEXT_PUBLIC_APP_HOST || ''), verificationToken, verifiedAt: input.status === 'verified' ? now() : '', createdAt: input.createdAt || now(), updatedAt: now() };
  await platformPrisma.$executeRawUnsafe('INSERT INTO "CoreCatalogRecord" (id,"tenantId",resource,slug,name,description,"metadataJson","updatedAt") VALUES ($1,$2,$3,$4,$5,$6,$7::jsonb,NOW()) ON CONFLICT ("tenantId",resource,slug) DO UPDATE SET name=EXCLUDED.name,description=EXCLUDED.description,"metadataJson"=EXCLUDED."metadataJson","updatedAt"=NOW()', `store-domain-${tenantId}-${domain}`, tenantId, DOMAIN_RESOURCE, domain, domain, `Domain binding for ${storeSlug}`, JSON.stringify(meta));
  await platformPrisma.$executeRawUnsafe('UPDATE "CoreCatalogRecord" SET "metadataJson" = coalesce("metadataJson", \'{}\'::jsonb) || $1::jsonb, "updatedAt"=NOW() WHERE "tenantId"=$2 AND resource=$3 AND slug=$4', JSON.stringify({ domain, domainStatus: meta.status, domainMode: 'custom-domain' }), tenantId, STORE_RESOURCE, storeSlug);
  return meta;
}
export async function deleteStoreDomainBinding(domainInput: string) { const session = await requireTenantSession(); await ensureTable(); const tenantId = String(session.tenantId || ''); const domain = cleanDomain(domainInput); await platformPrisma.$executeRawUnsafe('DELETE FROM "CoreCatalogRecord" WHERE "tenantId"=$1 AND resource=$2 AND slug=$3', tenantId, DOMAIN_RESOURCE, domain); return { domain, deleted: true }; }
export async function resolveStoreDomain(hostInput: string) { await ensureTable(); const host = cleanDomain(hostInput).replace(/^www\./, ''); const rows = await platformPrisma.$queryRawUnsafe<any[]>('SELECT id,"tenantId",slug,name,description,"metadataJson","createdAt","updatedAt" FROM "CoreCatalogRecord" WHERE resource=$1 AND (slug=$2 OR slug=$3 OR lower("metadataJson"::text) LIKE lower($4)) ORDER BY "updatedAt" DESC LIMIT 1', DOMAIN_RESOURCE, host, `www.${host}`, `%"domain":"${host}"%`); const binding = rows[0] ? mapDomain(rows[0]) : null; if (!binding) return { found: false, host, tenantId: '', storeSlug: '', channelSlug: '', binding: null }; return { found: true, host, tenantId: binding.tenantId, storeSlug: binding.storeSlug, channelSlug: binding.channelSlug, binding }; }
