import crypto from 'crypto';
import { platformPrisma } from '@/core/db/platform-prisma';
import { requireTenantSession } from '@/core/auth/session-guard.service';
import { assertTenantCanCreateStore } from '@/core/platform/store-allowance.service';
import { reservePlatformSubdomainForStore } from '@/core/storefront/store-domain-bindings.service';

const RESOURCE = 'store-channels';
function slugify(value: string) { return String(value || '').toLowerCase().replace(/[^a-z0-9]+/g, '-').replace(/(^-|-$)/g, '').slice(0, 80) || `channel-${Date.now()}`; }
function status(value: unknown) { return value === 'inactive' ? 'inactive' : 'active'; }
function tenantIdFromSession(session: any) { return String(session.tenantId || 'holo-print'); }
function cleanDomain(value: unknown) { return String(value || '').trim().toLowerCase().replace(/^https?:\/\//, '').replace(/\/$/, ''); }
async function ensureTable() { await platformPrisma.$executeRawUnsafe(`CREATE TABLE IF NOT EXISTS "CoreCatalogRecord" ("id" TEXT PRIMARY KEY,"tenantId" TEXT NOT NULL,"resource" TEXT NOT NULL,"slug" TEXT NOT NULL,"name" TEXT NOT NULL,"description" TEXT NOT NULL DEFAULT '',"metadataJson" JSONB,"createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,"updatedAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP);`); await platformPrisma.$executeRawUnsafe('CREATE UNIQUE INDEX IF NOT EXISTS "CoreCatalogRecord_tenant_resource_slug_uq" ON "CoreCatalogRecord"("tenantId","resource","slug")'); }
function mapRow(row: any) { const meta = row.metadataJson || {}; return { id: String(row.id), name: String(row.name || meta.name || ''), slug: String(row.slug || meta.slug || ''), domain: String(meta.domain || meta.platformSubdomain || ''), platformSubdomain: String(meta.platformSubdomain || ''), status: status(meta.status), themeId: String(meta.themeId || meta.themeKey || 'base'), currency: String(meta.currency || 'GBP'), locale: String(meta.locale || 'en-GB'), isHeadless: Boolean(meta.isHeadless || meta.storeType === 'external' || meta.channelType === 'external-api'), createdAt: row.createdAt instanceof Date ? row.createdAt.toISOString() : String(row.createdAt || ''), publicApiKey: String(meta.publicApiKey || ''), privateApiKey: '', domainStatus: String(meta.domainStatus || ''), hostedThemeEnabled: meta.hostedThemeEnabled !== false, externalApiEnabled: Boolean(meta.externalApiEnabled) }; }
export async function listStoreChannels(search = '', filterStatus?: string) { const session = await requireTenantSession(); await ensureTable(); const tenantId = tenantIdFromSession(session); const q = search.trim(); const rows = await platformPrisma.$queryRawUnsafe<any[]>('SELECT id,slug,name,description,"metadataJson","createdAt","updatedAt" FROM "CoreCatalogRecord" WHERE "tenantId"=$1 AND resource=$2 AND ($3=\'\' OR lower(name || \' \' || slug || \' \' || description || \' \' || coalesce("metadataJson"::text,\'\')) LIKE lower($4)) ORDER BY "updatedAt" DESC', tenantId, RESOURCE, q, `%${q}%`); const items = rows.map(mapRow).filter((item) => !filterStatus || item.status === filterStatus); return { items, pagination: { page: 1, perPage: Math.max(1, items.length), total: items.length, totalPages: 1 } }; }
export async function saveStoreChannel(input: Record<string, unknown>) { const session = await requireTenantSession(); await ensureTable(); const tenantId = tenantIdFromSession(session); const id = String(input.id || `channel-${crypto.randomUUID()}`); const slug = slugify(String(input.slug || input.name || id)); await assertTenantCanCreateStore(tenantId, slug); const name = String(input.name || slug); const customDomain = cleanDomain(input.domain); const isHeadless = Boolean(input.isHeadless); const themeId = String(input.themeId || 'base'); const platformDomain = customDomain ? null : await reservePlatformSubdomainForStore(tenantId, slug, name); const domain = customDomain || platformDomain?.domain || ''; const meta = { id, tenantId, name, slug, domain, platformSubdomain: platformDomain?.domain || '', platformRootDomain: platformDomain?.rootDomain || '', domainMode: customDomain ? 'custom-domain' : 'platform-subdomain', domainStatus: customDomain ? 'pending-verification' : platformDomain?.status || 'platform-subdomain', status: status(input.status), themeId, themeKey: themeId, currency: String(input.currency || 'GBP'), locale: String(input.locale || 'en-GB'), isHeadless, storeType: isHeadless ? 'external' : 'hosted', channelType: isHeadless ? 'external-api' : 'hosted', externalApiEnabled: isHeadless, hostedThemeEnabled: !isHeadless, paymentProvider: 'tenant_stripe_connect_pending' }; await platformPrisma.$executeRawUnsafe('INSERT INTO "CoreCatalogRecord" (id,"tenantId",resource,slug,name,description,"metadataJson","updatedAt") VALUES ($1,$2,$3,$4,$5,$6,$7::jsonb,NOW()) ON CONFLICT ("tenantId",resource,slug) DO UPDATE SET name=EXCLUDED.name,description=EXCLUDED.description,"metadataJson"=EXCLUDED."metadataJson","updatedAt"=NOW()', id, tenantId, RESOURCE, slug, name, isHeadless ? 'External API storefront channel' : 'Hosted storefront channel', JSON.stringify(meta)); return mapRow({ id, slug, name, description: '', metadataJson: meta, createdAt: new Date() }); }
