'use client';

import { AnimatePresence, motion } from 'framer-motion';
import { ChevronRight, Search, X } from 'lucide-react';
import { BRAND } from './theme-helpers';

export type SearchSuggestion = { id: string; type: 'product' | 'category'; title: string; description: string; href: string; sku?: string; price?: string; categoryTitle?: string };
export default function ChromeSearchModal({ open, searchTerm, setSearchTerm, suggestions, loading, searchUrl, onClose }: { open: boolean; searchTerm: string; setSearchTerm: (value: string) => void; suggestions: SearchSuggestion[]; loading: boolean; searchUrl: string; onClose: () => void }) {
  return <AnimatePresence>{open ? <motion.div initial={{ opacity: 0 }} animate={{ opacity: 1 }} exit={{ opacity: 0 }} transition={{ duration: 0.18 }} className="fixed inset-0 z-[70] overflow-y-auto bg-[rgba(16,18,24,0.45)] px-4 py-6 md:px-10"><div className="mx-auto flex max-w-[1080px] items-start justify-end"><button onClick={onClose} className="mt-3 rounded-full bg-white p-3 shadow-[0_12px_28px_rgba(0,0,0,0.10)]"><X className="h-5 w-5" style={{ color: BRAND.ink }} /></button></div><div className="mx-auto mt-4 max-w-[1080px] rounded-[28px] border bg-white p-6 shadow-[0_30px_90px_rgba(0,0,0,0.20)] md:p-8" style={{ borderColor: BRAND.line }}><div className="text-center"><div className="text-[10px] font-bold uppercase tracking-[0.18em]" style={{ color: BRAND.accent }}>Search catalogue</div><div className="mt-3 text-[34px] font-black tracking-[-0.045em]" style={{ color: BRAND.ink }}>Find products, categories and SKUs</div></div><form action={searchUrl.split('?')[0]} method="get" className="relative mx-auto mt-6 max-w-[760px]"><Search className="absolute left-4 top-1/2 h-5 w-5 -translate-y-1/2" style={{ color: BRAND.muted }} /><input name="q" value={searchTerm} onChange={(e) => setSearchTerm(e.target.value)} className="h-14 w-full rounded-[18px] border bg-white pl-12 pr-28 text-[14px] outline-none" placeholder="Search business cards, flyers, SKU..." style={{ borderColor: BRAND.line }} /><button className="absolute right-2 top-2 h-10 rounded-xl px-4 text-xs font-black text-white" style={{ backgroundColor: BRAND.primary }}>View all</button></form><div className="mt-8 grid gap-4 md:grid-cols-2">{suggestions.map((item) => <a key={item.id} href={item.href} onClick={onClose} className="group flex items-center justify-between rounded-[18px] border bg-[#FBFCFF] px-5 py-4 text-left no-underline shadow-[0_10px_24px_rgba(0,0,0,0.03)] transition hover:-translate-y-[1px] hover:shadow-[0_16px_32px_rgba(0,0,0,0.06)]" style={{ borderColor: BRAND.line }}><div><div className="text-[10px] font-black uppercase tracking-[0.13em]" style={{ color: BRAND.primary }}>{item.type === 'category' ? 'Category' : item.categoryTitle || 'Product'}{item.sku ? ` · SKU ${item.sku}` : ''}</div><div className="mt-1 text-[14px] font-black tracking-[-0.02em]" style={{ color: BRAND.ink }}>{item.title}</div><div className="mt-1 line-clamp-1 text-[12px]" style={{ color: BRAND.muted }}>{item.price || item.description || 'Browse catalogue'}</div></div><ChevronRight className="h-5 w-5" style={{ color: BRAND.primary }} /></a>)}</div>{loading ? <div className="mt-6 text-center text-xs" style={{ color: BRAND.muted }}>Searching published catalogue…</div> : !suggestions.length ? <div className="mt-6 text-center text-xs" style={{ color: BRAND.muted }}>{searchTerm ? 'No matching products yet. Use View all for filters.' : 'Start typing to search the full catalogue.'}</div> : null}</div></motion.div> : null}</AnimatePresence>;
}
