import Link from 'next/link';
import { BRAND, storeHref } from './theme-helpers';

function Shell({ children }: { children: React.ReactNode }) {
  return <div className="mx-auto w-full max-w-[1360px] px-4 sm:px-6 lg:px-8">{children}</div>;
}

function FooterCol({ title, items, storeBase }: { title: string; items: [string, string][]; storeBase: string }) {
  return <div><div className="mb-3 text-[12px] font-bold uppercase tracking-[0.16em]" style={{ color: BRAND.ink }}>{title}</div><div className="grid gap-2">{items.map(([label, path]) => <Link key={label} href={storeHref(storeBase, path)} className="text-left text-[12px] no-underline" style={{ color: BRAND.muted }}>{label}</Link>)}</div></div>;
}

export default function ChromeFooter({ storeBase }: { storeBase: string }) {
  const stats = [['Business printing','20+'],['Event signage','12+'],['Labels & packaging','18+'],['Custom quote support','1:1']];
  return <footer className="mt-8 border-t bg-white" style={{ borderColor: BRAND.line }}><div className="border-b py-3" style={{ borderColor: BRAND.line, backgroundColor: BRAND.primary }}><Shell><div className="flex flex-col items-center justify-between gap-3 text-[12px] font-semibold text-white md:flex-row"><span>Get the very best print solutions for your business, events and brand campaigns.</span><div className="flex gap-2"><input className="h-9 w-[250px] rounded-full border-0 bg-white px-4 text-[12px] text-black outline-none" placeholder="Email address" /><button className="rounded-full bg-black px-4 text-[12px] font-bold text-white">Subscribe</button></div></div></Shell></div><Shell><div className="grid gap-3 py-5 md:grid-cols-4">{stats.map(([item,count]) => <div key={item} className="rounded-[18px] border px-4 py-3" style={{ borderColor: BRAND.line, color: BRAND.muted }}><div className="text-[10px] font-bold uppercase tracking-[0.14em]">{item}</div><div className="mt-1 text-[16px] font-black" style={{ color: BRAND.ink }}>{count}</div></div>)}</div><div className="grid gap-8 py-10 md:grid-cols-[1.25fr_0.8fr_0.8fr_0.8fr_0.8fr]"><div><Link href={storeBase} className="flex items-center gap-0.5 no-underline"><span className="text-[50px] font-black tracking-[-0.055em]" style={{ color: BRAND.primary }}>HOLO</span><span className="text-[50px] font-black tracking-[-0.055em]" style={{ color: BRAND.ink }}>PRINT</span></Link><p className="mt-4 max-w-[360px] text-[12px] leading-7" style={{ color: BRAND.muted }}>Professional print storefront theme.</p></div><FooterCol storeBase={storeBase} title="Products" items={[['Business Cards','/business-cards'],['Flyers','/flyers'],['Posters','/posters-large-format-prints'],['Booklets','/booklets']]} /><FooterCol storeBase={storeBase} title="Categories" items={[['Labels','/all-products'],['Stationery','/stationery'],['Signage','/signage'],['Packaging','/all-products']]} /><FooterCol storeBase={storeBase} title="Business" items={[['Bulk pricing','/bespoke-quote'],['Custom quotes','/bespoke-quote'],['Artwork advice','/bespoke-quote'],['Delivery support','/all-products']]} /><FooterCol storeBase={storeBase} title="Support" items={[['All products','/all-products'],['Cart','/cart'],['Contact','/bespoke-quote'],['Quote request','/bespoke-quote']]} /></div><div className="flex flex-col gap-2 border-t py-4 text-[11px] md:flex-row md:items-center md:justify-between" style={{ borderColor: BRAND.line, color: BRAND.muted }}><span>© 2026 HOLO PRINT. All rights reserved.</span><div className="flex gap-4"><Link href={storeHref(storeBase, '/all-products')}>All products</Link><Link href={storeHref(storeBase, '/bespoke-quote')}>Custom quote</Link><Link href={storeHref(storeBase, '/cart')}>Cart</Link></div></div></Shell></footer>;
}
