'use client';

import { AnimatePresence, motion } from 'framer-motion';
import type { NavItem } from './types';
import { BRAND } from './theme-helpers';

export default function ChromeMegaMenu({ openLabel, navItems, onNavigate, onClose }: { openLabel: string | null; navItems: NavItem[]; onNavigate: (path: string) => void; onClose: () => void }) {
  return <AnimatePresence>{openLabel ? <motion.div initial={{ opacity: 0, y: 12 }} animate={{ opacity: 1, y: 0 }} exit={{ opacity: 0, y: 12 }} transition={{ duration: 0.18 }} onMouseLeave={onClose} className="absolute left-0 right-0 top-full hidden xl:block"><div className="mt-2 rounded-[22px] border bg-white p-5 shadow-[0_34px_100px_rgba(0,0,0,0.13)]" style={{ borderColor: BRAND.line }}>{(() => { const item = navItems.find((entry) => entry.label === openLabel) || navItems[0]; if (!item) return null; return <div className="grid gap-5"><div className="grid grid-cols-[270px_1fr_1fr_1fr] gap-6"><div className="rounded-[20px] border p-4" style={{ borderColor: BRAND.line, background: 'linear-gradient(180deg, #FBFDFE 0%, #F4F9FB 100%)' }}><img src={item.feature.image} alt={item.feature.title} className="h-36 w-full rounded-[12px] object-cover" /><div className="mt-4 text-[18px] font-black tracking-[-0.03em]" style={{ color: BRAND.ink }}>{item.feature.title}</div><p className="mt-2 text-[12px] leading-6" style={{ color: BRAND.muted }}>{item.feature.body}</p><button onClick={() => onNavigate(item.path)} className="mt-4 text-[12px] font-bold" style={{ color: BRAND.primary }}>{item.feature.cta}</button></div>{item.columns.map((column) => <div key={column.title}><div className="mb-2 text-[10px] font-bold uppercase tracking-[0.18em]" style={{ color: BRAND.primary }}>{column.title}</div><div className="grid gap-1">{column.links.map(([label, path]) => <button key={`${label}-${path}`} onClick={() => { onNavigate(path); onClose(); }} className="rounded-xl px-3 py-2 text-left text-[12px] font-medium hover:bg-[#F6F7F8]" style={{ color: BRAND.ink }}>{label}</button>)}</div></div>)}</div><div className="grid grid-cols-4 gap-3 border-t pt-4" style={{ borderColor: BRAND.line }}>{['Fast turnaround', 'Premium stock', 'Bulk pricing', 'Artwork support'].map((itemText) => <div key={itemText} className="rounded-[16px] border px-4 py-3 text-[11px] font-semibold" style={{ borderColor: BRAND.line, color: BRAND.muted }}>{itemText}</div>)}</div></div>; })()}</div></motion.div> : null}</AnimatePresence>;
}
