'use client';

import { AnimatePresence, motion } from 'framer-motion';
import { ChevronRight, Search, X } from 'lucide-react';
import { BRAND } from './theme-helpers';

export default function ChromeSearchModal({ open, searchTerm, setSearchTerm, suggestions, onClose, onNavigate }: { open: boolean; searchTerm: string; setSearchTerm: (value: string) => void; suggestions: [string, string][]; onClose: () => void; onNavigate: (path: string) => void }) {
  return <AnimatePresence>{open ? <motion.div initial={{ opacity: 0 }} animate={{ opacity: 1 }} exit={{ opacity: 0 }} transition={{ duration: 0.18 }} className="fixed inset-0 z-[70] bg-[rgba(16,18,24,0.45)] px-4 py-6 md:px-10"><div className="mx-auto flex max-w-[1080px] items-start justify-end"><button onClick={onClose} className="mt-3 rounded-full bg-white p-3 shadow-[0_12px_28px_rgba(0,0,0,0.10)]"><X className="h-5 w-5" style={{ color: BRAND.ink }} /></button></div><div className="mx-auto mt-4 max-w-[1080px] rounded-[28px] border bg-white p-6 shadow-[0_30px_90px_rgba(0,0,0,0.20)] md:p-8" style={{ borderColor: BRAND.line }}><div className="text-center"><div className="text-[10px] font-bold uppercase tracking-[0.18em]" style={{ color: BRAND.accent }}>Search HOLO Print</div><div className="mt-3 text-[34px] font-black tracking-[-0.045em]" style={{ color: BRAND.ink }}>Find the right print product faster</div></div><div className="relative mx-auto mt-6 max-w-[760px]"><Search className="absolute left-4 top-1/2 h-5 w-5 -translate-y-1/2" style={{ color: BRAND.muted }} /><input value={searchTerm} onChange={(e) => setSearchTerm(e.target.value)} className="h-14 w-full rounded-[18px] border bg-white pl-12 pr-4 text-[14px] outline-none" placeholder="Search business cards, flyers, posters, booklets..." style={{ borderColor: BRAND.line }} /></div><div className="mt-8 grid gap-4 md:grid-cols-2">{suggestions.filter(([label]) => label.toLowerCase().includes(searchTerm.toLowerCase())).slice(0, 12).map(([label, path], index) => <button key={`${label}-${path}`} onClick={() => { onNavigate(path); onClose(); }} className="group flex items-center justify-between rounded-[18px] border bg-[#FBFCFF] px-5 py-4 text-left shadow-[0_10px_24px_rgba(0,0,0,0.03)] transition hover:-translate-y-[1px] hover:shadow-[0_16px_32px_rgba(0,0,0,0.06)]" style={{ borderColor: BRAND.line }}><div><div className="text-[14px] font-black tracking-[-0.02em]" style={{ color: BRAND.ink }}>{label}</div><div className="mt-1 text-[12px]" style={{ color: BRAND.muted }}>{index < 4 ? 'Admin connected product/category' : 'Browse products and options'}</div></div><ChevronRight className="h-5 w-5" style={{ color: BRAND.primary }} /></button>)}</div></div></motion.div> : null}</AnimatePresence>;
}
