import { MapPin, Store, Truck } from 'lucide-react';
import StorefrontChrome from './StorefrontChrome';
import type { NavItem } from './types';
import type { CollectionPoint } from './collection-points';
import { BRAND } from './theme-helpers';
import { Shell } from './HomePrimitives';

export default function CollectionPointsPage({ storeBase, navItems, points }: { storeBase: string; navItems: NavItem[]; points: CollectionPoint[] }) {
  return <StorefrontChrome currentPath="/collection-points" navItems={navItems} storeBase={storeBase}><section className="border-b" style={{ borderColor: BRAND.line, background: 'linear-gradient(135deg, rgba(24,167,208,0.10) 0%, rgba(123,63,228,0.06) 58%, rgba(255,200,61,0.08) 100%)' }}><Shell className="py-10 lg:py-14"><div className="grid gap-8 lg:grid-cols-[0.9fr_1.1fr] lg:items-center"><div><div className="inline-flex rounded-full bg-white/80 px-4 py-2 text-[10px] font-black uppercase tracking-[0.18em]" style={{ color: BRAND.primary }}>Select store</div><h1 className="mt-5 max-w-[700px] text-[46px] font-black leading-[0.95] tracking-[-0.065em] sm:text-[62px]" style={{ color: BRAND.ink }}>Choose your collection point.</h1><p className="mt-5 max-w-[620px] text-[14px] leading-7" style={{ color: BRAND.muted }}>This page is prepared for tenant store locations and collection points. Customers can pick where they want to collect once checkout is connected.</p></div><div className="rounded-[30px] border bg-white p-6 shadow-[0_24px_70px_rgba(0,0,0,0.08)]" style={{ borderColor: BRAND.line }}><MapPin className="h-10 w-10" style={{ color: BRAND.primary }} /><div className="mt-4 text-[26px] font-black tracking-[-0.05em]" style={{ color: BRAND.ink }}>Local collection support</div><p className="mt-2 text-[13px] leading-7" style={{ color: BRAND.muted }}>Use tenant records to show real branches, partner shops and collection counters.</p></div></div></Shell></section><section className="py-8"><Shell><div className="grid gap-5 md:grid-cols-2 xl:grid-cols-3">{points.map((point) => <div key={point.slug} className="rounded-[24px] border bg-white p-6 shadow-[0_16px_36px_rgba(0,0,0,0.05)]" style={{ borderColor: BRAND.line }}><div className="flex items-start justify-between gap-4"><div className="grid h-12 w-12 place-items-center rounded-[18px]" style={{ backgroundColor: 'rgba(24,167,208,0.10)', color: BRAND.primary }}><Store className="h-6 w-6" /></div><span className="rounded-full border px-3 py-1 text-[11px] font-black" style={{ borderColor: BRAND.line, color: BRAND.primary }}>{point.status}</span></div><div className="mt-5 text-[20px] font-black tracking-[-0.04em]" style={{ color: BRAND.ink }}>{point.name}</div><p className="mt-2 text-[13px] leading-6" style={{ color: BRAND.muted }}>{point.address}</p><p className="mt-3 text-[12px] leading-6" style={{ color: BRAND.muted }}>{point.note}</p><button className="mt-5 inline-flex items-center gap-2 rounded-full px-5 py-3 text-[12px] font-black text-white" style={{ backgroundColor: BRAND.primary }}><Truck className="h-4 w-4" />Use this collection point</button></div>)}</div></Shell></section></StorefrontChrome>;
}
