import StorefrontChrome from './StorefrontChrome';
import type { NavItem } from './types';
import type { ThemeProductCard } from './catalog-adapter';
import { BRAND } from './theme-helpers';
import { Shell } from './HomePrimitives';

export default function ProductPage({ storeBase, navItems, slug, category, products = [] }: { storeBase: string; navItems: NavItem[]; slug: string; category: string; products?: ThemeProductCard[] }) {
  const product = products.find((item) => item.slug === slug && item.category === category);

  if (!product) {
    return <StorefrontChrome currentPath={`/${category}/${slug}`} navItems={navItems} storeBase={storeBase}><section className="py-10"><Shell><div className="rounded-[32px] border bg-white p-8 shadow-sm" style={{ borderColor: BRAND.line }}><div className="text-[11px] font-black uppercase tracking-[0.18em]" style={{ color: BRAND.primary }}>Unavailable</div><h1 className="mt-4 text-[38px] font-black tracking-[-0.055em]" style={{ color: BRAND.ink }}>Product not available</h1><p className="mt-3 max-w-[680px] text-sm leading-7" style={{ color: BRAND.muted }}>This product is not currently published for this store.</p></div></Shell></section></StorefrontChrome>;
  }

  return <StorefrontChrome currentPath={`/${category}/${slug}`} navItems={navItems} storeBase={storeBase}><section className="py-6"><Shell><div className="rounded-[32px] border bg-white p-8 shadow-sm" style={{ borderColor: BRAND.line }}><div className="text-[11px] font-black uppercase tracking-[0.18em]" style={{ color: BRAND.primary }}>Product</div><h1 className="mt-4 text-[38px] font-black tracking-[-0.055em]" style={{ color: BRAND.ink }}>{product.title}</h1>{product.text ? <p className="mt-3 max-w-[680px] text-sm leading-7" style={{ color: BRAND.muted }}>{product.text}</p> : null}</div></Shell></section><section className="pb-10"><Shell><div className="grid gap-6 lg:grid-cols-[1.05fr_0.95fr]"><div className="rounded-[26px] border bg-white p-5 shadow-[0_18px_48px_rgba(0,0,0,0.05)]" style={{ borderColor: BRAND.line }}>{product.image ? <img src={product.image} alt={product.title} className="h-[360px] w-full rounded-[18px] object-cover" /> : null}<div className="mt-5 text-[24px] font-black tracking-[-0.04em]" style={{ color: BRAND.ink }}>{product.title}</div></div><div className="rounded-[26px] border bg-white p-6 shadow-[0_18px_48px_rgba(0,0,0,0.05)]" style={{ borderColor: BRAND.line }}><div className="text-[22px] font-black tracking-[-0.04em]" style={{ color: BRAND.ink }}>Quote and order setup</div><div className="mt-2 text-[13px] font-bold" style={{ color: BRAND.primary }}>{product.price}</div><div className="mt-4 rounded-[18px] border p-4" style={{ borderColor: BRAND.line }}><div className="text-[12px] font-black" style={{ color: BRAND.ink }}>Real product data only</div><div className="mt-2 text-[12px]" style={{ color: BRAND.muted }}>Customer options will appear here only when they are configured in the SaaS product setup.</div></div><button className="mt-5 w-full rounded-full px-5 py-3 text-[12px] font-black text-white" style={{ backgroundColor: BRAND.primary }}>Request quote</button></div></div></Shell></section></StorefrontChrome>;
}
