'use client';

import { useEffect, useMemo, useState } from 'react';
import { Filter, Trash2 } from 'lucide-react';
import { Card } from '@/components/ui/card';
import { PageHeader } from '@/components/ui/page-header';
import { Button, PrimaryButton } from '@/components/ui/buttons';
import { Input } from '@/components/forms/input';
import { Select, type SelectOption } from '@/components/forms/select';
import { Toggle } from '@/components/forms/toggle';

type Field = { key: string; label: string; type?: 'text' | 'number' | 'textarea'; placeholder?: string; options?: SelectOption[]; toggle?: boolean };
type RecordItem = { id: string; title: string; subtitle?: string; meta?: string; pinned?: boolean; starred?: boolean; createdAt?: string; [key: string]: string | boolean | undefined };
type QuickTemplate = { label: string; values: Record<string, string | boolean> };
type LiveSyncState = 'local' | 'loading' | 'live' | 'saving' | 'error';
const sortOptions = [{ value: 'recent', label: 'Newest first' }, { value: 'title', label: 'Title A–Z' }, { value: 'status', label: 'Status' }, { value: 'owner', label: 'Owner / Assignee' }];

export function LocalRecordsPage({ storageKey, title, subtitle, createLabel, fields, initialItems, buildCardMeta, buildSubtitle, cardMetaFields, subtitleFields, searchKeys, primaryFilterKey, liveEndpoint, mapLiveItem }: { storageKey: string; title: string; subtitle: string; createLabel: string; fields: Field[]; initialItems: RecordItem[]; buildCardMeta?: (item: RecordItem) => string; buildSubtitle?: (item: RecordItem) => string; cardMetaFields?: string[]; subtitleFields?: string[]; searchKeys?: string[]; primaryFilterKey?: string; quickTemplates?: QuickTemplate[]; liveEndpoint?: string; mapLiveItem?: (row: Record<string, unknown>, index: number) => RecordItem }) {
  const seedItems = useMemo(() => initialItems.map((item, index) => ({ ...item, createdAt: item.createdAt ?? new Date(Date.now() - index * 1000 * 60 * 30).toISOString(), pinned: Boolean(item.pinned), starred: Boolean(item.starred) })), [initialItems]);
  const effectiveLiveEndpoint = liveEndpoint || (storageKey ? `/api/internal/config/${encodeURIComponent(storageKey)}/items` : undefined);
  const [items, setItems] = useState<RecordItem[]>(seedItems);
  const [selectedId, setSelectedId] = useState<string>(seedItems[0]?.id ?? '');
  const [query, setQuery] = useState('');
  const [activeFilter, setActiveFilter] = useState('all');
  const [sortBy, setSortBy] = useState('recent');
  const [attentionOnly, setAttentionOnly] = useState(false);
  const [liveSync, setLiveSync] = useState<LiveSyncState>(effectiveLiveEndpoint ? 'loading' : 'local');
  const [liveMessage, setLiveMessage] = useState(effectiveLiveEndpoint ? 'Connecting to internal API...' : 'Local-only workspace.');
  async function persist(next: RecordItem[]) { setItems(next); if (!effectiveLiveEndpoint) { if (typeof window !== 'undefined') window.localStorage.setItem(storageKey, JSON.stringify(next)); return; } setLiveSync('saving'); try { const res = await fetch(effectiveLiveEndpoint, { method: 'POST', headers: { 'Content-Type': 'application/json' }, body: JSON.stringify({ title, description: subtitle, items: next }) }); const payload = await res.json().catch(() => ({})); if (!res.ok || payload?.ok === false) throw new Error(payload?.error || 'Internal API save failed.'); setLiveSync('live'); setLiveMessage('Saved to internal database.'); } catch (error) { setLiveSync('error'); setLiveMessage(error instanceof Error ? error.message : 'Could not save to internal database.'); } }
  useEffect(() => { let active = true; if (!effectiveLiveEndpoint || typeof window === 'undefined') return; const loadLive = async () => { try { const res = await fetch(effectiveLiveEndpoint, { cache: 'no-store' }); const payload = await res.json().catch(() => null); if (!res.ok || !payload?.ok) { setLiveSync('error'); setLiveMessage(payload?.error || 'Internal API did not return a successful response.'); return; } const raw = payload?.data?.metadataJson?.items || payload?.data?.items || payload?.data || payload?.payload?.data || payload?.payload || []; if (!Array.isArray(raw)) { setLiveSync('error'); setLiveMessage('Internal API returned an unexpected data shape.'); return; } if (!raw.length) { setLiveSync('live'); setLiveMessage('Internal API connected. No database records found yet.'); return; } const mapped = raw.map((row, index) => mapLiveItem ? mapLiveItem(row as Record<string, unknown>, index) : ({ id: String((row as Record<string, unknown>).id ?? (row as Record<string, unknown>).slug ?? `row-${index + 1}`), title: String((row as Record<string, unknown>).name ?? (row as Record<string, unknown>).title ?? (row as Record<string, unknown>).slug ?? `Record ${index + 1}`), subtitle: String((row as Record<string, unknown>).description ?? ((row as Record<string, unknown>).metadataJson as Record<string, unknown> | undefined)?.subtitle ?? ''), meta: String(((row as Record<string, unknown>).metadataJson as Record<string, unknown> | undefined)?.meta ?? ''), ...(((row as Record<string, unknown>).metadataJson as Record<string, string | boolean> | undefined) ?? {}), createdAt: String((row as Record<string, unknown>).createdAt ?? new Date().toISOString()) })); if (active && mapped.length) { setItems(mapped.map((item) => ({ pinned: false, starred: false, ...item, createdAt: item.createdAt ?? new Date().toISOString() }))); setSelectedId(mapped[0]?.id ?? ''); setLiveSync('live'); setLiveMessage('Connected to internal API and loaded database records.'); } } catch (error) { setLiveSync('error'); setLiveMessage(error instanceof Error ? error.message : 'Could not reach internal API. No database records loaded.'); } }; void loadLive(); return () => { active = false; }; }, [effectiveLiveEndpoint, mapLiveItem]);
  useEffect(() => { if (effectiveLiveEndpoint || typeof window === 'undefined') return; const raw = window.localStorage.getItem(storageKey); if (!raw) return; try { const parsed = JSON.parse(raw) as RecordItem[]; if (Array.isArray(parsed) && parsed.length > 0) { setItems(parsed.map((item) => ({ pinned: false, starred: false, ...item, createdAt: item.createdAt ?? new Date().toISOString() }))); setSelectedId(parsed[0].id); } } catch {} }, [storageKey, effectiveLiveEndpoint]);
  const filterField = fields.find((field) => field.key === primaryFilterKey);
  const filterOptions = useMemo(() => filterField?.options ? filterField.options.map((option) => (typeof option === 'string' ? option : option.value)) : [], [filterField]);
  const filtered = useMemo(() => { const q = query.trim().toLowerCase(); const result = items.filter((item) => { const keys = searchKeys ?? ['title', 'subtitle', 'meta']; const matchesQuery = !q || keys.some((key) => String(item[key] ?? '').toLowerCase().includes(q)); const matchesFilter = activeFilter === 'all' || !primaryFilterKey || String(item[primaryFilterKey] ?? '') === activeFilter; const attentionState = [String(item.priority ?? ''), String(item.type ?? ''), String(item.status ?? '')].join(' ').toLowerCase(); const matchesAttention = !attentionOnly || /(critical|high|warning|security|blocked|due-soon|pending|open)/.test(attentionState); return matchesQuery && matchesFilter && matchesAttention; }); return result.sort((a, b) => { if (Boolean(a.pinned) !== Boolean(b.pinned)) return a.pinned ? -1 : 1; if (sortBy === 'title') return String(a.title).localeCompare(String(b.title)); if (sortBy === 'status') return String(a.status ?? '').localeCompare(String(b.status ?? '')); if (sortBy === 'owner') return String(a.owner ?? a.assignee ?? '').localeCompare(String(b.owner ?? b.assignee ?? '')); return String(b.createdAt ?? '').localeCompare(String(a.createdAt ?? '')); }); }, [activeFilter, attentionOnly, items, primaryFilterKey, query, searchKeys, sortBy]);
  const selected = items.find((item) => item.id === selectedId) ?? filtered[0] ?? items[0] ?? null;
  const subtitleTextForItem = (item: RecordItem) => buildSubtitle ? buildSubtitle(item) : subtitleFields?.length ? subtitleFields.map((key) => String(item[key] ?? '').trim()).filter(Boolean).join(' • ') : item.subtitle ?? '';
  const cardMetaTextForItem = (item: RecordItem) => buildCardMeta ? buildCardMeta(item) : cardMetaFields?.length ? cardMetaFields.map((key) => String(item[key] ?? '').trim()).filter(Boolean).join(' • ') : item.meta ?? '';
  const createRecord = () => { const id = `${storageKey}-${Date.now()}`; const next: RecordItem = { id, title: `New ${title}`, createdAt: new Date().toISOString(), ...Object.fromEntries(fields.map((field) => [field.key, field.toggle ? false : ''])) }; void persist([next, ...items]); setSelectedId(id); };
  const updateSelected = (key: string, value: string | boolean) => { if (!selected) return; void persist(items.map((item) => item.id === selected.id ? { ...item, [key]: value } : item)); };
  const removeSelected = () => { if (!selected) return; void persist(items.filter((item) => item.id !== selected.id)); setSelectedId(''); };
  return <div className="space-y-4"><PageHeader title={title} subtitle={subtitle} actions={<PrimaryButton onClick={createRecord}>{createLabel}</PrimaryButton>} /><div className="rounded-xl border border-border bg-panel px-4 py-3 text-sm text-textMuted">{liveMessage}</div><Card><div className="grid gap-3 md:grid-cols-[1fr_180px_180px_auto]"><Input placeholder="Search..." value={query} onChange={(e) => setQuery(e.target.value)} /><Select value={sortBy} options={sortOptions} onChange={(e) => setSortBy(e.target.value)} /><Select value={activeFilter} options={[{ value: 'all', label: 'All' }, ...filterOptions.map((value) => ({ value, label: value }))]} onChange={(e) => setActiveFilter(e.target.value)} /><Button onClick={() => setAttentionOnly((v) => !v)}><Filter size={14} /> Attention</Button></div></Card><div className="grid gap-4 lg:grid-cols-[minmax(0,1fr)_360px]"><Card><div className="space-y-3">{filtered.map((item) => <button key={item.id} type="button" onClick={() => setSelectedId(item.id)} className="block w-full rounded-xl border border-border p-4 text-left"><p className="font-semibold">{item.title}</p><p className="text-sm text-textMuted">{subtitleTextForItem(item)}</p><p className="text-xs text-textMuted">{cardMetaTextForItem(item)}</p></button>)}{!filtered.length ? <p className="text-sm text-textMuted">No records yet.</p> : null}</div></Card><Card>{selected ? <div className="space-y-3"><Input value={selected.title} onChange={(e) => updateSelected('title', e.target.value)} /><div className="space-y-3">{fields.map((field) => field.toggle ? <div key={field.key} className="flex items-center justify-between rounded-xl border border-border p-3"><span className="text-sm text-textMuted">{field.label}</span><Toggle checked={Boolean(selected[field.key])} onChange={(value) => updateSelected(field.key, value)} /></div> : field.options ? <Select key={field.key} value={String(selected[field.key] ?? '')} options={field.options} onChange={(e) => updateSelected(field.key, e.target.value)} /> : <Input key={field.key} value={String(selected[field.key] ?? '')} onChange={(e) => updateSelected(field.key, e.target.value)} placeholder={field.placeholder || field.label} />)}</div><Button onClick={removeSelected}><Trash2 size={14} /> Delete</Button></div> : <p className="text-sm text-textMuted">Select or create a record.</p>}</Card></div></div>;
}
