export const dynamic = 'force-dynamic';

import { NextRequest, NextResponse } from 'next/server';
import { getInternalCatalogRecord, upsertInternalCatalogRecord } from '@/core/catalog/internal-catalog.service';
import { tenantContextFromRequest } from '@/core/tenant/context';

const CONFIG_RESOURCE = 'admin-config' as any;
const CART_KEY = 'storefront-test-cart';

type ArtworkFileInput = {
  fileName?: string;
  fileSize?: number;
  mimeType?: string;
  lastModified?: number;
};

type CartItem = Record<string, any> & {
  id?: string;
  productName?: string;
  artworkUploads?: any[];
  artwork?: { uploads?: any[]; notes?: string };
};

function responseError(error: unknown, status = 500) {
  return NextResponse.json({ ok: false, error: error instanceof Error ? error.message : 'Storefront artwork request failed.' }, { status });
}

function makeId(prefix = 'artwork') {
  return `${prefix}-${new Date().toISOString().replace(/[-:.TZ]/g, '').slice(0, 14)}-${Math.random().toString(36).slice(2, 7)}`;
}

function safeFileName(value: unknown) {
  return String(value || '').replace(/[\\/]/g, '').trim();
}

function normaliseFiles(files: ArtworkFileInput[], notes: string) {
  const now = new Date().toISOString();
  return files.map((file) => ({
    id: makeId(),
    fileName: safeFileName(file.fileName),
    fileSize: Math.max(0, Number(file.fileSize || 0)),
    mimeType: String(file.mimeType || 'application/octet-stream'),
    lastModified: Number(file.lastModified || 0),
    status: 'uploaded-metadata',
    storageMode: 'metadata-only',
    notes,
    uploadedAt: now,
    source: 'StorefrontTestArtworkUpload',
  }));
}

async function readItems(request: NextRequest): Promise<CartItem[]> {
  try {
    const record = await getInternalCatalogRecord(tenantContextFromRequest(request), CONFIG_RESOURCE, CART_KEY);
    const items = (record as any)?.metadataJson?.items;
    return Array.isArray(items) ? items : [];
  } catch (error) {
    const message = error instanceof Error ? error.message : '';
    if (message.includes('was not found')) return [];
    throw error;
  }
}

async function saveItems(request: NextRequest, items: CartItem[]) {
  return upsertInternalCatalogRecord(tenantContextFromRequest(request), CONFIG_RESOURCE, {
    id: CART_KEY,
    slug: CART_KEY,
    name: 'Storefront test cart',
    description: 'Temporary cart items generated by the storefront test flow with artwork upload metadata.',
    metadataJson: {
      items,
      savedAt: new Date().toISOString(),
      storageKey: CART_KEY,
      source: 'StorefrontTestArtworkUpload',
    },
  } as any);
}

export async function POST(request: NextRequest) {
  try {
    const body = await request.json().catch(() => ({}));
    const cartItemId = String(body.cartItemId || '').trim();
    const notes = String(body.notes || '').trim();
    const files = Array.isArray(body.files) ? body.files : [];

    if (!cartItemId) return responseError(new Error('Cart item id is required for artwork upload.'), 400);
    if (files.length === 0 && !notes) return responseError(new Error('Select at least one artwork file or add artwork notes.'), 400);

    const validFiles = files.map((file: ArtworkFileInput) => ({
      ...file,
      fileName: safeFileName(file.fileName),
    })).filter((file: ArtworkFileInput) => file.fileName);

    if (files.length > 0 && validFiles.length === 0) return responseError(new Error('Artwork file name is required.'), 400);

    const items = await readItems(request);
    const target = items.find((item) => String(item.id) === cartItemId);
    if (!target) return responseError(new Error('Cart item was not found for artwork upload.'), 404);

    const nextUploads = [...(Array.isArray(target.artworkUploads) ? target.artworkUploads : []), ...normaliseFiles(validFiles, notes)];
    const updatedItem = {
      ...target,
      artworkUploads: nextUploads,
      artwork: {
        ...(target.artwork || {}),
        uploads: nextUploads,
        notes,
        status: nextUploads.length > 0 ? 'artwork-received' : 'artwork-note-only',
        updatedAt: new Date().toISOString(),
      },
      updatedAt: new Date().toISOString(),
    };

    const next = items.map((item) => String(item.id) === cartItemId ? updatedItem : item);
    const record = await saveItems(request, next);
    return NextResponse.json({ ok: true, source: 'internal-storefront-artwork-db', data: record, item: updatedItem });
  } catch (error) {
    return responseError(error);
  }
}
