import { platformPrisma } from '@/core/db/platform-prisma';
import { requireSuperAdmin } from '@/core/auth/session-guard.service';

const TENANT_ID = 'platform';
const ALLOWED = new Set(['organizations', 'merchant-accounts', 'api-access-profiles']);
type PlatformRecord = { id: string; name: string; slug: string; description: string; metadataJson: Record<string, unknown>; createdAt: string; updatedAt: string };
function slugify(value: string) { return value.toLowerCase().replace(/[^a-z0-9]+/g, '-').replace(/(^-|-$)/g, '') || `record-${Date.now()}`; }
function safeResource(resource: string) { if (!ALLOWED.has(resource)) throw new Error('Unsupported platform record resource.'); return resource; }
async function ensureTable() { await platformPrisma.$executeRawUnsafe(`CREATE TABLE IF NOT EXISTS "CoreCatalogRecord" ("id" TEXT PRIMARY KEY,"tenantId" TEXT NOT NULL,"resource" TEXT NOT NULL,"slug" TEXT NOT NULL,"name" TEXT NOT NULL,"description" TEXT NOT NULL DEFAULT '',"metadataJson" JSONB,"createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,"updatedAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,CONSTRAINT "CoreCatalogRecord_tenantId_resource_slug_key" UNIQUE ("tenantId","resource","slug"));`); await platformPrisma.$executeRawUnsafe('CREATE INDEX IF NOT EXISTS "CoreCatalogRecord_tenantId_resource_idx" ON "CoreCatalogRecord"("tenantId","resource")'); }
function publicRecord(row: any): PlatformRecord { return { id: String(row.id), name: String(row.name || ''), slug: String(row.slug || ''), description: String(row.description || ''), metadataJson: row.metadataJson || {}, createdAt: row.createdAt instanceof Date ? row.createdAt.toISOString() : String(row.createdAt || ''), updatedAt: row.updatedAt instanceof Date ? row.updatedAt.toISOString() : String(row.updatedAt || '') }; }
export async function listPlatformRecords(resource: string, search = '') { await requireSuperAdmin(); await ensureTable(); const safe = safeResource(resource); const term = search.trim(); const rows = await platformPrisma.$queryRawUnsafe<any[]>('SELECT id,name,slug,description,"metadataJson","createdAt","updatedAt" FROM "CoreCatalogRecord" WHERE "tenantId"=$1 AND resource=$2 AND ($3=\'\' OR lower(name || \' \' || slug || \' \' || description || \' \' || coalesce("metadataJson"::text,\'\')) LIKE lower($4)) ORDER BY "updatedAt" DESC LIMIT 300', TENANT_ID, safe, term, `%${term}%`); return { items: rows.map(publicRecord) }; }
export async function savePlatformRecord(resource: string, record: Record<string, unknown>) { await requireSuperAdmin(); await ensureTable(); const safe = safeResource(resource); const id = String(record.id || `${safe}-${Date.now()}`); const name = String(record.name || record.title || id); const slug = slugify(String(record.slug || record.code || name || id)); const description = String(record.description || record.notes || ''); const metadataJson = { ...record, id, name, slug }; await platformPrisma.$executeRawUnsafe('INSERT INTO "CoreCatalogRecord" (id,"tenantId",resource,slug,name,description,"metadataJson","updatedAt") VALUES ($1,$2,$3,$4,$5,$6,$7::jsonb,NOW()) ON CONFLICT ("tenantId",resource,slug) DO UPDATE SET name=EXCLUDED.name,description=EXCLUDED.description,"metadataJson"=EXCLUDED."metadataJson","updatedAt"=NOW()', id, TENANT_ID, safe, slug, name, description, JSON.stringify(metadataJson)); return { item: { id, name, slug, description, metadataJson } }; }
export async function deletePlatformRecord(resource: string, id: string) { await requireSuperAdmin(); await ensureTable(); const safe = safeResource(resource); await platformPrisma.$executeRawUnsafe('DELETE FROM "CoreCatalogRecord" WHERE "tenantId"=$1 AND resource=$2 AND id=$3', TENANT_ID, safe, id); return { success: true }; }
