'use client';

import { useEffect, useState } from 'react';
import { CheckCircle2, AlertTriangle, RefreshCw } from 'lucide-react';
import { PageHeader } from '@/components/ui/page-header';
import { Card } from '@/components/ui/card';
import { Button } from '@/components/ui/buttons';

type Severity = 'pass' | 'warning' | 'error' | 'info';
type Check = { id: string; group: string; severity: Severity; label: string; detail: string; action?: string };
type Report = { ready: boolean; score: number; generatedAt: string; summary: Record<string, number>; checks: Check[]; nextActions: Check[]; reports: any };
function tone(severity: Severity | string) { if (severity === 'pass') return 'border-emerald-500/30 bg-emerald-500/10 text-emerald-100'; if (severity === 'warning') return 'border-amber-500/30 bg-amber-500/10 text-amber-100'; if (severity === 'error') return 'border-red-500/30 bg-red-500/10 text-red-100'; if (severity === 'info') return 'border-sky-500/30 bg-sky-500/10 text-sky-100'; return 'border-white/10 bg-white/[0.04] text-textMuted'; }
export function StorefrontLiveFlowPage() {
  const [report, setReport] = useState<Report | null>(null);
  const [message, setMessage] = useState('Running final storefront live-flow check...');
  const [busy, setBusy] = useState(false);
  async function run() { setBusy(true); try { const res = await fetch('/api/internal/launch/storefront-live-flow', { cache: 'no-store' }); const payload = await res.json().catch(() => ({})); if (!res.ok || payload?.ok === false) throw new Error(payload?.error || 'Storefront live flow check failed.'); setReport(payload.data); setMessage('Storefront live-flow check completed.'); } catch (error) { setMessage(error instanceof Error ? error.message : 'Storefront live-flow check failed.'); } finally { setBusy(false); } }
  useEffect(() => { void run(); }, []);
  return <div className="space-y-4"><PageHeader title="Storefront Live Flow Final Test" subtitle="One final QA view for hosted storefront, VAT, checkout, orders, customer/account readiness, payment readiness and email notifications." actions={<Button onClick={() => void run()} disabled={busy}><RefreshCw size={14} /> Run check</Button>} />{message ? <div className="rounded-xl border border-white/10 bg-white/[0.04] p-3 text-sm text-textMuted">{message}</div> : null}<div className="grid gap-4 md:grid-cols-5"><Card><p className="text-xs uppercase text-textMuted">Score</p><p className="mt-2 text-3xl font-black text-white">{report?.score ?? '...'}/100</p></Card><Metric label="Pass" value={report?.summary?.pass || 0} severity="pass" /><Metric label="Warnings" value={report?.summary?.warning || 0} severity={report?.summary?.warning ? 'warning' : 'pass'} /><Metric label="Errors" value={report?.summary?.error || 0} severity={report?.summary?.error ? 'error' : 'pass'} /><Metric label="Info" value={report?.summary?.info || 0} severity="info" /></div><Card className={report?.ready ? 'border-emerald-500/30 bg-emerald-500/5' : 'border-amber-500/30 bg-amber-500/5'}><div className="flex items-start gap-3">{report?.ready ? <CheckCircle2 className="mt-1 text-emerald-300" /> : <AlertTriangle className="mt-1 text-amber-300" />}<div><h3 className="font-semibold text-white">{report?.ready ? 'No blocking errors found' : 'Review warnings/errors before live storefront testing'}</h3><p className="mt-1 text-sm text-textMuted">Generated: {report?.generatedAt ? new Date(report.generatedAt).toLocaleString() : '-'}</p></div></div></Card><div className="grid gap-4 xl:grid-cols-[1fr_1fr]"><Card><h3 className="mb-3 text-sm font-semibold text-white">Next actions</h3><div className="space-y-2">{(report?.nextActions || []).map((item) => <CheckCard key={item.id} item={item} />)}{!report?.nextActions?.length ? <p className="text-sm text-textMuted">No blocking next actions.</p> : null}</div></Card><Card><h3 className="mb-3 text-sm font-semibold text-white">All checks</h3><div className="space-y-2">{(report?.checks || []).map((item) => <CheckCard key={item.id} item={item} />)}{!report?.checks?.length ? <p className="text-sm text-textMuted">No checks loaded yet.</p> : null}</div></Card></div><Card><h3 className="mb-3 text-sm font-semibold text-white">Manual browser flow after this passes</h3><div className="grid gap-2 text-sm text-textMuted md:grid-cols-3"><p>1. Open hosted storefront route/domain.</p><p>2. Product list → product detail → cart.</p><p>3. Checkout → order → customer account/order history.</p></div></Card></div>;
}
function Metric({ label, value, severity }: { label: string; value: number; severity: Severity }) { return <Card className={tone(severity)}><p className="text-xs uppercase opacity-80">{label}</p><p className="mt-2 text-2xl font-semibold">{value}</p></Card>; }
function CheckCard({ item }: { item: Check }) { return <div className={`rounded-xl border p-3 ${tone(item.severity)}`}><div className="flex flex-wrap justify-between gap-2"><p className="text-sm font-semibold">{item.label}</p><span className="text-xs uppercase">{item.severity}</span></div><p className="mt-1 text-xs opacity-90">{item.group}: {item.detail}</p>{item.action ? <p className="mt-2 text-xs opacity-90">Action: {item.action}</p> : null}</div>; }
