'use client';

import { useMemo, useState } from 'react';
import Link from 'next/link';
import { Copy, ExternalLink, FilePlus2, FileText, Megaphone, Phone, Trash2 } from 'lucide-react';
import { Input } from '@/components/forms/input';
import { StorefrontMediaField } from './storefront-media-library';
import { StorefrontSectionBuilder } from './storefront-section-builder';
import type { ThemeEditorField } from '@/modules/themes/types';
import { normaliseStorefrontPagePath, storefrontPagePathIsReserved } from '@/theme-runtime/content-pages';

type PageRow = Record<string, any> & { id: string; path: string; title: string; summary: string; enabled: boolean; showInNavigation: boolean; navigationLabel: string; navigationOrder: number; seoTitle: string; seoDescription: string; socialImage: string; noIndex: boolean; sections: Record<string, any>[] };
type Template = { key: string; label: string; description: string; icon: typeof FileText; title: string; path: string; sections: Record<string, any>[] };

function text(value: unknown) { return String(value ?? '').trim(); }
function uid(prefix: string) { const random = typeof globalThis.crypto?.randomUUID === 'function' ? globalThis.crypto.randomUUID().slice(0, 8) : Math.random().toString(36).slice(2, 10); return `${prefix}-${Date.now().toString(36)}-${random}`; }
function block(type: string, values: Record<string, unknown>) { return { id: type, type, enabled: true, ...values }; }
function cloneBlocks(rows: Record<string, any>[]) { return rows.map((row) => ({ ...JSON.parse(JSON.stringify(row)), id: uid(row.type || 'section') })); }

const TEMPLATES: Template[] = [
  { key: 'blank', label: 'Blank page', description: 'A clean text page with a closing action.', icon: FilePlus2, title: 'New page', path: 'new-page', sections: [block('rich-text', { title: 'New page', body: '' }), block('contact-cta', { title: 'Talk to our print team.', buttonLabel: 'Request a quote', buttonHref: '/quote' })] },
  { key: 'about', label: 'About page', description: 'Story, reassurance and enquiry blocks.', icon: FileText, title: 'About us', path: 'about', sections: [block('hero', { eyebrow: 'About us', title: 'Print expertise with a personal service.', buttonLabel: 'Browse products', buttonHref: '/all-products' }), block('image-text', { eyebrow: 'Our story', title: 'Built around dependable production.', body: '' }), block('trust-badges', { title: 'Why choose us', items: [] }), block('contact-cta', { title: 'Tell us what you are planning.', buttonLabel: 'Request a quote', buttonHref: '/quote' })] },
  { key: 'contact', label: 'Contact page', description: 'Contact, collection and FAQ blocks.', icon: Phone, title: 'Contact us', path: 'contact', sections: [block('hero', { eyebrow: 'Contact', title: 'Let us help with your next print project.', buttonLabel: 'Request a quote', buttonHref: '/quote' }), block('collection-points', { title: 'Collection points' }), block('faq', { title: 'Useful answers', items: [] }), block('contact-cta', { title: 'Send us your brief.', buttonLabel: 'Request a quote', buttonHref: '/quote' })] },
  { key: 'campaign', label: 'Campaign page', description: 'Promotion, products, proof and CTA.', icon: Megaphone, title: 'Campaign', path: 'campaign', sections: [block('promo-banner', { eyebrow: 'Limited offer', title: 'Promote your campaign here.', buttonLabel: 'Shop now', buttonHref: '/all-products' }), block('product-grid', { title: 'Campaign products', productSlugs: [], limit: 6 }), block('testimonials', { title: 'Customer stories', items: [] }), block('contact-cta', { title: 'Ask for a tailored quote.', buttonLabel: 'Request a quote', buttonHref: '/quote' })] },
];

function parse(value: unknown): PageRow[] {
  let source = value;
  if (typeof value === 'string') { try { source = JSON.parse(value); } catch { return []; } }
  if (!Array.isArray(source)) return [];
  return source.filter((row) => row && typeof row === 'object' && !Array.isArray(row)).map((row: any, index) => {
    const path = normaliseStorefrontPagePath(row.path || row.slug || `page-${index + 1}`);
    const title = text(row.title) || path.replace(/-/g, ' ').replace(/\b\w/g, (letter) => letter.toUpperCase());
    return { ...row, id: text(row.id) || `page-${index + 1}`, path, title, summary: text(row.summary || row.description), enabled: row.enabled !== false, showInNavigation: row.showInNavigation === true, navigationLabel: text(row.navigationLabel || row.menuLabel || title), navigationOrder: Number(row.navigationOrder ?? row.menuOrder) || 900 + index, seoTitle: text(row.seoTitle), seoDescription: text(row.seoDescription), socialImage: text(row.socialImage || row.heroImage), noIndex: row.noIndex === true, sections: Array.isArray(row.sections) ? row.sections : [] } as PageRow;
  });
}
function uniquePath(base: string, pages: PageRow[]) { const clean = normaliseStorefrontPagePath(base) || 'page'; const used = new Set(pages.map((page) => page.path)); if (!used.has(clean)) return clean; let suffix = 2; while (used.has(`${clean}-${suffix}`)) suffix += 1; return `${clean}-${suffix}`; }
function Toggle({ checked, label, note, onChange }: { checked: boolean; label: string; note: string; onChange: (checked: boolean) => void }) { return <label className="flex cursor-pointer gap-3 rounded-xl border border-white/8 bg-panelMuted/80 p-3"><input type="checkbox" checked={checked} onChange={(event) => onChange(event.target.checked)} className="mt-0.5 h-4 w-4 accent-accent" /><span><span className="block text-[12px] font-medium text-text">{label}</span><span className="mt-1 block text-[10px] leading-4 text-textMuted">{note}</span></span></label>; }

export function StorefrontPageBuilder({ field, value, onChange, draftBase, liveBase }: { field: ThemeEditorField; value: unknown; onChange: (value: unknown) => void; draftBase?: string; liveBase?: string }) {
  const pages = useMemo(() => parse(value), [value]);
  const [selectedId, setSelectedId] = useState('');
  const selected = pages.find((page) => page.id === selectedId) || pages[0] || null;
  const maximum = field.maxItems || 24;
  const replace = (next: PageRow[]) => onChange(next);
  const update = (patch: Partial<PageRow>) => selected && replace(pages.map((page) => page.id === selected.id ? { ...page, ...patch } : page));
  const add = (template: Template) => { if (pages.length >= maximum) return; const next: PageRow = { id: uid('page'), path: uniquePath(template.path, pages), title: template.title, summary: '', enabled: true, showInNavigation: false, navigationLabel: template.title, navigationOrder: 900 + pages.length, seoTitle: '', seoDescription: '', socialImage: '', noIndex: false, sections: cloneBlocks(template.sections) }; replace([...pages, next]); setSelectedId(next.id); };
  const duplicate = (page: PageRow) => { if (pages.length >= maximum) return; const next = { ...JSON.parse(JSON.stringify(page)), id: uid('page'), path: uniquePath(`${page.path}-copy`, pages), title: `${page.title} copy`, enabled: false, showInNavigation: false, sections: cloneBlocks(page.sections) } as PageRow; replace([...pages, next]); setSelectedId(next.id); };
  const remove = (id: string) => { const next = pages.filter((page) => page.id !== id); replace(next); setSelectedId(next[0]?.id || ''); };
  const pageField: ThemeEditorField = { ...field, pageCollection: false, path: `${field.path}.sections`, label: 'Page sections', maxItems: 30 };
  const duplicatePath = selected ? pages.some((page) => page.id !== selected.id && page.path === selected.path) : false;
  const reservedPath = selected ? storefrontPagePathIsReserved(selected.path) : false;

  return <div id="storefront-pages" className="space-y-5">
    <div className="rounded-2xl border border-white/8 bg-black/10 p-4"><div className="flex items-center justify-between gap-3"><div><h3 className="text-sm font-semibold text-white">Page templates</h3><p className="mt-1 text-[11px] leading-5 text-textMuted">Uses the same draft, preview and publish action as the homepage.</p></div><span className="rounded-full bg-panelMuted px-3 py-1.5 text-[10px] text-textMuted">{pages.length}/{maximum}</span></div><div className="mt-4 grid gap-3 sm:grid-cols-2 xl:grid-cols-4">{TEMPLATES.map((template) => { const Icon = template.icon; return <button key={template.key} type="button" disabled={pages.length >= maximum} onClick={() => add(template)} className="rounded-xl border border-dashed border-white/12 bg-panelMuted/60 p-3 text-left hover:border-accent/50 hover:bg-accent/5 disabled:opacity-40"><Icon className="h-4 w-4 text-accent" /><div className="mt-2 text-[12px] font-semibold text-white">{template.label}</div><p className="mt-1 text-[10px] leading-4 text-textMuted">{template.description}</p></button>; })}</div></div>
    <div className="grid gap-5 xl:grid-cols-[0.7fr_1.3fr]">
      <aside className="rounded-2xl border border-white/8 bg-black/10 p-3"><div className="mb-3 text-[11px] font-semibold uppercase tracking-[0.14em] text-accent">Pages</div><div className="space-y-2">{pages.map((page) => <div key={page.id} className={`rounded-xl border p-3 ${selected?.id === page.id ? 'border-accent/60 bg-accent/10' : 'border-white/8 bg-panelMuted/60'}`}><button type="button" onClick={() => setSelectedId(page.id)} className="w-full text-left"><div className="flex justify-between gap-2"><span className="truncate text-[12px] font-semibold text-white">{page.title}</span><span className="text-[9px] text-textMuted">{page.enabled ? 'Public' : 'Hidden'}</span></div><div className="mt-1 truncate font-mono text-[10px] text-textMuted">/{page.path}</div></button><div className="mt-3 flex gap-1"><button type="button" onClick={() => duplicate(page)} className="rounded-lg border border-white/8 p-1.5 text-textMuted"><Copy className="h-3.5 w-3.5" /></button><button type="button" onClick={() => remove(page.id)} className="ml-auto rounded-lg border border-red-500/20 p-1.5 text-red-300"><Trash2 className="h-3.5 w-3.5" /></button></div></div>)}{!pages.length ? <div className="rounded-xl border border-dashed border-white/10 p-5 text-center text-[11px] text-textMuted">Choose a template to create a page.</div> : null}</div></aside>
      <div className="space-y-5">{selected ? <>
        <section className="rounded-2xl border border-white/8 bg-black/10 p-4"><div className="flex flex-wrap items-start justify-between gap-3"><div><h3 className="text-sm font-semibold text-white">Page settings</h3><p className="mt-1 text-[11px] text-textMuted">Paths may contain up to three segments, such as services/design.</p></div><div className="flex gap-2">{draftBase ? <Link target="_blank" href={`${draftBase}/${selected.path}`} className="inline-flex items-center gap-2 rounded-xl border border-amber-400/30 bg-amber-400/10 px-3 py-2 text-[11px] text-amber-100 no-underline"><ExternalLink className="h-3.5 w-3.5" />Draft</Link> : null}{liveBase && selected.enabled ? <Link target="_blank" href={`${liveBase}/${selected.path}`} className="inline-flex items-center gap-2 rounded-xl border border-white/10 bg-panelMuted px-3 py-2 text-[11px] text-text no-underline"><ExternalLink className="h-3.5 w-3.5" />Live</Link> : null}</div></div><div className="mt-4 grid gap-4 lg:grid-cols-2"><div><label className="mb-2 block text-[12px] text-text">Title</label><Input value={selected.title} onChange={(event) => update({ title: event.target.value })} /></div><div><label className="mb-2 block text-[12px] text-text">Path</label><Input value={selected.path} onChange={(event) => update({ path: normaliseStorefrontPagePath(event.target.value) })} />{reservedPath || duplicatePath ? <p className="mt-1 text-[10px] text-red-300">{reservedPath ? 'This path is reserved by the storefront.' : 'Another page already uses this path.'}</p> : null}</div><div className="lg:col-span-2"><label className="mb-2 block text-[12px] text-text">Summary</label><textarea value={selected.summary} onChange={(event) => update({ summary: event.target.value })} rows={3} className="w-full rounded-xl border border-white/8 bg-panelMuted/90 p-3 text-[13px] text-text outline-none" /></div><Toggle checked={selected.enabled} onChange={(enabled) => update({ enabled })} label="Publish page" note="Hidden pages remain in the draft and do not resolve publicly." /><Toggle checked={selected.showInNavigation} onChange={(showInNavigation) => update({ showInNavigation })} label="Add to navigation" note="Adds a menu item unless that path already exists." />{selected.showInNavigation ? <><Input value={selected.navigationLabel} onChange={(event) => update({ navigationLabel: event.target.value })} placeholder="Navigation label" /><Input type="number" value={String(selected.navigationOrder)} onChange={(event) => update({ navigationOrder: Number(event.target.value) || 900 })} placeholder="Navigation order" /></> : null}</div></section>
        <section className="rounded-2xl border border-white/8 bg-black/10 p-4"><h3 className="text-sm font-semibold text-white">Search and sharing</h3><div className="mt-4 grid gap-4 lg:grid-cols-2"><Input value={selected.seoTitle} onChange={(event) => update({ seoTitle: event.target.value })} placeholder="SEO title" /><div><label className="mb-2 block text-[11px] text-textMuted">Social sharing image</label><StorefrontMediaField value={selected.socialImage} onChange={(socialImage) => update({ socialImage })} /></div><textarea value={selected.seoDescription} onChange={(event) => update({ seoDescription: event.target.value })} rows={3} placeholder="SEO description" className="lg:col-span-2 w-full rounded-xl border border-white/8 bg-panelMuted/90 p-3 text-[13px] text-text outline-none" /><div className="lg:col-span-2"><Toggle checked={selected.noIndex} onChange={(noIndex) => update({ noIndex })} label="Hide from search engines" note="Adds noindex and nofollow while keeping the URL accessible." /></div></div></section>
        <section className="rounded-2xl border border-white/8 bg-black/10 p-4"><h3 className="mb-1 text-sm font-semibold text-white">Page sections</h3><p className="mb-4 text-[11px] text-textMuted">Uses the approved homepage block library.</p><StorefrontSectionBuilder field={pageField} value={selected.sections} onChange={(sections) => update({ sections: Array.isArray(sections) ? sections as Record<string, any>[] : [] })} /></section>
      </> : null}</div>
    </div>
  </div>;
}
