import type { V0ThemePackageManifest } from '../contracts';

export const HOLOV2_V0_MANIFEST = {
  key: 'holo-v2-native',
  aliases: ['holo-v2'],
  name: 'HOLO V2',
  version: '1.0.0',
  description: 'HOLO V2 storefront created through the restricted v0 presentation contract.',
  widgetAppearance: {
    surface: 'card',
    density: 'comfortable',
    radius: 'medium',
    optionStyle: 'auto',
    fieldStyle: 'outline',
    buttonStyle: 'pill',
    priceStyle: 'panel',
    shadow: 'soft',
    labelStyle: 'uppercase',
  },
  editor: {
    content: [
      { path: 'brand.brandName', label: 'Store name', type: 'text', group: 'Brand' },
      { path: 'brand.logoUrl', label: 'Logo', type: 'image', group: 'Brand' },
      { path: 'content.text.utilityText', label: 'Announcement text', type: 'text', group: 'Header' },
      { path: 'content.text.footerDescription', label: 'Footer description', type: 'textarea', group: 'Footer' },
      { path: 'sections', label: 'Homepage sections', type: 'sections', group: 'Homepage' },
    ],
    settings: [
      { path: 'brand.primary', label: 'Primary colour', type: 'colour', group: 'Colours' },
      { path: 'brand.accent', label: 'Accent colour', type: 'colour', group: 'Colours' },
      { path: 'brand.background', label: 'Background colour', type: 'colour', group: 'Colours' },
      { path: 'brand.text', label: 'Text colour', type: 'colour', group: 'Colours' },
      { path: 'layout.widgetAppearance.surface', label: 'Widget surface', type: 'select', group: 'Configurator', options: [{ label: 'Theme default', value: '' }, { label: 'Card', value: 'card' }, { label: 'Soft', value: 'soft' }, { label: 'Flat', value: 'flat' }] },
      { path: 'layout.widgetAppearance.density', label: 'Widget spacing', type: 'select', group: 'Configurator', options: [{ label: 'Theme default', value: '' }, { label: 'Compact', value: 'compact' }, { label: 'Comfortable', value: 'comfortable' }, { label: 'Spacious', value: 'spacious' }] },
      { path: 'layout.widgetAppearance.radius', label: 'Widget corner radius', type: 'select', group: 'Configurator', options: [{ label: 'Theme default', value: '' }, { label: 'Small', value: 'small' }, { label: 'Medium', value: 'medium' }, { label: 'Large', value: 'large' }] },
      { path: 'layout.widgetAppearance.optionStyle', label: 'Option control style', type: 'select', group: 'Configurator', options: [{ label: 'Theme default', value: '' }, { label: 'Automatic', value: 'auto' }, { label: 'Cards', value: 'cards' }, { label: 'Pills', value: 'pills' }, { label: 'Segments', value: 'segments' }] },
      { path: 'layout.widgetAppearance.fieldStyle', label: 'Form field style', type: 'select', group: 'Configurator', options: [{ label: 'Theme default', value: '' }, { label: 'Outline', value: 'outline' }, { label: 'Filled', value: 'filled' }, { label: 'Underline', value: 'underline' }] },
      { path: 'layout.widgetAppearance.buttonStyle', label: 'Primary button shape', type: 'select', group: 'Configurator', options: [{ label: 'Theme default', value: '' }, { label: 'Pill', value: 'pill' }, { label: 'Rounded', value: 'rounded' }, { label: 'Square', value: 'square' }] },
      { path: 'layout.widgetAppearance.priceStyle', label: 'Price presentation', type: 'select', group: 'Configurator', options: [{ label: 'Theme default', value: '' }, { label: 'Panel', value: 'panel' }, { label: 'Highlight', value: 'highlight' }, { label: 'Minimal', value: 'minimal' }] },
      { path: 'layout.widgetAppearance.shadow', label: 'Widget shadow', type: 'select', group: 'Configurator', options: [{ label: 'Theme default', value: '' }, { label: 'None', value: 'none' }, { label: 'Soft', value: 'soft' }, { label: 'Strong', value: 'strong' }] },
      { path: 'layout.widgetAppearance.labelStyle', label: 'Widget labels', type: 'select', group: 'Configurator', options: [{ label: 'Theme default', value: '' }, { label: 'Normal', value: 'normal' }, { label: 'Uppercase', value: 'uppercase' }] },
      { path: 'layout.showSearch', label: 'Show search', type: 'boolean', group: 'Header' },
      { path: 'layout.showCollectionPoints', label: 'Show collection selector', type: 'boolean', group: 'Header' },
      { path: 'layout.showCustomerAccount', label: 'Show customer account', type: 'boolean', group: 'Header' },
    ],
  },
} satisfies V0ThemePackageManifest;
