import crypto from 'crypto';
import { NextResponse } from 'next/server';
import { platformPrisma } from '@/core/db/platform-prisma';
import { createAdminServerSession, setAdminSessionCookie } from './session-guard.service';
import type { AdminAuthSession } from './admin-auth.service';
import { recordSecurityEvent } from '@/core/security/security-audit.service';

const PROVIDER = 'google';
type GoogleProfile = { sub: string; email: string; email_verified?: boolean; name?: string; picture?: string; hd?: string };
type UserRow = { id: string; tenantId: string | null; email: string; name: string | null; role: string; isActive: boolean | null; sessionVersion: number | null; tenantName: string | null; tenantSlug: string | null };
type InviteRow = { id: string; tenantId: string; email: string; name: string | null; role: string; invitedBy: string | null; tenantName: string | null; tenantSlug: string | null };
function env(name: string) { return String(process.env[name] || '').trim(); }
function baseUrl(request: Request) { return env('NEXT_PUBLIC_APP_URL') || env('ADMIN_URL') || env('NEXT_PUBLIC_ADMIN_URL') || new URL(request.url).origin; }
function redirectUri(request: Request) { return env('GOOGLE_OAUTH_REDIRECT_URI') || `${baseUrl(request).replace(/\/$/, '')}/api/internal/auth/google/callback`; }
function hash(value: string) { return crypto.createHash('sha256').update(value).digest('hex'); }
function allowedDomains() { return env('GOOGLE_OAUTH_ALLOWED_DOMAINS').split(',').map((x) => x.trim().toLowerCase()).filter(Boolean); }
function roleFromDb(role: string): AdminAuthSession['role'] { if (role === 'SUPERADMIN') return 'super_admin'; if (role === 'TENANT_STAFF') return 'ops_manager'; return 'tenant_admin'; }
function defaultRoute(role: AdminAuthSession['role']) { return role === 'super_admin' ? '/super-admin' : '/workspace'; }
function publicSession(user: UserRow): AdminAuthSession { const role = roleFromDb(user.role); return { id: user.id, name: user.name || user.email, email: user.email, role, company: user.tenantName || (role === 'super_admin' ? 'Print Admin SaaS' : 'Print Admin'), tenantId: user.tenantSlug || user.tenantId || env('DEFAULT_TENANT_ID') || 'holo-print', defaultRoute: defaultRoute(role) }; }
async function ensureTables() { await platformPrisma.$executeRawUnsafe(`CREATE TABLE IF NOT EXISTS "OAuthState" ("id" TEXT PRIMARY KEY,"stateHash" TEXT NOT NULL UNIQUE,"redirectTo" TEXT,"createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,"expiresAt" TIMESTAMP(3) NOT NULL,"usedAt" TIMESTAMP(3));`); await platformPrisma.$executeRawUnsafe(`CREATE TABLE IF NOT EXISTS "OAuthAccount" ("id" TEXT PRIMARY KEY,"userId" TEXT NOT NULL,"provider" TEXT NOT NULL,"providerAccountId" TEXT NOT NULL,"email" TEXT,"picture" TEXT,"createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,"updatedAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,CONSTRAINT "OAuthAccount_provider_providerAccountId_key" UNIQUE ("provider","providerAccountId"));`); await platformPrisma.$executeRawUnsafe('CREATE INDEX IF NOT EXISTS "OAuthAccount_userId_idx" ON "OAuthAccount"("userId")'); await platformPrisma.$executeRawUnsafe('CREATE INDEX IF NOT EXISTS "OAuthState_expiresAt_idx" ON "OAuthState"("expiresAt")'); }
export function googleOAuthConfigured() { return Boolean(env('GOOGLE_OAUTH_CLIENT_ID') && env('GOOGLE_OAUTH_CLIENT_SECRET')); }
export async function createGoogleOAuthUrl(request: Request) { await ensureTables(); if (!googleOAuthConfigured()) throw new Error('Google OAuth is not configured. Add GOOGLE_OAUTH_CLIENT_ID and GOOGLE_OAUTH_CLIENT_SECRET.'); const url = new URL(request.url); const next = url.searchParams.get('next') || '/workspace'; const state = crypto.randomBytes(32).toString('base64url'); await platformPrisma.$executeRawUnsafe('INSERT INTO "OAuthState" (id,"stateHash","redirectTo","expiresAt") VALUES ($1,$2,$3,$4)', `oauthstate-${crypto.randomUUID()}`, hash(state), next, new Date(Date.now() + 10 * 60 * 1000)); const google = new URL('https://accounts.google.com/o/oauth2/v2/auth'); google.searchParams.set('client_id', env('GOOGLE_OAUTH_CLIENT_ID')); google.searchParams.set('redirect_uri', redirectUri(request)); google.searchParams.set('response_type', 'code'); google.searchParams.set('scope', 'openid email profile'); google.searchParams.set('state', state); google.searchParams.set('prompt', 'select_account'); return google.toString(); }
async function consumeState(state: string) { await ensureTables(); const rows = await platformPrisma.$queryRawUnsafe<Array<{ id: string; redirectTo: string | null }>>('SELECT id,"redirectTo" FROM "OAuthState" WHERE "stateHash"=$1 AND "usedAt" IS NULL AND "expiresAt" > NOW() LIMIT 1', hash(state)); const row = rows[0]; if (!row) throw new Error('OAuth state is invalid or expired.'); await platformPrisma.$executeRawUnsafe('UPDATE "OAuthState" SET "usedAt"=NOW() WHERE id=$1', row.id); return row.redirectTo || '/workspace'; }
async function exchangeCode(request: Request, code: string) { const body = new URLSearchParams(); body.set('client_id', env('GOOGLE_OAUTH_CLIENT_ID')); body.set('client_secret', env('GOOGLE_OAUTH_CLIENT_SECRET')); body.set('code', code); body.set('grant_type', 'authorization_code'); body.set('redirect_uri', redirectUri(request)); const response = await fetch('https://oauth2.googleapis.com/token', { method: 'POST', headers: { 'Content-Type': 'application/x-www-form-urlencoded' }, body }); const token = await response.json().catch(() => ({})); if (!response.ok || !token.access_token) throw new Error(token.error_description || token.error || 'Google token exchange failed.'); return String(token.access_token); }
async function fetchProfile(accessToken: string): Promise<GoogleProfile> { const response = await fetch('https://www.googleapis.com/oauth2/v3/userinfo', { headers: { Authorization: `Bearer ${accessToken}` } }); const profile = await response.json().catch(() => ({})); if (!response.ok || !profile.email || !profile.sub) throw new Error('Google profile could not be loaded.'); return profile; }
function checkDomain(profile: GoogleProfile) { const allowed = allowedDomains(); if (!allowed.length) return; const domain = profile.email.split('@')[1]?.toLowerCase() || ''; const hostedDomain = String(profile.hd || '').toLowerCase(); if (!allowed.includes(domain) && !allowed.includes(hostedDomain)) throw new Error('Google account domain is not allowed.'); }
async function findUser(email: string) { const rows = await platformPrisma.$queryRawUnsafe<UserRow[]>('SELECT u.id,u."tenantId",u.email,u.name,u.role::text AS role,u."isActive",u."sessionVersion",t.name AS "tenantName",t.slug AS "tenantSlug" FROM "User" u LEFT JOIN "Tenant" t ON t.id=u."tenantId" WHERE lower(u.email)=lower($1) AND u.role::text IN (\'SUPERADMIN\',\'TENANT_OWNER\',\'TENANT_ADMIN\',\'TENANT_STAFF\') LIMIT 1', email); return rows[0] || null; }
async function findInvite(email: string) { const rows = await platformPrisma.$queryRawUnsafe<InviteRow[]>('SELECT i.id,i."tenantId",i.email,i.name,i.role::text AS role,i."invitedBy",t.name AS "tenantName",t.slug AS "tenantSlug" FROM "AdminInvitation" i JOIN "Tenant" t ON t.id=i."tenantId" WHERE lower(i.email)=lower($1) AND i.status=\'PENDING\' AND i."revokedAt" IS NULL AND i."expiresAt" > NOW() LIMIT 1', email).catch(() => []); return rows[0] || null; }
async function userFromInvite(invite: InviteRow, profile: GoogleProfile) { const id = `user-${crypto.randomUUID()}`; const name = profile.name || invite.name || invite.email; await platformPrisma.$executeRawUnsafe('INSERT INTO "User" (id,"tenantId",email,name,role,"isActive","sessionVersion","updatedAt") VALUES ($1,$2,$3,$4,$5::"UserRole",true,1,NOW()) ON CONFLICT (email) DO UPDATE SET "tenantId"=EXCLUDED."tenantId", name=EXCLUDED.name, role=EXCLUDED.role, "isActive"=true, "updatedAt"=NOW()', id, invite.tenantId, invite.email.toLowerCase(), name, invite.role); const user = await findUser(invite.email); if (!user) throw new Error('Invited user could not be created.'); await platformPrisma.$executeRawUnsafe('INSERT INTO "TenantMembership" (id,"tenantId","userId",role,status,"invitedBy","updatedAt") VALUES ($1,$2,$3,$4::"UserRole",\'ACTIVE\',$5,NOW()) ON CONFLICT ("tenantId","userId") DO UPDATE SET role=EXCLUDED.role,status=\'ACTIVE\',"updatedAt"=NOW()', `member-${crypto.randomUUID()}`, invite.tenantId, user.id, invite.role, invite.invitedBy || 'google-oauth'); await platformPrisma.$executeRawUnsafe('UPDATE "AdminInvitation" SET status=\'ACCEPTED\',"acceptedAt"=NOW(),"acceptedUserId"=$1,"updatedAt"=NOW() WHERE id=$2', user.id, invite.id).catch(() => undefined); return user; }
async function linkAccount(user: UserRow, profile: GoogleProfile) { await ensureTables(); await platformPrisma.$executeRawUnsafe('INSERT INTO "OAuthAccount" (id,"userId",provider,"providerAccountId",email,picture,"updatedAt") VALUES ($1,$2,$3,$4,$5,$6,NOW()) ON CONFLICT (provider,"providerAccountId") DO UPDATE SET "userId"=EXCLUDED."userId",email=EXCLUDED.email,picture=EXCLUDED.picture,"updatedAt"=NOW()', `oauth-${crypto.randomUUID()}`, user.id, PROVIDER, profile.sub, profile.email.toLowerCase(), profile.picture || ''); }
export async function handleGoogleOAuthCallback(request: Request) { const url = new URL(request.url); const code = url.searchParams.get('code') || ''; const state = url.searchParams.get('state') || ''; const error = url.searchParams.get('error') || ''; if (error) throw new Error(error); if (!code || !state) throw new Error('Google OAuth callback is missing code or state.'); const redirectTo = await consumeState(state); const accessToken = await exchangeCode(request, code); const profile = await fetchProfile(accessToken); if (profile.email_verified === false) throw new Error('Google email is not verified.'); checkDomain(profile); const email = profile.email.toLowerCase(); let user = await findUser(email); if (!user) { const invite = await findInvite(email); if (!invite) throw new Error('Google login is invite-only. Ask a Super Admin to invite this email first.'); user = await userFromInvite(invite, profile); } if (user.isActive === false) throw new Error('User is disabled.'); await linkAccount(user, profile); await platformPrisma.$executeRawUnsafe('UPDATE "User" SET "lastLoginAt"=NOW(),"updatedAt"=NOW() WHERE id=$1', user.id).catch(() => undefined); const adminSession = publicSession(user); const serverSession = await createAdminServerSession({ id: user.id, tenantId: user.tenantId, role: user.role, sessionVersion: user.sessionVersion || 1 }); await recordSecurityEvent({ action: 'auth.google.login_success', actor: user.email, tenantId: user.tenantId, severity: 'info', metadata: { provider: PROVIDER } }).catch(() => undefined); const response = NextResponse.redirect(new URL(redirectTo || adminSession.defaultRoute, baseUrl(request))); setAdminSessionCookie(response, serverSession.token, serverSession.expiresAt); return response; }
export async function googleOAuthStatus() { await ensureTables(); const rows = await platformPrisma.$queryRawUnsafe<Array<{ count: bigint | number | string }>>('SELECT COUNT(*)::bigint AS count FROM "OAuthAccount"').catch(() => [{ count: 0 }]); return { configured: googleOAuthConfigured(), allowedDomains: allowedDomains(), linkedAccounts: Number(rows[0]?.count || 0), redirectPath: '/api/internal/auth/google/callback' }; }
