import { platformPrisma } from '@/core/db/platform-prisma';
import { requireTenantSession } from '@/core/auth/session-guard.service';

const THEME_RESOURCE = 'platform-themes';
const ASSIGN_RESOURCE = 'theme-assignments';
const STORE_RESOURCE = 'store-channels';
const ALLOWED_TYPES = ['hero', 'product-grid', 'category-carousel', 'text-image', 'faq', 'contact-cta', 'collection-points'];
const ALLOWED_EXT = ['.json', '.js', '.jsx', '.css', '.svg', '.png', '.jpg', '.jpeg', '.webp', '.md'];
function now() { return new Date().toISOString(); }
function slug(value: unknown, fallback = 'theme') { return String(value || fallback).toLowerCase().replace(/[^a-z0-9]+/g, '-').replace(/(^-|-$)/g, '') || fallback; }
function text(value: unknown) { return String(value || '').trim(); }
async function ensureTable() { await platformPrisma.$executeRawUnsafe(`CREATE TABLE IF NOT EXISTS "CoreCatalogRecord" ("id" TEXT PRIMARY KEY,"tenantId" TEXT NOT NULL,"resource" TEXT NOT NULL,"slug" TEXT NOT NULL,"name" TEXT NOT NULL,"description" TEXT NOT NULL DEFAULT '',"metadataJson" JSONB,"createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,"updatedAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP);`); await platformPrisma.$executeRawUnsafe('CREATE UNIQUE INDEX IF NOT EXISTS "CoreCatalogRecord_tenant_resource_slug_uq" ON "CoreCatalogRecord"("tenantId","resource","slug")'); }
function platformTenantId() { return 'platform'; }
function normalizeTheme(input: Record<string, any>) { const key = slug(input.themeKey || input.key || input.name, 'theme'); const manifest = typeof input.manifest === 'object' && input.manifest ? input.manifest : {}; const supportedSections = Array.isArray(input.supportedSections) ? input.supportedSections : Array.isArray(manifest.supports) ? manifest.supports : ALLOWED_TYPES; return { themeKey: key, name: text(input.name || manifest.name || key), version: text(input.version || manifest.version || '1.0.0'), status: ['draft', 'published', 'disabled'].includes(input.status) ? input.status : 'draft', description: text(input.description || manifest.description || ''), previewImage: text(input.previewImage || manifest.previewImage || ''), themeType: input.themeType === 'external-compatible' ? 'external-compatible' : 'hosted', uploadMode: text(input.uploadMode || 'manifest'), fileStoragePath: text(input.fileStoragePath || ''), manifest: { ...manifest, themeKey: key }, supportedSections: supportedSections.filter((item: string) => ALLOWED_TYPES.includes(item)), updatedAt: now() }; }
function mapTheme(row: any) { const meta = row?.metadataJson || {}; return { id: row?.id || `theme-${meta.themeKey || row?.slug}`, slug: row?.slug || meta.themeKey, ...meta }; }
function mapAssignment(row: any) { const meta = row?.metadataJson || {}; return { id: row?.id || `assign-${meta.themeKey || row?.slug}`, slug: row?.slug || meta.themeKey, ...meta }; }
async function seedDefaultTheme() { const count = await platformPrisma.$queryRawUnsafe<Array<{ count: string }>>('SELECT COUNT(*)::text as count FROM "CoreCatalogRecord" WHERE "tenantId"=$1 AND resource=$2', platformTenantId(), THEME_RESOURCE); if (Number(count[0]?.count || 0) > 0) return; await savePlatformTheme({ themeKey: 'holo-default', name: 'HOLO Default Theme', version: '1.0.0', status: 'published', description: 'Default hosted print storefront theme.', supportedSections: ALLOWED_TYPES, previewImage: '' }); await saveThemeAssignment({ themeKey: 'holo-default', visibility: 'all', enabled: true }); }
export async function listPlatformThemes() { await ensureTable(); await seedDefaultTheme(); const rows = await platformPrisma.$queryRawUnsafe<any[]>('SELECT id,slug,name,description,"metadataJson","updatedAt" FROM "CoreCatalogRecord" WHERE "tenantId"=$1 AND resource=$2 ORDER BY "updatedAt" DESC', platformTenantId(), THEME_RESOURCE); const assignments = await listThemeAssignments(); return { items: rows.map(mapTheme), assignments: assignments.items }; }
export async function savePlatformTheme(input: Record<string, any>) { await ensureTable(); const theme = normalizeTheme(input); await platformPrisma.$executeRawUnsafe('INSERT INTO "CoreCatalogRecord" (id,"tenantId",resource,slug,name,description,"metadataJson","updatedAt") VALUES ($1,$2,$3,$4,$5,$6,$7::jsonb,NOW()) ON CONFLICT ("tenantId",resource,slug) DO UPDATE SET name=EXCLUDED.name,description=EXCLUDED.description,"metadataJson"=EXCLUDED."metadataJson","updatedAt"=NOW()', `platform-theme-${theme.themeKey}`, platformTenantId(), THEME_RESOURCE, theme.themeKey, theme.name, theme.description, JSON.stringify(theme)); return theme; }
export async function listThemeAssignments() { await ensureTable(); const rows = await platformPrisma.$queryRawUnsafe<any[]>('SELECT id,slug,name,description,"metadataJson","updatedAt" FROM "CoreCatalogRecord" WHERE "tenantId"=$1 AND resource=$2 ORDER BY "updatedAt" DESC', platformTenantId(), ASSIGN_RESOURCE); return { items: rows.map(mapAssignment) }; }
export async function saveThemeAssignment(input: Record<string, any>) { await ensureTable(); const themeKey = slug(input.themeKey || input.slug, 'theme'); const visibility = ['all', 'selected-tenants', 'selected-stores'].includes(input.visibility) ? input.visibility : 'all'; const meta = { themeKey, visibility, enabled: input.enabled !== false, tenantIds: Array.isArray(input.tenantIds) ? input.tenantIds.map(String).filter(Boolean) : [], storeChannelIds: Array.isArray(input.storeChannelIds) ? input.storeChannelIds.map(String).filter(Boolean) : [], updatedAt: now() }; await platformPrisma.$executeRawUnsafe('INSERT INTO "CoreCatalogRecord" (id,"tenantId",resource,slug,name,description,"metadataJson","updatedAt") VALUES ($1,$2,$3,$4,$5,$6,$7::jsonb,NOW()) ON CONFLICT ("tenantId",resource,slug) DO UPDATE SET name=EXCLUDED.name,description=EXCLUDED.description,"metadataJson"=EXCLUDED."metadataJson","updatedAt"=NOW()', `theme-assignment-${themeKey}`, platformTenantId(), ASSIGN_RESOURCE, themeKey, `Assignment: ${themeKey}`, 'Theme visibility assignment.', JSON.stringify(meta)); return meta; }
export function validateThemeZipManifest(input: Record<string, any>) { const checks: Array<Record<string, any>> = []; const files = Array.isArray(input.files) ? input.files.map(String) : []; const manifest = typeof input.manifest === 'object' && input.manifest ? input.manifest : {}; const size = Number(input.sizeBytes || 0); if (!text(input.filename).endsWith('.zip')) checks.push({ severity: 'error', label: 'ZIP filename required', detail: 'Theme packages must be ZIP files.' }); else checks.push({ severity: 'pass', label: 'ZIP filename', detail: input.filename }); if (size && size > 20 * 1024 * 1024) checks.push({ severity: 'error', label: 'ZIP too large', detail: 'Theme package must be under 20MB.' }); else checks.push({ severity: 'pass', label: 'ZIP size', detail: size ? `${Math.round(size / 1024)}KB` : 'Size not supplied yet.' }); if (!manifest.name || !manifest.version || !manifest.themeKey) checks.push({ severity: 'error', label: 'theme.json incomplete', detail: 'Manifest needs name, version and themeKey.' }); else checks.push({ severity: 'pass', label: 'theme.json', detail: `${manifest.name} ${manifest.version}` }); const blocked = files.filter((file: string) => ['.env', '.ts', '.tsx', '.server.js'].some((ext) => file.endsWith(ext)) || file.includes('..') || file.startsWith('/')); if (blocked.length) checks.push({ severity: 'error', label: 'Blocked files detected', detail: blocked.join(', ') }); const badExt = files.filter((file: string) => !ALLOWED_EXT.some((ext) => file.toLowerCase().endsWith(ext))); if (badExt.length) checks.push({ severity: 'warning', label: 'Unknown file extensions', detail: badExt.join(', ') }); if (!files.includes('theme.json')) checks.push({ severity: 'warning', label: 'theme.json file not listed', detail: 'ZIP file list should include theme.json at root.' }); return { ready: !checks.some((c) => c.severity === 'error'), checks, manifest, files, sizeBytes: size }; }
export async function listAllowedThemesForTenant(request: Request, channelSlug = 'default-store') { const session = await requireTenantSession(request); const tenantId = String(session.tenantId || ''); const library = await listPlatformThemes(); const assignments = library.assignments.filter((a: any) => a.enabled !== false); const allowedKeys = new Set(assignments.filter((a: any) => a.visibility === 'all' || (a.visibility === 'selected-tenants' && a.tenantIds?.includes(tenantId)) || (a.visibility === 'selected-stores' && a.storeChannelIds?.includes(channelSlug))).map((a: any) => a.themeKey)); return { tenantId, channelSlug, items: library.items.filter((theme: any) => theme.status === 'published' && allowedKeys.has(theme.themeKey)) }; }
export async function selectThemeForStore(request: Request, input: Record<string, any>) { const session = await requireTenantSession(request); const tenantId = String(session.tenantId || ''); const channelSlug = slug(input.channelSlug || 'default-store', 'default-store'); const themeKey = slug(input.themeKey, 'theme'); const allowed = await listAllowedThemesForTenant(request, channelSlug); if (!allowed.items.some((theme: any) => theme.themeKey === themeKey)) throw new Error('Theme is not assigned to this tenant/store.'); const rows = await platformPrisma.$queryRawUnsafe<any[]>('SELECT id,slug,name,description,"metadataJson" FROM "CoreCatalogRecord" WHERE "tenantId"=$1 AND resource=$2 AND slug=$3 LIMIT 1', tenantId, STORE_RESOURCE, channelSlug); const previous = rows[0]?.metadataJson || { slug: channelSlug, name: channelSlug }; const metadata = { ...previous, themeKey, themeId: themeKey, hostedThemeEnabled: true, updatedAt: now() }; await platformPrisma.$executeRawUnsafe('INSERT INTO "CoreCatalogRecord" (id,"tenantId",resource,slug,name,description,"metadataJson","updatedAt") VALUES ($1,$2,$3,$4,$5,$6,$7::jsonb,NOW()) ON CONFLICT ("tenantId",resource,slug) DO UPDATE SET "metadataJson"=EXCLUDED."metadataJson","updatedAt"=NOW()', `store-channel-${tenantId}-${channelSlug}`, tenantId, STORE_RESOURCE, channelSlug, text(previous.name || channelSlug), 'Store channel theme selection.', JSON.stringify(metadata)); return { tenantId, channelSlug, themeKey, channel: metadata }; }
