import { platformPrisma } from '@/core/db/platform-prisma';
import { requireTenantSession } from '@/core/auth/session-guard.service';
import { publishHostedTheme } from './hosted-theme-editor.service';

const STORE_RESOURCE = 'store-channels';
function slug(value: unknown) { return String(value || 'default-store').toLowerCase().replace(/[^a-z0-9]+/g, '-').replace(/(^-|-$)/g, '') || 'default-store'; }
async function ensureTable() { await platformPrisma.$executeRawUnsafe(`CREATE TABLE IF NOT EXISTS "CoreCatalogRecord" ("id" TEXT PRIMARY KEY,"tenantId" TEXT NOT NULL,"resource" TEXT NOT NULL,"slug" TEXT NOT NULL,"name" TEXT NOT NULL,"description" TEXT NOT NULL DEFAULT '',"metadataJson" JSONB,"createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,"updatedAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP);`); await platformPrisma.$executeRawUnsafe('CREATE UNIQUE INDEX IF NOT EXISTS "CoreCatalogRecord_tenant_resource_slug_uq" ON "CoreCatalogRecord"("tenantId","resource","slug")'); }
export async function getStoreDesignLiveReadiness(channelSlugInput = 'default-store') { const session = await requireTenantSession(); await ensureTable(); const tenantId = String(session.tenantId || ''); const channelSlug = slug(channelSlugInput); const rows = await platformPrisma.$queryRawUnsafe<any[]>('SELECT id,slug,name,description,"metadataJson","updatedAt" FROM "CoreCatalogRecord" WHERE "tenantId"=$1 AND resource=$2 AND slug=$3 LIMIT 1', tenantId, STORE_RESOURCE, channelSlug); const channel = rows[0]?.metadataJson || { slug: channelSlug, name: channelSlug }; const checks = [ { label: 'Store channel', ok: Boolean(rows[0]), detail: rows[0] ? 'Store/channel record exists.' : 'No store/channel record found yet.' }, { label: 'Theme selected', ok: Boolean(channel.themeKey || channel.themeId), detail: channel.themeKey || channel.themeId || 'No theme selected.' }, { label: 'Hosted theme enabled', ok: channel.hostedThemeEnabled !== false, detail: channel.hostedThemeEnabled === false ? 'Hosted theme disabled.' : 'Hosted theme enabled.' } ]; return { tenantId, channelSlug, channel, ready: checks.every((check) => check.ok), checks }; }
export async function setStoreDesignLive(channelSlugInput = 'default-store') { const session = await requireTenantSession(); await ensureTable(); const tenantId = String(session.tenantId || ''); const channelSlug = slug(channelSlugInput); const readiness = await getStoreDesignLiveReadiness(channelSlug); if (!readiness.ready) throw new Error('Store design is not ready.'); const liveTheme = await publishHostedTheme(channelSlug); const channel = readiness.channel || {}; const metadata = { ...channel, slug: channelSlug, themeKey: channel.themeKey || channel.themeId || '', themeId: channel.themeId || channel.themeKey || '', hostedThemeEnabled: true, themeLiveAt: new Date().toISOString(), themeLiveStatus: 'live', liveThemeVersion: liveTheme.settings?.publishedVersion || liveTheme.settings?.draftVersion || 0 };
  await platformPrisma.$executeRawUnsafe('INSERT INTO "CoreCatalogRecord" (id,"tenantId",resource,slug,name,description,"metadataJson","updatedAt") VALUES ($1,$2,$3,$4,$5,$6,$7::jsonb,NOW()) ON CONFLICT ("tenantId",resource,slug) DO UPDATE SET "metadataJson"=EXCLUDED."metadataJson","updatedAt"=NOW()', `store-channel-${tenantId}-${channelSlug}`, tenantId, STORE_RESOURCE, channelSlug, String(channel.name || channelSlug), 'Store design live configuration.', JSON.stringify(metadata)); return { tenantId, channelSlug, channel: metadata, theme: liveTheme.settings };
}
