import JSZip from 'jszip';
import { platformPrisma } from '@/core/db/platform-prisma';
import { savePlatformTheme, validateThemeZipManifest } from './platform-theme-library.service';

const PACKAGE_RESOURCE = 'platform-theme-packages';
const VERSION_RESOURCE = 'platform-theme-versions';
const PREVIEW_RESOURCE = 'theme-preview-snapshots';
const PLATFORM_TENANT = 'platform';
function now() { return new Date().toISOString(); }
function slug(value: unknown, fallback = 'theme') { return String(value || fallback).toLowerCase().replace(/[^a-z0-9]+/g, '-').replace(/(^-|-$)/g, '') || fallback; }
async function ensureTable() { await platformPrisma.$executeRawUnsafe(`CREATE TABLE IF NOT EXISTS "CoreCatalogRecord" ("id" TEXT PRIMARY KEY,"tenantId" TEXT NOT NULL,"resource" TEXT NOT NULL,"slug" TEXT NOT NULL,"name" TEXT NOT NULL,"description" TEXT NOT NULL DEFAULT '',"metadataJson" JSONB,"createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,"updatedAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP);`); await platformPrisma.$executeRawUnsafe('CREATE UNIQUE INDEX IF NOT EXISTS "CoreCatalogRecord_tenant_resource_slug_uq" ON "CoreCatalogRecord"("tenantId","resource","slug")'); }
function asJson(row: any) { return row?.metadataJson || {}; }
export async function parseThemeZipUpload(file: File) { const buffer = Buffer.from(await file.arrayBuffer()); const zip = await JSZip.loadAsync(buffer); const files = Object.keys(zip.files).filter((name) => !zip.files[name].dir); const manifestFile = zip.file('theme.json'); if (!manifestFile) throw new Error('theme.json is required at ZIP root.'); const manifest = JSON.parse(await manifestFile.async('text')); const validation = validateThemeZipManifest({ filename: file.name, sizeBytes: buffer.byteLength, files, manifest }); if (!validation.ready) throw new Error(`Theme ZIP failed validation: ${validation.checks.filter((c: any) => c.severity === 'error').map((c: any) => c.label).join(', ')}`); return { filename: file.name, sizeBytes: buffer.byteLength, files, manifest, zipBase64: buffer.toString('base64'), validation }; }
export async function storeThemeZipPackage(file: File) { await ensureTable(); const parsed = await parseThemeZipUpload(file); const themeKey = slug(parsed.manifest.themeKey || parsed.manifest.name); const version = String(parsed.manifest.version || '1.0.0'); const packageSlug = `${themeKey}-${version}-${Date.now()}`; const packageRecord = { themeKey, version, filename: parsed.filename, sizeBytes: parsed.sizeBytes, files: parsed.files, manifest: parsed.manifest, storageMode: 'database-jsonb-base64', zipBase64: parsed.zipBase64, uploadedAt: now(), validation: parsed.validation };
  await platformPrisma.$executeRawUnsafe('INSERT INTO "CoreCatalogRecord" (id,"tenantId",resource,slug,name,description,"metadataJson","updatedAt") VALUES ($1,$2,$3,$4,$5,$6,$7::jsonb,NOW()) ON CONFLICT ("tenantId",resource,slug) DO UPDATE SET "metadataJson"=EXCLUDED."metadataJson","updatedAt"=NOW()', `theme-package-${packageSlug}`, PLATFORM_TENANT, PACKAGE_RESOURCE, packageSlug, `Package ${themeKey} ${version}`, 'Uploaded hosted theme ZIP package.', JSON.stringify(packageRecord));
  await savePlatformTheme({ themeKey, name: parsed.manifest.name || themeKey, version, status: 'draft', description: parsed.manifest.description || '', previewImage: parsed.manifest.previewImage || '', manifest: parsed.manifest, supportedSections: parsed.manifest.supports || [] });
  await saveThemeVersion({ themeKey, version, packageSlug, manifest: parsed.manifest, status: 'uploaded', notes: `Uploaded ${parsed.filename}` });
  return { ...packageRecord, packageSlug };
}
export async function saveThemeVersion(input: Record<string, any>) { await ensureTable(); const themeKey = slug(input.themeKey); const version = String(input.version || '1.0.0'); const versionSlug = `${themeKey}-${version}`; const meta = { themeKey, version, packageSlug: input.packageSlug || '', manifest: input.manifest || {}, status: input.status || 'uploaded', notes: input.notes || '', createdAt: input.createdAt || now(), active: Boolean(input.active) };
  await platformPrisma.$executeRawUnsafe('INSERT INTO "CoreCatalogRecord" (id,"tenantId",resource,slug,name,description,"metadataJson","updatedAt") VALUES ($1,$2,$3,$4,$5,$6,$7::jsonb,NOW()) ON CONFLICT ("tenantId",resource,slug) DO UPDATE SET "metadataJson"=EXCLUDED."metadataJson","updatedAt"=NOW()', `theme-version-${versionSlug}`, PLATFORM_TENANT, VERSION_RESOURCE, versionSlug, `Version ${themeKey} ${version}`, 'Hosted theme version.', JSON.stringify(meta)); return meta; }
export async function listThemeVersions(themeKeyInput?: string) { await ensureTable(); const key = themeKeyInput ? slug(themeKeyInput) : ''; const rows = key ? await platformPrisma.$queryRawUnsafe<any[]>('SELECT slug,name,description,"metadataJson","updatedAt" FROM "CoreCatalogRecord" WHERE "tenantId"=$1 AND resource=$2 AND slug LIKE $3 ORDER BY "updatedAt" DESC', PLATFORM_TENANT, VERSION_RESOURCE, `${key}-%`) : await platformPrisma.$queryRawUnsafe<any[]>('SELECT slug,name,description,"metadataJson","updatedAt" FROM "CoreCatalogRecord" WHERE "tenantId"=$1 AND resource=$2 ORDER BY "updatedAt" DESC', PLATFORM_TENANT, VERSION_RESOURCE); return { items: rows.map((row) => ({ slug: row.slug, ...asJson(row) })) }; }
export async function rollbackThemeVersion(themeKeyInput: string, versionInput: string) { await ensureTable(); const themeKey = slug(themeKeyInput); const targetVersion = String(versionInput || ''); const versions = await listThemeVersions(themeKey); const target = versions.items.find((item: any) => item.version === targetVersion); if (!target) throw new Error('Theme version was not found.'); for (const item of versions.items) { await saveThemeVersion({ ...item, active: item.version === targetVersion, status: item.version === targetVersion ? 'active' : item.status === 'active' ? 'uploaded' : item.status }); }
  await savePlatformTheme({ themeKey, name: target.manifest?.name || themeKey, version: targetVersion, status: 'published', description: target.manifest?.description || '', previewImage: target.manifest?.previewImage || '', manifest: target.manifest || {}, supportedSections: target.manifest?.supports || [] }); return { themeKey, version: targetVersion, active: true };
}
export async function createThemePreviewSnapshot(input: Record<string, any>) { await ensureTable(); const themeKey = slug(input.themeKey); const version = String(input.version || 'draft'); const slugValue = `${themeKey}-${version}-${Date.now()}`; const meta = { themeKey, version, channelSlug: input.channelSlug || 'default-store', sections: Array.isArray(input.sections) ? input.sections : [], brand: input.brand || {}, createdAt: now(), expiresAt: new Date(Date.now() + 60 * 60 * 1000).toISOString() };
  await platformPrisma.$executeRawUnsafe('INSERT INTO "CoreCatalogRecord" (id,"tenantId",resource,slug,name,description,"metadataJson","updatedAt") VALUES ($1,$2,$3,$4,$5,$6,$7::jsonb,NOW())', `theme-preview-${slugValue}`, PLATFORM_TENANT, PREVIEW_RESOURCE, slugValue, `Preview ${themeKey}`, 'Temporary hosted theme preview snapshot.', JSON.stringify(meta)); return { previewId: slugValue, ...meta };
}
export async function getThemePreviewSnapshot(previewId: string) { await ensureTable(); const rows = await platformPrisma.$queryRawUnsafe<any[]>('SELECT slug,"metadataJson" FROM "CoreCatalogRecord" WHERE "tenantId"=$1 AND resource=$2 AND slug=$3 LIMIT 1', PLATFORM_TENANT, PREVIEW_RESOURCE, previewId); if (!rows[0]) throw new Error('Theme preview was not found.'); return { previewId, ...asJson(rows[0]) }; }
export async function listThemePackages(themeKeyInput?: string) { await ensureTable(); const key = themeKeyInput ? slug(themeKeyInput) : ''; const rows = key ? await platformPrisma.$queryRawUnsafe<any[]>('SELECT slug,name,description,"metadataJson","updatedAt" FROM "CoreCatalogRecord" WHERE "tenantId"=$1 AND resource=$2 AND slug LIKE $3 ORDER BY "updatedAt" DESC', PLATFORM_TENANT, PACKAGE_RESOURCE, `${key}-%`) : await platformPrisma.$queryRawUnsafe<any[]>('SELECT slug,name,description,"metadataJson","updatedAt" FROM "CoreCatalogRecord" WHERE "tenantId"=$1 AND resource=$2 ORDER BY "updatedAt" DESC', PLATFORM_TENANT, PACKAGE_RESOURCE); return { items: rows.map((row) => { const meta = asJson(row); return { slug: row.slug, themeKey: meta.themeKey, version: meta.version, filename: meta.filename, sizeBytes: meta.sizeBytes, files: meta.files, uploadedAt: meta.uploadedAt, storageMode: meta.storageMode, manifest: meta.manifest, validation: meta.validation }; }) }; }
