'use client';

import { useEffect, useState } from 'react';
import { Copy, Mail, RefreshCw, Send } from 'lucide-react';
import { PageHeader } from '@/components/ui/page-header';
import { Card } from '@/components/ui/card';
import { Button } from '@/components/ui/buttons';

type OutboxEmail = {
  id: string;
  type: string;
  status: string;
  to: string;
  subject: string;
  body: string;
  reuploadLink?: string;
  uploadId?: string;
  orderId?: string;
  quoteId?: string;
  createdAt: string;
  sentAt?: string;
  failedAt?: string;
  lastError?: string;
  attempts?: number;
  messageId?: string;
};

type SmtpStatus = { configured: boolean; host?: string; port?: string; from?: string };

export function EmailOutboxPage() {
  const [items, setItems] = useState<OutboxEmail[]>([]);
  const [smtp, setSmtp] = useState<SmtpStatus | null>(null);
  const [loading, setLoading] = useState(true);
  const [sending, setSending] = useState('');
  const [copied, setCopied] = useState('');

  async function load() {
    setLoading(true);
    try {
      const res = await fetch('/api/internal/email-outbox', { cache: 'no-store' });
      const payload = await res.json().catch(() => ({}));
      setItems(Array.isArray(payload?.data?.items) ? payload.data.items : []);
      setSmtp(payload?.smtp || null);
    } finally {
      setLoading(false);
    }
  }

  useEffect(() => { void load(); }, []);

  async function copyText(id: string, text: string) {
    await navigator.clipboard?.writeText(text);
    setCopied(id);
    window.setTimeout(() => setCopied(''), 1800);
  }

  async function sendOne(id: string) {
    setSending(id);
    try {
      await fetch(`/api/internal/email-outbox/${encodeURIComponent(id)}/send`, { method: 'POST' });
      await load();
    } finally {
      setSending('');
    }
  }

  async function sendQueued() {
    setSending('queued');
    try {
      await fetch('/api/internal/email-outbox', { method: 'POST', headers: { 'Content-Type': 'application/json' }, body: JSON.stringify({ action: 'send-queued' }) });
      await load();
    } finally {
      setSending('');
    }
  }

  return (
    <div className="space-y-5">
      <PageHeader
        title="Email Outbox"
        subtitle="Customer messages generated by artwork workflow actions. Configure SMTP env to send automatically or use manual retry buttons."
        actions={<><Button onClick={() => void load()}><RefreshCw size={14} /> Refresh</Button><Button onClick={() => void sendQueued()} disabled={sending === 'queued'}><Send size={14} /> Send queued</Button></>}
      />
      <Card>
        <div className={`rounded-xl border p-3 text-sm ${smtp?.configured ? 'border-emerald-500/30 bg-emerald-500/10 text-emerald-200' : 'border-amber-500/30 bg-amber-500/10 text-amber-200'}`}>
          SMTP: {smtp?.configured ? `configured (${smtp.from || 'from address not shown'})` : 'not configured'}
          {!smtp?.configured ? <span className="ml-2 text-textMuted">Add SMTP_HOST, SMTP_PORT, SMTP_USER, SMTP_PASS and SMTP_FROM env vars.</span> : null}
        </div>
      </Card>
      <Card>
        {loading ? <p className="text-sm text-textMuted">Loading outbox…</p> : null}
        {!loading && !items.length ? <p className="rounded-xl border border-dashed border-white/10 p-8 text-center text-sm text-textMuted">No email outbox records yet.</p> : null}
        <div className="space-y-4">
          {items.map((email) => (
            <div key={email.id} className="rounded-2xl border border-white/8 bg-white/[0.03] p-4">
              <div className="flex flex-wrap items-start justify-between gap-3">
                <div className="flex items-start gap-3">
                  <div className="grid h-10 w-10 place-items-center rounded-xl border border-white/8 bg-white/[0.04]"><Mail size={18} /></div>
                  <div>
                    <p className="text-sm font-semibold text-white">{email.subject}</p>
                    <p className="mt-1 text-xs text-textMuted">To: {email.to || 'Customer email missing'} · {email.status} · attempts {email.attempts || 0} · {new Date(email.createdAt).toLocaleString()}</p>
                    <p className="mt-1 text-xs text-textMuted">Upload: {email.uploadId || '—'} · Order: {email.orderId || email.quoteId || '—'}</p>
                    {email.sentAt ? <p className="mt-1 text-xs text-emerald-200">Sent: {new Date(email.sentAt).toLocaleString()} {email.messageId ? `· ${email.messageId}` : ''}</p> : null}
                    {email.lastError ? <p className="mt-1 text-xs text-red-300">Last error: {email.lastError}</p> : null}
                  </div>
                </div>
                <div className="flex flex-wrap gap-2">
                  <Button onClick={() => void sendOne(email.id)} disabled={sending === email.id || !email.to}><Send size={14} /> {email.status === 'sent' ? 'Send again' : 'Send'}</Button>
                  <Button onClick={() => void copyText(email.id, `To: ${email.to}\nSubject: ${email.subject}\n\n${email.body}`)}><Copy size={14} /> {copied === email.id ? 'Copied' : 'Copy email'}</Button>
                </div>
              </div>
              {email.reuploadLink ? <div className="mt-3 rounded-xl border border-white/8 bg-black/20 p-3 text-xs text-textMuted break-all">Re-upload link: {email.reuploadLink}</div> : null}
              <pre className="mt-3 whitespace-pre-wrap rounded-xl border border-white/8 bg-black/20 p-3 text-xs leading-6 text-textMuted">{email.body}</pre>
            </div>
          ))}
        </div>
      </Card>
    </div>
  );
}
