'use client';

import { useEffect, useState } from 'react';
import { Copy, Mail, RefreshCw } from 'lucide-react';
import { PageHeader } from '@/components/ui/page-header';
import { Card } from '@/components/ui/card';
import { Button } from '@/components/ui/buttons';

type OutboxEmail = {
  id: string;
  type: string;
  status: string;
  to: string;
  subject: string;
  body: string;
  reuploadLink?: string;
  uploadId?: string;
  orderId?: string;
  quoteId?: string;
  createdAt: string;
};

export function EmailOutboxPage() {
  const [items, setItems] = useState<OutboxEmail[]>([]);
  const [loading, setLoading] = useState(true);
  const [copied, setCopied] = useState('');

  async function load() {
    setLoading(true);
    try {
      const res = await fetch('/api/internal/email-outbox', { cache: 'no-store' });
      const payload = await res.json().catch(() => ({}));
      setItems(Array.isArray(payload?.data?.items) ? payload.data.items : []);
    } finally {
      setLoading(false);
    }
  }

  useEffect(() => { void load(); }, []);

  async function copyText(id: string, text: string) {
    await navigator.clipboard?.writeText(text);
    setCopied(id);
    window.setTimeout(() => setCopied(''), 1800);
  }

  return (
    <div className="space-y-5">
      <PageHeader
        title="Email Outbox"
        subtitle="Email-ready customer messages generated by workflow actions. SMTP sending can be connected later without changing the artwork rejection flow."
        actions={<Button onClick={() => void load()}><RefreshCw size={14} /> Refresh</Button>}
      />
      <Card>
        {loading ? <p className="text-sm text-textMuted">Loading outbox…</p> : null}
        {!loading && !items.length ? <p className="rounded-xl border border-dashed border-white/10 p-8 text-center text-sm text-textMuted">No email outbox records yet.</p> : null}
        <div className="space-y-4">
          {items.map((email) => (
            <div key={email.id} className="rounded-2xl border border-white/8 bg-white/[0.03] p-4">
              <div className="flex flex-wrap items-start justify-between gap-3">
                <div className="flex items-start gap-3">
                  <div className="grid h-10 w-10 place-items-center rounded-xl border border-white/8 bg-white/[0.04]"><Mail size={18} /></div>
                  <div>
                    <p className="text-sm font-semibold text-white">{email.subject}</p>
                    <p className="mt-1 text-xs text-textMuted">To: {email.to || 'Customer email missing'} · {email.status} · {new Date(email.createdAt).toLocaleString()}</p>
                    <p className="mt-1 text-xs text-textMuted">Upload: {email.uploadId || '—'} · Order: {email.orderId || email.quoteId || '—'}</p>
                  </div>
                </div>
                <Button onClick={() => void copyText(email.id, `To: ${email.to}\nSubject: ${email.subject}\n\n${email.body}`)}><Copy size={14} /> {copied === email.id ? 'Copied' : 'Copy email'}</Button>
              </div>
              {email.reuploadLink ? <div className="mt-3 rounded-xl border border-white/8 bg-black/20 p-3 text-xs text-textMuted break-all">Re-upload link: {email.reuploadLink}</div> : null}
              <pre className="mt-3 whitespace-pre-wrap rounded-xl border border-white/8 bg-black/20 p-3 text-xs leading-6 text-textMuted">{email.body}</pre>
            </div>
          ))}
        </div>
      </Card>
    </div>
  );
}
